### ISSUE TITLE
Admin ability to search all Kits

### ISSUE THREAD

**Issue by LASHirsh** [DukeLearningInnovation/kits#101]
As a system admin, I can browse, search, and manage all kits so that I can provide the kind of technical support for which I am responsible. - Please refer to #440 for all admin features.

How might we (the Kits project team) enable system admins to support the university's use of Kits?

This issue is specific to allowing an admin to search across all Kits 

**Questions**

**Assumptions**

**Hypotheses**

**Comment by joliet** [comment]
This is related to feature:
Create an Admin area for Kits where all admin features live - https://github.com/DukeLearningInnovation/kits/issues/440

**Comment by joliet** [comment]
@curiousmustard The use case for this feature is that when troubleshooting issues, we will likely have the name of the kit in question, and simply need a way to search for, and then view, the kit with full access.  We might be able to accomplish this with the existing search box on the main My Kits page (as long as this is technically feasible).

<img width="847" alt="Admin_Search_For_Kit" src="https://user-images.githubusercontent.com/7387760/65649764-f0a6c480-dfd5-11e9-943e-027cb266c556.png">

Another use case for this is that there may be times that an issue is not specific to a kit, but a range of kits created during a time frame.  Being able to see a table list view kits in the system with column headers with relevant kit data (name, semester, category, creator, date added) would be helpful.  This option could live under the My Kits menu as a menu item for Admins (View all kits).

<img width="1042" alt="View_All_Kits_Under_My_Kits" src="https://user-images.githubusercontent.com/7387760/65649903-7460b100-dfd6-11e9-9e24-ddf37bb25145.png">

This page would need a search box as well to find specific kits.

**Comment by joliet** [comment]
Update to this feature.  We decided that in order for a Kits Admin to be able to act on a kit with instructor privileges, they need to search for the kit in the Admin Console.  We will not use the search box in the main Kits application UI for Kits Admins to find kits.  So, ignore my screenshots from above on Sept 25.  That is replaced with the work on #440 .

**Comment by joliet** [comment]
Feature doc for Admin Console here - https://docs.google.com/document/d/12ekaI9uEZTUcPE2bDiUdpSdNoTUf_W3zb3RhoXq92CA/edit?usp=sharing

**Comment by curiousmustard** [comment]
Mockups for this are in Zeplin: https://app.zeplin.io/project/5b214027c1eddc64606dc242/dashboard?seid=5e9f5d937ab1c37ca72d9309

Added a "clear" button to clear out a search, otherwise this is what Jolie has in the feature doc for the Admin Console

**Comment by swwalker** [comment]
Notes from team discussion:

Search Kit ID, Display Name, Creator
Course name is clickable to open the card
Use same pagination as used on Create Combined Kits

**Comment by outten45** [comment]
From meeting today: Limit results to the first 50 kits that come back and not full server side pagination.

**Comment by outten45** [comment]
From meeting today: Limit results to the first 50 kits that come back and not full server side pagination.

**Comment by joliet** [comment]
Tested https://kits-test.oit.duke.edu/toolkits2/admin/search by searching for 'compsci' (showed results), 'ece' (showed results) and known add ahoc titles such as 'kit' (showed results).  Searching and showing results seems to be working fine but I can only access and update adhoc kits, including combined kits.  Official course kits show for a millisecond then disappear.
