### ISSUE TITLE
[MANAGE REPORTS] As a system admin, I want to run reports on how the system is being used so that this information can be used for annual reporting and making decisions about resource allocation and future integrations.

### ISSUE THREAD

**Issue by LASHirsh** [DukeLearningInnovation/kits#102]
Break this down into separate user stories: 

- how often and when people are accessing this site 
- what tools/URLs individuals and communities are using

**Comment by profmikegreene** [comment]
admins need to know if a person used it just to add their TA via sakai embed vs batch create vs other use cases
