### ISSUE TITLE
Admin access to view activity logs

### ISSUE THREAD

**Issue by LASHirsh** [DukeLearningInnovation/kits#104]
As a system admin, I need to browse, search, and filter user activity logs so that I can troubleshoot system issues with users.

How might we (the Kits project team) give system admins access to view the activity logs of all users?

**Questions**

**Assumptions**

**Hypotheses**

**Comment by joliet** [comment]
This is related to feature:
Create an Admin area for Kits where all admin features live - https://github.com/DukeLearningInnovation/kits/issues/440

**Comment by swwalker** [comment]
@joliet - Please confirm that this Toolkits feature is currently being used and provides benefit

**Comment by joliet** [comment]
This looks great @noahhh .  Testing this new feature, I found the following issues:

- Default sort for table activity should be reverse chronological (most recent first).
- Filtered results disappear when using the sort by date/time option.
- Sorting by Duke ID results in the error " The page you were looking for doesn't exist. You may have mistyped the address or the page may have moved. Need some assistance? Send us a help request."
- No sort for Display Name (useful when evaluating kit activity and by whom).
- Clear button removes filter options but does not reset activity results to default (all activity, most recent first).
