### ISSUE TITLE
create a content creation mockup using Negotiation DLX module

### ISSUE THREAD

**Issue by profmikegreene** [DukeLearningInnovation/kits#11]
Give us something to test with students, faculty, and Duke community and build the narratives around how to communicate these ideas.

**Comment by JustinJohnsen** [comment]
Do we still want to do this?

**Comment by profmikegreene** [comment]
Definitely not a requirement, but seemed like a useful module to keep in the back of our minds since several of us were familiar with it and have the faculty’s permission to use it in projects.
