### ISSUE TITLE
Impersonate a user

### ISSUE THREAD

**Issue by mccahill** [DukeLearningInnovation/kits#117]
I am *support staff* trying to *troubleshoot an issue* but *can't accurately understand the issue i'm troubleshooting* because *the user's view/account/permissions is different than mine* which makes me feel *disappointed that I can't help them*.

How might we (the Kits project team) enable support staff with the appropriate access to impersonate the user so we can see exactly what they do?

### Assumptions

- This action must be logged to an auditor log that the application admin an inspect and search. 
- Activities that the support staff perform on behalf of the user while in impersonation mode are also logged to the audit log.

**Comment by curiousmustard** [comment]
Added wireframes/mockups for this issue to Freehand board: [https://projects.invisionapp.com/freehand/document/2sINaXZDI](https://projects.invisionapp.com/freehand/document/2sINaXZDI)

**Comment by noahhh** [comment]
@profmikegreene this option is available to users we have marked as super_admins.  From your team, only you are a super admin right now.  Could you give me a list of netids for other users who you would like to have access?

@ewendland23 Is it alright to add any additional users to super_admins, or should I create our own toolkits2_admin group for this and any future admin functionality we add?

**Comment by profmikegreene** [comment]
Can we autofocus the user lookup textbox on /admin/impersonate ?
Can we add the impersonated users name to the banner at the bottom so it says "you are acting as first last (netid)"?

Exit impersonation doesn't seem to be working, check logs on 4/18/19 9:30am. Logging out and logging back in did fix it though.

**Comment by noahhh** [comment]
@profmikegreene The first two items from your previous comment are now in test

**Comment by noahhh** [comment]
@profmikegreene I believe I have fixed the Exit impersonation issue you were having.  When possible, could you try again?

**Comment by profmikegreene** [comment]
6/6/19 Testing results

* exit impersonation working
* add app, edit membership, notify kit while impersonated working
* I did several impersonations at 8:55 EDT on 6/6/19 if you need to verify the audit logging is working properly

**bugs**
* no bugs

**enhancements**
* impersonate, add user to kit, impersonate that user - did not show the kit. logout/in, impersonate did however. It would be worth exploring how we could get new kits to show up without logout/in next quarter, I can see that easing the rollout and support burden.

**Comment by swwalker** [comment]
@noahh - see Michael's feedback above.  Would you prefer to implement this enhancement, or would you like a new issue created that we track and prioritize separately?  It depends on whether you think this is simple and quick to add, or if it will require more work.

**Comment by noahhh** [comment]
@swwalker this is something I would need to talk to Liz about, I think.  The reason log out/log in worked is because it refreshed the user/pulled in their new ismemberof information and set it.  We have the app set to refresh a user every 60 minutes, but this is only set to refresh the session (logged in) user, not the users we add to a course.

**Comment by swwalker** [comment]
@noahh - I'll create a new issue for the enhancement, and flag it for review.  You can close this issue once you've moved the code to production.
