### ISSUE TITLE
As an admin, I need to de-provision tools and communities because of governance policies or terminated license agreements

### ISSUE THREAD

**Issue by mccahill** [DukeLearningInnovation/kits#119]
For undergrad courses we currently have a 4 year data retention policy. At the end of the 4 year period, the admin needs an automated way to de-provision the community and the tools which it created.

**Comment by profmikegreene** [comment]
I'd recommend using 5 years as we've done with Sakai and implementing more like what the sites@duke team has done for wordpress.

**Comment by swwalker** [comment]
closed - incorporated in #111
