### ISSUE TITLE
User-created kits

### ISSUE THREAD

**Issue by profmikegreene** [DukeLearningInnovation/kits#126]
I am *an instructor* trying to *create kits for other learning experiences than official courses* but *there is no way to add another learning experience on kits.duke.edu*

Primary need is to allow LI to add courses without rosters.  Want to be sure that new kits are learning communities.  Examples - Alumni, Co-Lab

Architect to allow create permissions to expand to wider groups in future releases

Can use same roles, since they are still learning communities, but not necessarily semester based.

May impact/be impacted by #384 Kit menu re-work

**Questions**

1. When creating a kit, the authorized user can select from a list of categories.  When this feature is made more broadly available to others than Kit admins, there will need to be a way to restrict the categories available based on user.  How will this be managed?

2. When creating a kit, the user will be able to define an alphanumeric Kit ID.  The system will need to ensure uniqueness for resource allocation and group manager groups behind the scenes, could a unique identifier be appended to the category/kit id combination?

**Related Problem Statements**
#92 #369 #130 #110 #164

**Comment by profmikegreene** [comment]
Examples: alumni learning, colab roots

**Comment by swwalker** [comment]
@profmikegreene, @joliet @chrislorch - Discussion in the working session on 3/19 indicated that some level of bulk add of members to a roster may be needed to make user-created kits more user-friendly.  This item was not included in the original scope, but there are existing ux artifacts by Lauren that can be leveraged, and the ability to bulk add based on netid exists in toolkits.  We wouldn't be able to implement all of the options listed in the bulk add issue (#92), but may be able to slip an initial version of this feature into FY19, as time/budget allows and if what can be accomplished within those parameters would provide sufficient benefit for the use cases to be handled by this release (co-lab, alumni learning).  

Which bulk add option would be the most useful and at the top of the wish list if only one option could be included to support user-created kits?

**Comment by curiousmustard** [comment]
![126_UserCreatedKit_01](https://user-images.githubusercontent.com/18170417/56133986-a36cf400-5f5b-11e9-900d-b5bcb5c4fafa.JPG)
![126_UserCreatedKit_02](https://user-images.githubusercontent.com/18170417/56133987-a36cf400-5f5b-11e9-8d21-aa7ee0a862a7.JPG)
![126_UserCreatedKit_03](https://user-images.githubusercontent.com/18170417/56133988-a36cf400-5f5b-11e9-891c-5f23084cc7e1.JPG)

Wireframe sketches for team review.

**Comment by curiousmustard** [comment]
Updated mockups on Freehand for review. Needs decision on Bulk Add and any edits before I upload to Zeplin for Noah.
https://projects.invisionapp.com/freehand/document/2sINaXZDI

**Comment by curiousmustard** [comment]
Uploaded design mockups to Zeplin: https://zpl.io/a74KXdp

**Comment by curiousmustard** [comment]
Added mockup for snackbar confirmation message after user creates kit: https://zpl.io/V0LG539

**Comment by LASHirsh** [comment]
@noahhh , can you change the title of the Custom Kit screen from "Custom Kit" to "Create Custom Kit"? And change the button text from "SAVE KIT" to "CREATE KIT"?

**Comment by noahhh** [comment]
@LASHirsh Sure.  When editing a kit, should it say 'Edit Custom Kit' and the button text at that point be 'SAVE KIT'?

**Comment by LASHirsh** [comment]
@noahhh Yup! :)

**Comment by LASHirsh** [comment]
@noahhh , currently not seeing any option to Edit Custom Kit on kits-test.
<img width="362" alt="Screen Shot 2019-05-31 at 9 24 52 AM" src="https://user-images.githubusercontent.com/2487713/58708594-3cc65d00-8386-11e9-9d4b-93f6f93cdc31.png">

**Comment by noahhh** [comment]
@LASHirsh these changes should be in there now.  Let me know if you can't see the 'Edit Kit' button in the kabob.

**Comment by LASHirsh** [comment]
@noahhh , yes, I now have the option! I see on the Edit Custom Kit screen that I have the option to Delete the kit. When I click Delete, I see the confirmation modal Delete Kit?, with message: "This Kit will disappear from your account and the accounts of members added to the roster." Will deleting the kit also delete any resources that have been added to the kit? If so, that should be included in the message.

**Comment by noahhh** [comment]
@LASHirsh Correct, all resources that have been added to the Kit will be removed as well.

**Comment by LASHirsh** [comment]
Thanks for confirming @noahhh ! Okay, please edit the modal message to say: 

"This Kit and its apps will be removed from your account and the accounts of members added to the roster."

(I think 'disappear' implies that the resources still exist but just aren't visible on My Kits).

**Comment by LASHirsh** [comment]
I know @curiousmustard is going to add a separate issue re: replacing the custom kit creation confirmation screen with snackbars on the MyKits page. For the time being, @noahhh , let's just change the text to get rid of the typo or use some alternate text like: "We are setting up your new custom kit. You will be redirected when the setup is complete."
<img width="689" alt="Screen Shot 2019-05-30 at 12 58 50 PM" src="https://user-images.githubusercontent.com/2487713/58727608-cee45a80-83b2-11e9-894a-e3793f21361f.png">

**Comment by profmikegreene** [comment]
6/6/19 Testing results

**bugs**
* roles list had 2 entries for instructor, assistant, and student. visitor only 1. once I added someone, the data table drop down only had 1 entry for each role. toolkits1 role dropdown also had double entries.
* adding sakai, populate the site title with the kit title instead of "non sis course site"
* Edit kit screen needs a cancel button. I almost hit delete several times on accident.
* I'm not sure the sakai site was actually created, it looks like it didn't pick up my changed site title/id. all other apps worked except panopto which looks like it never finished setup -- adhoc_course/347

**enhancements**
* it would be cool if the mockup to the right auto populated what you typed
* don't remove the typed content when someone uses special characters in the kit id or displayname, just show the error snackbar
* I hit save kit and "The course you are attempting to view this page for is still being set up. Please wait while we complete the setup. You will be redirected upon completion" [Duke | Log In](https://kits-test.oit.duke.edu/toolkits2/manage_members/347/edit) I let the browser do it's auto refresh thing for about a minute then it moved onto manage membership. Can we style this differently to look like the app instead of ruby native?
* is it possible to change the resource naming strategy to kits:name:kittypeid and not have adhoc in there?

**Comment by noahhh** [comment]
@curiousmustard could you do a quick mockup of having the save/cancel/delete buttons?  I'm not sure what order/spacing between them and all that (or just come over and point at my screen where they should go)

**Comment by noahhh** [comment]
@profmikegreene Do you have a list of all the Categories we have (for now)?

**Comment by curiousmustard** [comment]
@noahhh Mockup of buttons! https://zpl.io/VqvD7WZ

**Comment by profmikegreene** [comment]
@noahhh Let's start with these. Alpha sort is fine, I don't think we have a sense of which will be most popular at this time.

Alumni
Co-Lab
Divinity
Fuqua
Law
Medicine
Nursing
Nicholas
Pratt
Sanford
Trinity

**Comment by noahhh** [comment]
@swwalker the mockup populating would have to be its own issue.  Currently the mockup is just an image, so we can't manipulate it.  Doing so would require adding React to that page to mock up a Kit and then adding the functionality/design needed to change it based on input.

The 'save kit' page would need to be a ticket for design from @curiousmustard/the CRUX team.

**Comment by profmikegreene** [comment]
Button mockup looks good @curiousmustard

**Comment by LASHirsh** [comment]
@swwalker, my questions: 

- did we determine that (for now) users will not be allowed to combine custom/user-created kits? 
- we decided that (for now) users will not be allowed to add/remove kits from a combined kit once created, correct?

**Comment by swwalker** [comment]
@LASHirsh 

No limitations were put on combining user-created kits.
Users should be allowed to add/remove kits from a combined kit once created.  The intention is the combined kit is simply a collection of existing kits, so if an existing kit is removed from the group, it no longer has access to the shared resources, but individually still exists.

**Comment by LASHirsh** [comment]
Good, thanks. @curiousmustard will change the table headings to Kit Display Name and Kit ID (looks like @profmikegreene made a comment about it on the mockups too)

# 2 - right, I understand it individually existed after removal...just confirming there wasn't an issue with removing/adding additional kits at any point after creation.  :-)

**Comment by noahhh** [comment]
@profmikegreene @swwalker I have moved this to test, fixing the multiple roles and sakai not creating bugs.  Sakai Title was brought up in another ticket #390 but has not been resolved.

Panopto was not setting up for me, even on existing courses.  Can you verify that @profmikegreene ?  If so, that will need to be a new ticket.

We also identified a bug where the custom Sakai Title you entered did not transfer to the Sakai course, which Liz has told me is a bug in her code and she will fix but should be entered as another ticket @swwalker

**Comment by joliet** [comment]
User-created kits #126 Testing Results

**Passed**
- Clicked Create Kit button - next screen displays to name kit
- Selected category, entered kit id and display name
- Clicked the Create Kit button - see attached screen confirming kit is being created
- In user-created kit TRINITY 2019-05 Writing Placement:
- Added Panopto
- Added Warpwire (need to change this page to Warpwire from Duke Stream)
- Added Box
- Added Custom Link
- Edited Custom Link
- Removed Box
- Added Michael Greene as instructor
- Added Chris Lorch as assistant
- Added Heather Hans as student
- Added Nicholas Janes as visitor
- Notified kit

**Bugs**
- View kit as student -should students see Add App at bottom of card?
- Edited kit display name, received the attached error that something went wrong
- Message that kit is being created.  Should the attached image show or the snackbar? If not the snackbar, should the message contain @LASHirsh's changes above?

Image of kit being created message - https://www.evernote.com/l/AAPQiLNL3LVHp54Y15swXDLgpwiTK350hg8
Image of error received when editing user-created kit above - https://www.evernote.com/l/AAOdqtwqNctEY5Jr-3NpaD3lNtamSWGjuug

**Comment by noahhh** [comment]
@joliet Students can see the 'Add App' at the bottom - it takes them to custom link app, not the app store.

The attached image is what was decided on, but I think someone on CRUX was going to redesign it.

**Comment by joliet** [comment]
Thanks @noahhh.  Makes sense about student access to custom links.

**Comment by noahhh** [comment]
@joliet Editing a kit should work successfully now.
Panopto is another issue that we are looking at (I think Michael and I talked about it in another ticket somewhere?) but is unrelated to user-created kits.  It will not complete set up for any kit currently.

**Comment by noahhh** [comment]
https://github.com/DukeLearningInnovation/kits/issues/400#issuecomment-503752177

**Comment by LASHirsh** [comment]
**Usability Enhancements (on Create Custom Kit screen)**

- Add clear validation help text below the Kit ID input box, e.g., "valid characters are A-Z  a-z  0-9  _  -"
- Remove the space after the dash in the sample kit image to the right of the form
- Update error message text: "Please enter a Kit ID containing only letters, numbers, dashes, and underscores."

_Issue:_  
The Kit ID validation requirements should be made explicit to users prior to a user filling out the form, and these requirements should remain on the screen while the user is completing the form. In addition, the error message should be consistent with the language used in the form fields and elsewhere on the page/site.
- Here, some guidance is provided in the form of sample text in the Kit ID input box ("1000-01"), however that help text disappears from the screen as soon as the user begins typing and it isn't as clear if this is the required format/what characters are and are not permissible. 
- When the user attempts to create a kit with an invalid Kit ID, the error message text does not echo the language used on the Create Custom Kit screen. Current text says "Unique Name may only contain letters, numbers, dashes and underscores. Unable to create tool set". It's not immediately clear whether the Unique Name in question is the Kit ID or Kit Display Name. (Adding to the confusion, the example image on the right shows a Kit ID with a space after the dash.) And kit is referred to as "tool set."


(Also, the error message formatting looks a bit awkward to me...but I'll defer to @curiousmustard re: the line height). 

![Kits_CreateCustomKit_error](https://user-images.githubusercontent.com/2487713/60043887-22cf2000-968f-11e9-916c-3f434b8501b1.png)

**Comment by swwalker** [comment]
@LASHirsh - usability enhancements have been moved to new issue #401

**Comment by joliet** [comment]
**Research update:** In researching non_course kits created in the past few months, the most prominent use case is for provisioning Box folder probably tied with Sakai project site creation.  I did see some instances where a Sympa list was created and a WordPress site.  The last two were less common.
