### ISSUE TITLE
Remove Delegate

### ISSUE THREAD

**Issue by profmikegreene** [DukeLearningInnovation/kits#127]
* As in _instructor_ I want to _remove a delegate from acting on my behalf_ because _they are no longer authorized to do so_.
* As an _instructional support staff_ I need to _remove myself as a delegate_ because _I am no longer authorized to delegate on behalf of that user or that user no longer needs me as a delegate_. 
* As a _Kits admin_, I can _remove delegates for instructors on their behalf_ because _they don't have local support staff or are too busy or uncomfortable with technology_. 
*As a _system_, I can _remove delegates based on governance criteria set by the university_ because systems may be aware of changes that system admins or users are not
  
How might we (the Kits project team) enable users to remove other users' ability to perform tasks on their behalf?

**Comment by joliet** [comment]
This is related to feature:
Create an Admin area for Kits where all admin features live - https://github.com/DukeLearningInnovation/kits/issues/440

**Comment by swwalker** [comment]
covered by other issues.  Closing
