### ISSUE TITLE
Create merged kits

### ISSUE THREAD

**Issue by profmikegreene** [DukeLearningInnovation/kits#133]
As an instructor, I want to combine multiple rosters into one kit but the system doesn't allow me to which makes me frustrated that the system doesn't match my mental model for teaching.

How might we (the Kits project team) make Kits work for instructors who want to manage multiple courses as one?

**Questions**
- Would this feature allow for copying from semester to semester (reload roster)?  Maybe need to decouple rosters from courses in kits.  Maybe a separate feature depending on whether the same approach can be used for both use cases. See #69 Clone from existing kit

Duplicating a kit's setup to a subsequent semester will be a separate feature implemented at a future date..

- when you come from sakai how to a say/show there are multiple kits that represent me?

**Assumptions**
- Can't assume that all sections of a course should have the same kit.  
- what the end goal is that we set up the same tool for all sections at the same time
- adding multiple groups to a single resource

**Hypotheses**
- it would be easier to allow multiple groups to share a resource than to actually merge things in Kits
 - this feels related to reuse of tools across kits

- [ ] confirm wording on Barbara's sketches (Lauren)
- [ ] design (Jen)
- [ ] implementation (Noah/Liz)

**Comment by profmikegreene** [comment]
Some relevant background discussion

---
From Liz:
I discovered an issue when the ITAC meeting was held and a couple of the instructors logged in.  Here is the scenario…
 
Instructor is teaching XXXXXX:101L:06L:4020:1660.  When they go to Kits, the following process occurs:
 
Kits looks to see if there is a ‘kit’ for this yet.  There is not, so it creates one immediately and returns the new ID
Kits renders a card for this course
In the background, Kits looks to see if there is a Sakai site using this roster/provider_id
There is!  In fact, this Sakai site has 20 rosters and an associated Kit already created. 
 
The issue is what to do now…  We have 2 kits that share a Sakai site.  Should we point both at the same Sakai site?  But then, when someone in Sakai clicks ‘Add Participant’, how will we know which Toolkit they mean to use?
 
We don’t check for an existing Sakai site immediately because it would slow down the initial page draw.  If this were not the case, we could then treat the two courses as the same (something like a cross-listed course?)  Unless sometimes they want to mash courses together in Sakai, but treat separately in WordPress?
 
It almost feels like somehow when a user mashes together courses into a single Sakai site, we need to do the same thing in Kits?
 
This has not been an issue before because we only needed to link to a single kit (from any one of the multiple courses) since no one was looking at the course from the other rosters in Toolkits.
 
Does this make sense?  Do we want to make an issue for this?  I am not sure what the process is for mashing courses together so I am not sure the best way to solve this.

---

From Michael:
It does make sense and is one of the features we prioritized on the roadmap when Learning Innovation met a couple weeks ago. 

This doesn’t seem like an easy change though, is there a temporary solution we need to implement?

---

From Liz:
The easiest thing is to let multiple Kits reference the same Sakai site.

The problem with this is when you then link from Sakai back to Kits to add members.  I am assuming people in this situation are already Sakai-centric since they merged courses in Sakai.  They probably don’t care about what one sees in Kits.  If we could somehow mark a Kit as ‘primary’ for Sakai… then we can always link to that when they click through.
 
---

From Michael:
So, if we implement this change, in Sakai/Toolkits they'd see all the people they've added from all the various rosters and in Kits, they'd have to go to each kit to see the specific roster and we'd define the first one as the "primary" and that's where they'd see guests no on a roster. Is that correct?

If we don't implement this change, is the faculty's course now unable to add/remove participants in Toolkits?

---

From Jolie:
I agree with Liz's assumption that when a user mashes courses together into a single site in Sakai, we need to do that same thing in Kits.  If there's a quicker solution that we need to implement to move forward with our current beta pilot or to solve an immediate problem with adding participants to active Sakai sites, that's ok.  Linking a primary Kit to a Sakai site seems reasonable to me.

And I think Liz is also right that most (not all!) users don't pay much attention to Toolkits participants when they add new participants to Sakai sites.  The participant list in Sakai is the one they are more focused on.  If we were to replace the Sakai participant list with the participant list in Toolkits/Kits in the future, which has been discussed, we would definitely need to make sure that the participant list is reflective of all rosters and participants in the Sakai site.

**Comment by swwalker** [comment]
@joliet, @profmikegreene - During the sprint retro meeting last Thursday, Barbara reviewed the updates to the Merge/Combine Kits functionality per our working session the prior week.  @ewendland23 and @noahh will begin working on this feature this week and will have questions about how this should work from a Sakai perspective.  The current specs are as follows:

- an instructor can create an "umbrella" kit (skulk) in Kits and link other Kits (for which they are an instructor) to that umbrella kit
- apps provisioned at the umbrella kit level will be accessible by all kits in that umbrella
- apps provisioned at the individual kit level will only be accessible by that kit

For example, an instructor can create a combined kit/skulk/umbrella and call it COMPSCI 101, and associate individual kits for COMPSCI 101.1, 101.2., 101.3, etc.  Then, if they add an app to COMPSCI 101, it will be accessible by all kit members in sections 1, 2, and 3.  If they add an app to COMPSCI 101.1, it will only be available to COMPSCI 101.1 kit members. 

Based on the previous discussion of this issue, some of the questions about how this will work in practice include

- what happens if the instructor has already merged in Sakai?  Do we create the combined kit in Kits for them, or do we prevent them from merging in Sakai and drive them to Kits?  or something in between?
- what if there are already Sakai sites provisioned for the individual sections and then a Sakai site is provisioned for the skulk/umbrella/combined kit?  Is it feasible technically and from a user perspective to provision another Sakai site for the combined kit, which would result in a single section having 2 Sakai sites displayed?

**Comment by joliet** [comment]
Combined Kits testing:

1. Created toolkits for ECE 110L - 01, ECE 110L - 02, ECE 110L9 - 01, ECE 110L9 - 02 on toolkits-test
2. Added me (jgt10) to the toolkits above as an instructor
3. Logged in to kits-test.oit.duke.edu
4. Clicked on My Kits, Create Combined Kit
5. Checked the boxes for kits to combine
6. Clicked the Add Kits button
7. On the next screen, clicked Confirm Kits
8. On the next screen, I entered the display name "Elec and Comp Engr Foundations"
for the combined kit in the text box
9. Clicked the Create Combined Kit
10. Was presented with the "your kit is being setup" notification
11. After a few minutes, the View/Edit participants to kit page was displayed.
12. I added Andrea Novicki (anovicki) to the ECE 110L -01 kit.
13. I clicked the Done button.
14. I clicked the text BACK TO MY KITS.
15. The main page of Kits showed my combined kit with the correct display name and associated kits.
16. Clicking View/Edit kit in the kebab showed all the cards for each kit in the combined kit on the View Combined Kit page.
17. Going back to My Kits, I clicked on Add App for the combined kit and added a custom link and Box.
18. When I go to Edit/View kit, I do not see the apps for the combined kit on the cards for the kits in the combined kit.  I should, right?
19. When I add a custom link to the one of the kits, such as ECE 110L9 - 01L, I do not see this app on the combined kit, only on the card for the course/section where I added the app.
20. None of the kits in my combined kit have a semester defined.  For instance, the name shows ECE 110L - 01 undefined, where "undefined" would be the semester.

Issues:

- The lag time between steps 9 and 11 above is long enough that it will be confusing for users to wait and then end up at the Add Participants screen.  Maybe just create the combined kit and have the creator click on the kebab to access View/Edit Roster to add folks once the kit is created?
- None of the individual kits in the combined kit have a semester in the title.  They all show the semester as "undefined" (should be Fall 2019).

Possible enhancements:

- Restyle this page?  I think we may have discussed this already?
<img width="1143" alt="Duke_Kits_Setup_Message" src="https://user-images.githubusercontent.com/7387760/61658743-fdd0cb80-ac93-11e9-8bbb-2f180e69074d.png">

**Comment by noahhh** [comment]
@joliet Thank you for testing so soon!  I am deploying a fix for #18 now.  I have it set to create the connection from parent kit to child kit if the privacy level is set to everyone - does that make sense to you?

The deploy should also fix the 'no semester in title' issue.

For the lag time, that probably is related to https://github.com/DukeLearningInnovation/kits/issues/406
