### ISSUE TITLE
Who can view community membership as it relates to FERPA?

### ISSUE THREAD

**Issue by profmikegreene** [DukeLearningInnovation/kits#134]
Who can view the membership as it relates to FERPA? What user info can each user see about others? If users can customize nouns in the system, who can see the default system nouns and how?

**Comment by profmikegreene** [comment]
Who can view the membership as it relates to FERPA? What user info can each user see about others? If users can customize nouns in the system, who can see the default system nouns and how?

**Comment by LASHirsh** [comment]
We have decided to remove filtering for MVP1.

**Comment by LASHirsh** [comment]
During EPIC 2 testing (sprint 4), we received a lot of feedback (unsurprisingly) that instructors feel it is very important that they be able to see the names/emails of everyone in their course, including those who are have FERPA flags on their accounts in PeopleSoft. This is not how current Toolkits is set up, even for course groups. How do we go about getting this access for course instructors viewing their course rosters in this application?

**Comment by swwalker** [comment]
@ewendland23 - who can make the decision to allow instructors to view class rosters in Toolkits?  I assume instructors must be able to see this in Sakai.

**Comment by ewendland23** [comment]
I don't know how it works in Sakai - ask LI?  And IDM could answer issues about seeing hidden attributes.  Again, not me.

**Comment by swwalker** [comment]
Thanks, Liz.  Just checking to see if you knew, given your institutional and toolkits knowledge.

**Comment by swwalker** [comment]
@profmikegreene  - the viewing of names protected by FERPA would need to be handled at the toolkits role level, since this is a permission that applies within the toolkits app itself.  Would this apply only to leaders, then, or potentially to leaders and assistants?

**Comment by swwalker** [comment]
@profmikegreene - @outten45 can follow up with Identity Management and the Registrar once we have clarification on who in a community should be able to view the information for FERPA protected individuals with the Kits app.  Assuming anybody with an instructor (leader) role would like to have view access - what about those with the TA (assistant) role?

**Comment by swwalker** [comment]
During 7/19 team meeting, agreed that for MVP1 we would request access for leaders to FERPA protected information.  @ewendland23 will test how Sakai treats Ferpa info.

**Comment by swwalker** [comment]
@ewendland23. @outten45, @profmikegreene - who has point to put in the request for FERPA access for Kits?

**Comment by LASHirsh** [comment]
Thanks @ewendland23! Just to confirm, we are requesting access to view FERPA data for instructors AND assistants, right?

**Comment by ewendland23** [comment]
I requested that our service account can read suppressed records like the Sakai one does.  But, then we don't know that they are suppressed so everyone in the community can see it.  As far as I know?

Is there anyway someone else can talk to IDM to see how we should handle this?  I don't want to be the one in charge of FERPA decisions.  We have no precedent for showing Students the class roster as far as I know - I don't see it as a student in Sakai.

**Comment by swwalker** [comment]
@ewendland23 - would there be a FERPA flag available so we know who is suppressed?
@outten45 - are you still willing to talk about this with our IDM team?

**Comment by ewendland23** [comment]
@swwalker  - I don't know how to tell if they are suppressed.  That would be something to find out from IDM.

**Comment by outten45** [comment]
I talked IDM and they have web services for handling this kind of information. I'm going to setup a time to talk with them about the details (including @ewendland23 and @noahhh).

**Comment by swwalker** [comment]
Team discussion regarding relative complexity.  May be that netid is what we show for now.  Richard and Liz to meet with IDM next week.  Based on that meeting, regroup with team to possibly delay display of suppressed info to a future release and restrict display for MVP1.

**Comment by outten45** [comment]
After talking with IDM, our plan is the following:

* We will populate the data coming in with public only data.
* If a particular user has access to see protected data (like the leader) and there is someone in the list with missing data, we'll make a call to the IDM service (with proxy token) to fetch the data that person is allowed to see.

IDM is recommending this approach (they are actually using it with their applications).

What this means for the user?

You might notice someone on the list that doesn't have a name initially, but once we get it back, we switch to showing the name in the list (for example, on the manage members page).

Hopefully that makes sense, but we can discuss again if needed.

**Comment by curiousmustard** [comment]
@outten45 Lauren and I are wondering if this means that students will be able to view the Roster with the public data in this first version of Kits?

**Comment by LASHirsh** [comment]
@outten45 and Assistants will be able to view the protected data, correct?

**Comment by outten45** [comment]
Yes, that is the goal. We need to get access to the web service and then do some testing to see how it does (does it perform well enough and how does it appear to the user). With so few people with protected flags, it should probably be fine.
