### ISSUE TITLE
As a leader, I select a tool and add it to my community so that members have access to it

### ISSUE THREAD

**Issue by profmikegreene** [DukeLearningInnovation/kits#140]
- [ ] add tool from browse
- [ ] add tool from tool details

**Comment by profmikegreene** [comment]
Some tools in toolkits currently ask users to accept terms and conditions, not the actual app's TOC but some subset of policies we've created. How do we want to handle this moving forward @profmikegreene?

**Comment by swwalker** [comment]
Closed - user story added to #201
