### ISSUE TITLE
In-App Support

### ISSUE THREAD

**Issue by profmikegreene** [DukeLearningInnovation/kits#153]
### Description
Provide user-accessible on-line help within Kits.  Option is within the hamburger menu in the header

### Tasks
- [ ] link form in Kits UI https://duke.qualtrics.com/jfe/form/SV_9LJmzmbph6OU2Gx
- [ ] Develop Online Help Content

**Comment by swwalker** [comment]
@profmikegreene - please clarify in the description what we mean by "user support".  Is this in-app help/support/notifications or help desk level support?  If both, I recommend splitting out to two issues.

**Comment by profmikegreene** [comment]
user self-service in app or out would be a piece of user support, but also how the service desk, learning innovation, and project team handle Tier 1-3 support calls as well. 

We've had some preliminary discussion, I believe in app walkthrough/demo was deemed out of scope for MVP1.

A recommendation I'll put forth to the project team for discussion.
- icon in lower right that links to a 1-2 open question qualtrics form for feedback
- tier 1-2 support calls are routed to learning innovation
- tier 3 support calls are routed from learning innovation to the project team (which will need a service now group setup unless there's a better way to handle that)

**Comment by profmikegreene** [comment]
looks done to me

**Comment by profmikegreene** [comment]
verified in multiple browsers
