### ISSUE TITLE
supporting the unsupported users/user choices

### ISSUE THREAD

**Issue by profmikegreene** [DukeLearningInnovation/kits#17]
We hypothesize that there are significant user bases who will want decentralized or unsupported options run at a school, department, or individual level and that we must support those in this framework.

**Comment by JustinJohnsen** [comment]
We'll need to define what 'support' means for unsupported options.

**Comment by profmikegreene** [comment]
At first I was going down this route:
OIT/LI managed apps = full tier 1-3 support from OIT/LI
School/Department managed apps = perhaps one of our policies with integrating these is the school must provide tier 1-2 support or links to vendor self-support
Custom apps #39 = no support

But I'm not sure that works out in all scenarios. What's the current Voicethread support model? That's an LI licensed tool with a different support need than Sakai/Extend.

For custom links that we decide to add to /apps, it seems reasonable to include a link to vendor documentation for self-support as the upper limit, no?

**Comment by JustinJohnsen** [comment]
I think from our perspective it makes good sense to do it this way. I'm a bit worried about the student perspective, where they will not necessarily even know which apps are given local support or not, and would possibly have a very uneven support experience, all of which lands on learn.duke's plate.

**Comment by profmikegreene** [comment]
Good point, maybe our UI could have a single 'support' icon regardless of what that support looks like for that tool and we can send students to the appropriate place.

**Comment by profmikegreene** [comment]
- [ ] rewrite as user story
