### ISSUE TITLE
As a leader or assistant, I want to add a tool to my community that I use to help teach the course but that students and guests/visitors/auditors never need to access or even know I'm using so that I can get to it easily.

### ISSUE THREAD

**Issue by LASHirsh** [DukeLearningInnovation/kits#175]

**Comment by swwalker** [comment]
@profmikegreene - Is this critical for MVP1 or can we push this to a future release?  Trying to gauge frequency of the use case.  Is this functionality currently available in toolkits?

**Comment by swwalker** [comment]
Closed - incorporated in #198, #224, and #236
