### ISSUE TITLE
create role map for each app

### ISSUE THREAD

**Issue by LASHirsh** [DukeLearningInnovation/kits#189]

**Comment by swwalker** [comment]
#115

**Comment by swwalker** [comment]
Here is a start at the role mapping needed.  There is a distinction to be made between what is displayed to the users to make the labels meaningful, what the permissions are within the toolkit app itself, and what the default permissions are for each tool/app associated with the community.  It also sounds like we may alter the UI display depending on the type of community.

Here is my first draft of the role mapping.  Feel free to update/modify the file itself and/or comment.  

[role mapping.xlsx](https://github.com/DukeLearningInnovation/learn.duke/files/2134034/role.mapping.xlsx)

**Comment by profmikegreene** [comment]
I committed your spreadsheet to the repo @swwalker and changed the link in your comment. This way it'll have version control on it. I'll add stuff shortly.
