### ISSUE TITLE
User Experience definition for managing delegates

### ISSUE THREAD

**Issue by swwalker** [DukeLearningInnovation/kits#200]

**Comment by swwalker** [comment]
User stories: #127, #128, #129

**Comment by profmikegreene** [comment]
@ewendland23 do you have data on how many delegates are added each year?

**Comment by chrislorch** [comment]
^specifically, do Super Delegates for schools/departments often add instructor delegates without OIT/LI involvement?

**Comment by bap13** [comment]
@curiousmustard has the wireframes and this can be designed in sprint 7

**Comment by curiousmustard** [comment]
I've got mockups in [Zeplin](https://app.zeplin.io/project/5b214027c1eddc64606dc242/dashboard?seid=5b573f036150e73938ef6065) and [InVision](https://projects.invisionapp.com/boards/7B3NU02UC4M/) for Managing Delegates.
