### ISSUE TITLE
Add/Remove App for a Community

### ISSUE THREAD

**Issue by swwalker** [DukeLearningInnovation/kits#201]
### Description
Allow leaders and assistants in a community to add a tool from the app store for use by the community.
Access to add an app to a community includes
- Ability to add an app to a community while viewing the app store.
- Ability to add an app to a community while viewing my communities

See #225 for requirements regarding terms of service notifications

Allow leaders and assistants in a community to remove a tool from a community. Removing an app from a community only removes it from the UI, it does not decommission the instance within any of the apps (e.g., Sakai course site, wordpress site).  See issue thread below.

1. select tool or multiple tools to edit
2. choose to remove
3. ask user to confirm removal
4. save changes
5. changes to the permissions are reflected in browser upon refresh so community members don't have to log out and back in to see changes.

### User Stories
1. As a leader, I select a tool and add it to my community so that members have access to it #140
2. As a leader, I want to remove access to a tool I have added to my course and delete it from my course view because we don't want to see tools we are not using.  #91 
3. As a leader, I want to relabel a tool because I colloquially call it something else #143

### Tasks

- [ ] Define metrics to be captured #203
- [x] [Sprint 14 Functional verification](https://docs.google.com/spreadsheets/d/1obU_rOQ09-WNwM1-P7lHMHZ0tf72dQ5xdz_i5YYUY7U/edit#gid=0)

**Comment by swwalker** [comment]
Related issues:
#194

**Comment by bap13** [comment]
@thegreenbot Reference #207 for decision on how color will be applied to kits in community.

**Comment by swwalker** [comment]
Decisions made during team meeting on 7/30:
- both instructors (leaders) and assistants can manage community apps for a given community, including adding, publishing and removing
- removing an app from a community only removes it from the UI, it does not decommission the instance within any of the apps (e.g., Sakai course site, wordpress site)
- if an app has been added to a community but has not yet been published/made visible, both instructors and assistants will see the app within the community card @LASHirsh - should there be a visual indicator to instructors/assistants when viewing the community card of apps that are visible to the community vs those that are not?

**Comment by profmikegreene** [comment]
@curiousmustard we need some type of visual indicator for the visibility of the app on the card itself. Otherwise, users have to go into edit mode and view the settings for that app to see who it is shared with.

**Comment by swwalker** [comment]
Feature has been tested and any bugs/enhancements have been identified in separate issues.  Closing.
