### ISSUE TITLE
Terms of Service - Requirements for confirmation for tools

### ISSUE THREAD

**Issue by swwalker** [DukeLearningInnovation/kits#225]
For many of the apps in kits, there is a terms of service confirmation that currently displays every time an instructor/assistant adds that tool to a community.  During setup at the beginning of a semester, this may mean that one individual setting up multiple courses that use the same tool needs to confirm TOS each time they add the tool to a new course.  Is there a way to streamline the user experience in this use case?

Understand the vendor requirements for TOS for each of the following tools:
- [x] Wordpress

- [x] Box

- [x] Warpwire

**Comment by LASHirsh** [comment]
From Evan: 
...just have it displayed somewhere relatively prominent. I’d be fine with links as proposed. I’d suggest maybe an additional terms of service paragraph somewhere more broadly for Kits (in an about or bottom a page somewhere?) that notes that by using any of these applications you’re agreeing to their individual terms of service which are available in the tiles, or something like that.

**Comment by LASHirsh** [comment]
I also added text/links to both the App Details and App Store wireframes

**Comment by profmikegreene** [comment]
https://preview.uxpin.com/97f1536f1e1180fb99f4e5e05651cf146eef0747#/pages/88347557/simulate/sitemap?mode=i is the wireframe mentioned above. I like this model.

**Comment by LASHirsh** [comment]
Also this one (App Details) https://preview.uxpin.com/97f1536f1e1180fb99f4e5e05651cf146eef0747#/pages/88347452/simulate/sitemap?mode=i

see optional field added to upper right and optional section added to bottom
