### ISSUE TITLE
Questions regarding creation of a custom app link

### ISSUE THREAD

**Issue by swwalker** [DukeLearningInnovation/kits#235]
### Description
 
From Liz on 8/2/18:

- Name -how long? Does this appear under the little link Icon on the Kit card?
- URL - i assume this can be quite long
- Icon - do they get to supply this?

### Related Feature
Manage Community Private Custom Apps #224

**Comment by LASHirsh** [comment]
Kits display name - 18 chars
URL - yep
Icon - they get to choose a font-awesome icon from the FA picker on the custom link screen
