### ISSUE TITLE
Unauthenticated user access

### ISSUE THREAD

**Issue by swwalker** [DukeLearningInnovation/kits#252]
### Problem Statement
As an unauthenticated user I browse the marketing home page, about, list of apps, and app details to learn more about Kits because I'm interested in what it does.

How might we allow those who aren't logged in to learn about Kits?

### Requirements

- [x] Design marketing page to be deploy as /about @curiousmustard 
- [ ] Determine if toolkits2 can be removed from the routes and remove if possible @ewendland23 @noahhh 
- [ ] Make routes under /about accessible unauthenticated @noahhh 
- [ ] Determine if app_store/appname/details routes be changed to app_store/appname? @noahhh
- [ ] Add toolkits routes to the list below @profmikegreene 

#### Kits Routes

What should each route do when an unauthenticated user hits it?

* / and /toolkits2
    * redirect to to shib
* /toolkits2/app_store
    * redirect to to shib
* /toolkits2/app_store/{{app name}}/details
    * redirect to to shib
* /toolkits2/app_store/{{kit id}}
    * redirect to to shib
* /toolkits2/app_store/{{kit id}}/edit/{{resource id}}
    * redirect to to shib
* /toolkits2/about
    * access unathenticated
* /toolkits2/about/app_store
    * access unathenticated
* /toolkits2/about/app_store/{{app name}}/details
    * access unathenticated
* /toolkits2/manage_members/{{kit id}}
    * redirect to to shib

### Questions ###

- Can we have already authenticated users go directly to logged in content? need to follow up with IDM

### Assumptions
- 

### Hypotheses
-

**Comment by curiousmustard** [comment]
Can't continue until I meet with LI about content needs for this new marketing page. @swwalker can you set up a meeting for us sometime next week to get this going? Thanks!

**Comment by joliet** [comment]
I created a new issue for changes to the footer content of the About page currently on kits-test.  I think Jen said that these couldn't be edited according to David?  Hopefully we'll be able to get these changes in before moving to prod.

#425 Footer changes to the About page on kits-test
