### ISSUE TITLE
Toolkits regression testing

### ISSUE THREAD

**Issue by swwalker** [DukeLearningInnovation/kits#257]
Sprint 16 FQA has updated testing results https://docs.google.com/spreadsheets/d/1lbH6g2HqN2eRD8tLIC-5VvgzhmoLH5s-Asg6Qw7cbTc/edit#gid=1462110634

Sprint 14 FQA Script https://docs.google.com/spreadsheets/d/1obU_rOQ09-WNwM1-P7lHMHZ0tf72dQ5xdz_i5YYUY7U/edit#gid=0

Refer to #269 for additional tests

**Comment by profmikegreene** [comment]
How is this different from Functional QA?

**Comment by swwalker** [comment]
functional qa is related to the Kits functionality

regression testing is verification that toolkits (the original app) still works

Its actually two different tests, since we are leveraging code from an existing app to build a new one.  regression testing would focus on making sure the existing app still functions as expected.
