### ISSUE TITLE
Add user to roster using entered name, not lookup name

### ISSUE THREAD

**Issue by swwalker** [DukeLearningInnovation/kits#266]
### Feature
#199 Add/update/remove members in a community

### Description
When adding a person to the roster, the app is displaying the name and/or email address entered by the user instead of using the values from LDAP.

### Sprint 15 testing results
Logged in as saw38; Chrome browser; Public Speaking Cross-Listed course (assistant role)

Edit Mode, Add New Members
Entered Richard Outten in name field - no matches found
Entered richard.outten@duke.edu in email field - no matches found
Entered outtenr in email field, found Richard Outten:
![image](https://user-images.githubusercontent.com/38253046/48423804-54622f00-e72f-11e8-9e6c-b380b06d77a0.png)

When selected from the results, populated name field but not email address field:
![image](https://user-images.githubusercontent.com/38253046/48423858-752a8480-e72f-11e8-99e0-ba867f94996f.png)

However, searching for sombody else in email using netid (vizas), Jen Vizas was correctly returned in the results and when selected, both name and email fields were populated:

![image](https://user-images.githubusercontent.com/38253046/48424477-bcfddb80-e730-11e8-8714-70188ba15a9e.png)

However, focus remained in the email field instead of moving to the role field.

Expected results:
Richard Outten in name field should have found results
When person selected from the results drop-down, both name and email from LDAP should be populated and focus should be on Role field

**Comment by profmikegreene** [comment]
This appears to be fixed in the case of searching for Richard by name, netid/eppn. As I commented on #282 I believe this is as designed and will need refactor next release if we decide it isn't adequate.
