### ISSUE TITLE
add google analytics to production

### ISSUE THREAD

**Issue by profmikegreene** [DukeLearningInnovation/kits#271]
```Javascript
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-XXXXXXXXXX-6"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-XXXXXXXXXXX-6');
</script>
```

DM me for tracking code and send your google account email so I can add project team members to the property.

**Comment by noahhh** [comment]
Michael,

I put this code in to the new kits layout that I believe.  Are you seeing any activity for google analytics?

I have it set to run in production only, so I haven't tested it (I didn't want to populate it with misleading data)

**Comment by profmikegreene** [comment]
It's working and thank you for only putting it in prod!
