### ISSUE TITLE
saml caml ip change error

### ISSUE THREAD

**Issue by swwalker** [DukeLearningInnovation/kits#272]
User will see error when logged into kits-test and moving from wired to wireless

**Comment by ewendland23** [comment]
I was able to duplicate this problem by switching VPN contexts.  Apache Shib (traditional) redirected me to Shib in again, but once I did I was sent to the application.   SamlCamel (what kits is using) also did the redirect to re-Shib, but then when Shib sends me back to the app, SamlCaml shows the ugly error.  I was also able to duplicate this with other SamlCamel apps.  

I have notified the IDM team about the problem.

**Comment by swwalker** [comment]
Appears to have been corrected.  I have timed out in the app as well as changed IPs and am now required to reauthenticate instead of seeing the less user-friendly message.  Closing issue and will reopen if it recurs.
