### ISSUE TITLE
Instructor adding Piazza to kit receives error message

### ISSUE THREAD

**Issue by swwalker** [DukeLearningInnovation/kits#275]
### Feature
#170 Piazza Integration

### Description
I see this - workflow takes me to "We're sorry, but something went wrong." However, returning to front page, Piazza is accessible. Is it a redirect thing?

https://www.useloom.com/share/fa336697e7224cb2b45340c236b4b20a

**Comment by ewendland23** [comment]
Hey Chris,  I can't duplicate this although it happened so long ago... 

Can you try again and if it fails let me know right away via email or Teams?  So I can check the logs?

Thanks!

**Comment by profmikegreene** [comment]
Creating a fresh Piazza site as kit instructor works no problem. Waiting on a fresh batch of kits to test assistant.
