### ISSUE TITLE
Error message placement on App Store page

### ISSUE THREAD

**Issue by swwalker** [DukeLearningInnovation/kits#277]
### Feature
#228 View App Store

On desktop:
"A course needs to be chosen before an app can be added" works when user clicks grayed out Add App button, but user only sees that feedback if scrolled to the top of the page. They don't see it if scrolled to bottom of middle/bottom of the page. Choosing Add app could scroll to top where they can choose the Kit.
Even better, kit choosing may scroll along with user progress down the page, so they don't need to flip back and forth 😃

**Comment by profmikegreene** [comment]
This is done.
