### ISSUE TITLE
Change to Sakai Template copy

### ISSUE THREAD

**Issue by ewendland23** [DukeLearningInnovation/kits#278]
Nursing is reporting that their grading schema, set in the Gradebook, is not being copied from their template into the sites created via batch.  Jolie reported this to the community in this JIRA - https://jira.sakaiproject.org/browse/SAK-40786 . 

Based on Miquel's comment, we are going to experiment using copySiteContent instead of copyResources (which is what we do for batch created sites now)

**Comment by ewendland23** [comment]
Hi Jolie,

I created a site on production by cloning the Nursing Template and then using the copySiteContent option as we discussed.  The site is:
https://sakai.duke.edu/portal/site/liz_test_template_cp_1

It looks good to me - but can you check if its got what they need?  If so, assign this issue back to me and I can make a change to new Toolkits and it will be available when we roll out the new code (mid December).

Thanks!
Liz

**Comment by joliet** [comment]
Hi Liz,
Unfortunately, the Grading Schema settings (in Gradebook, Settings, Grading Schema) in the Nursing template were not copied to your site.

https://www.evernote.com/l/AAN4PH_bGmBLVIvFfRb-99ouFT8kfN5ff4Y
https://www.evernote.com/l/AANq1wc5ZOFK26XREr_Dsua7eXVz0xcKa5E

Jolie

**Comment by ewendland23** [comment]
You are right Jolie.  I just tried it again, doing exactly what Miguel did in the ticket and it does not bring the schema.  I noticed he is using a 'project' site.  Could that matter?  I also notice there is another SOAP method: copySiteContentForTool.  Maybe we have to use that?  

I am stuck on this one.  Not sure what to try next.

**Comment by joliet** [comment]
Checked recently created Nursing sites (using batch) against their template site and the grading schema looks like it matches.  I'm closing this one.
