### ISSUE TITLE
Updating roles for original course members yields unexpected results

### ISSUE THREAD

**Issue by swwalker** [DukeLearningInnovation/kits#284]
### Feature
#199 Add/update/remove members within a community

### Description
user role is changed, but a duplicate record in the roster list appears, so user "Ben Jo" is successfully changed from Student to Assistant, but there are two rows showing info for "Ben Jo". Further errors occur when attempting to change one of these two records to another role (no longer possible to change to Assistant). This error only seems to affect user records in the roster that do not have a Remove X option to the far right. Role change(s) in associated apps is unconfirmed. (Sprint 14 test results; Justin Johnsen)

### Additional information

- From testing 11/28/18 - may be related:  Sakai site "NURSING 975 - 20: Dnp Scholarly Project (Lecture)": Student Wai May Ng shows up twice in the participant list

- during verification 11/29/18, discovered Done button no longer working (issue #286 reopened).  Once 286 resolved again, will verify functionality related to role updates for course members.

**Comment by profmikegreene** [comment]
after bumping an official student up in role, the visitor option shows in the drop down. selecting it auto changes to student. would prefer it to be hidden as it is in the original drop down for official students.
