### ISSUE TITLE
Default sort order for roster

### ISSUE THREAD

**Issue by swwalker** [DukeLearningInnovation/kits#285]
### Features
#238 View Community Membership
#199 Add/update/remove members within a community

### Description
Roster sort order appears to be somewhat random.  Roster should be sorted by member last name by default. (Sprint 14 test results; Justin Johnsen)

Feedback from Noah: Sorting by last name will require text manipulation since the service provides full name, not first name/last name.  Text manipulation isn't full-proof, if somebody has a two part first name (e.g, Mary Ann).

Will implement sort by first name.

**Comment by profmikegreene** [comment]
Looks done to me.

**Comment by profmikegreene** [comment]
Verified complete in multiple kits/browsers.
