### ISSUE TITLE
Unable to easily navigate out of Delete App or View Visibility states for a community

### ISSUE THREAD

**Issue by swwalker** [DukeLearningInnovation/kits#291]
### Feature
#201 Add/Remove App for a Community

### Description
Once a user enters the Delete App mode for a course community, unable to navigate out of that mode easily.  Trash cans remain, and there is no option for a user to return to view mode.

Same experience when entering the View Visibility state.
(Sprint 14 test results - Shellene Walker)

**Comment by profmikegreene** [comment]
I get the X icon when I enter either of these two states. Looks done to me.

**Comment by profmikegreene** [comment]
verified in multiple kits/browsers.
