### ISSUE TITLE
Search when adding new members to a community yields unexpected results across browsers (spaces)

### ISSUE THREAD

**Issue by swwalker** [DukeLearningInnovation/kits#292]
### Feature
#199 Add/update/remove members within a community

Verify in
- [x] Safari
- [x] Chrome
- [x] Firefox

### Description
From Sprint 14 test results - Justin Johnsen

- [x] Furthermore, adding the space breaks the auto-fill, as in this example.
![image](https://user-images.githubusercontent.com/38253046/48371442-e0218000-e689-11e8-8049-a69964f02c4f.png)
You can see that I was zeroing in on Ethan Barber, which appears in the suggestions in the second image, but doesn't appear in the third.

**Comment by profmikegreene** [comment]
I split this into two issues and removed the second into #311
