### ISSUE TITLE
What features are important from a user's POV?

### ISSUE THREAD

**Issue by profmikegreene** [DukeLearningInnovation/kits#30]
* Calendar integration
* Document ingestion from other storage options
* Post announcements from courses

From Justin

**Comment by JustinJohnsen** [comment]
Students - submit assignments
Faculty - review (download) and grade submitted assignments

**Comment by profmikegreene** [comment]
I must have added this to MVP1 for discussion during this time, not for deployment. I do think we can start crafting user stories out of it though.

The student submits assignments is a good one to unpack as it's similar to the conversation on #49 .

A student wants a direct (deep?) link to assignment directions/submission (assumption that these are the same URL) because they want to know what's required of them right now and don't want miss something because of UI/UX.

A faculty wants a direct (deep?) link to assignment submissions because they want to grade right now.

If that direction makes sense to @DukeLearningInnovation/lts I'll pull those two out as user stories and we can all start crafting more from the other examples.

**Comment by hrvalli** [comment]
This makes sense. And I like "direct" over "deep" as the issue seems less about the level and more about the immediacy of access.
