### ISSUE TITLE
Add to roster: adding by email only works if you are searching for user's preferred email address

### ISSUE THREAD

**Issue by LASHirsh** [DukeLearningInnovation/kits#300]
Email field is only searching for Duke preferred email address (which would be either netid@duke.edu or firstname.lastname@duke.edu). Ideally, instructor can add someone by either. If someone's preferred email address is their firstname.lastname@duke.edu, the instructor would have to know to search by name or enter the netid in the name field)

Potential solution: just one search/add field that combines name and netid@duke.edu and firstname.lastname@duke.edu a la Grouper?

<img width="1243" alt="screen shot 2018-11-28 at 3 20 53 pm" src="https://user-images.githubusercontent.com/2487713/49180218-0e59bd80-f322-11e8-9217-2742cd0dfd07.png">

**Comment by JustinJohnsen** [comment]
Some related screenshots.


<img width="588" alt="screen shot 2018-11-28 at 3 27 41 pm" src="https://user-images.githubusercontent.com/13791075/49180482-cab38380-f322-11e8-9f03-089b5996b9b0.png">
<img width="582" alt="screen shot 2018-11-28 at 3 29 04 pm" src="https://user-images.githubusercontent.com/13791075/49180484-cd15dd80-f322-11e8-8dd4-5b980d5fffc9.png">
<img width="367" alt="screen shot 2018-11-28 at 3 29 18 pm" src="https://user-images.githubusercontent.com/13791075/49180489-cf783780-f322-11e8-817f-ff557ed23e26.png">

**Comment by JustinJohnsen** [comment]
Another example.

<img width="918" alt="screen shot 2018-11-28 at 3 40 34 pm" src="https://user-images.githubusercontent.com/13791075/49181011-3d712e80-f324-11e8-9adf-975bd6e510a5.png">

<img width="967" alt="screen shot 2018-11-28 at 3 40 44 pm" src="https://user-images.githubusercontent.com/13791075/49181019-42ce7900-f324-11e8-870a-60840754474c.png">
<img width="972" alt="screen shot 2018-11-28 at 3 40 59 pm" src="https://user-images.githubusercontent.com/13791075/49181020-4530d300-f324-11e8-89d4-f778468e5570.png">
