### ISSUE TITLE
===========================OVER/UNDER==========================

### ISSUE THREAD

**Issue by profmikegreene** [DukeLearningInnovation/kits#310]
Created this issue to separate what we will and won't include in the release. Everything above we include. Everything below is done post-launch

Created the `needs verification` for issues I didn't hear discussed at testing blitz and need status verified. Issues created during testing blitz don't need this label as they were verified on the latest build.

I recommend we close issues with `feature` or `eipc` labels that are in the build, move any unchecked tasks from inside them to new `task` or `bug` issues  and only create `bug` or `task` issues for things that need fixing before release.

**Comment by swwalker** [comment]
@profmikegreen - agree with last statement, with the exception of the actual app integration tickets (Sakai integration, Box, etc.).  I think keeping those open for now will help us clearly identify when apps are enabled.    All other feature/epic tickets I will review and update as needed.

Thanks for review/organization last night!
