### ISSUE TITLE
Spaces break auto-complete in membership search

### ISSUE THREAD

**Issue by profmikegreene** [DukeLearningInnovation/kits#311]
### Feature
#199 Add/update/remove members within a community

### Description
From Sprint 14 test results - Justin Johnsen

- [ ] Furthermore, adding the space breaks the auto-fill, as in this example.
![image](https://user-images.githubusercontent.com/38253046/48371442-e0218000-e689-11e8-8049-a69964f02c4f.png)
You can see that I was zeroing in on Ethan Barber, which appears in the suggestions in the second image, but doesn't appear in the third.

**Comment by swwalker** [comment]
Closing - duplicate of #292
