### ISSUE TITLE
Kits is different than building another LMS

### ISSUE THREAD

**Issue by profmikegreene** [DukeLearningInnovation/kits#32]
A traditional LMS is a collection of learning tools built together into a single product. This would be disaggregating those tools, selecting existing best-of-breeds among each tool use case, and skinning/linking/embedding them together in one place. Each tool could ideally be replaceable when necessary or desired, and the skin/shell could be replaced as well without losing any tools. The unity of the LMS made information transfer easy at the cost of having less than ideal tools and functions; the NGDLE would have the best available tools, at the cost of greater pressure on information transfer (I/O standards, APIs, LTI, QTI, etc...).
From Justin

**Comment by JustinJohnsen** [comment]
It's object-oriented programming at the application ecosystem level (without the same strong standardization of I/O between objects).

**Comment by profmikegreene** [comment]
Something this project is that an LMS isn't and most likely cannot be is a *technical specification for pedagogy* - we aren't building announcement tools, but should build a spec for what an announcement is so that any tool that provides announcements can have those announcements sent to learn.duke and displayed in a uniform way to students. LTI doesn't come anywhere close to this. [LRNWebComponents](https://github.com/lrnwebcomponents) is much closer. This is not MVP1.
