### ISSUE TITLE
Error deleting CIFS

### ISSUE THREAD

**Issue by noahhh** [DukeLearningInnovation/kits#332]
Received an error when removing CIFS app

Cog::Isilon::NotFoundError (404: Unable to open object 'english582s_01_f2018' in store 'cifscourses' -- not found.):
  
app/lib/resource/cifs_service.rb:133:in `block in destroyCourseDirectory'
app/lib/resource/cifs_service.rb:175:in `block in connection'
app/lib/resource/cifs_service.rb:169:in `connection'
app/lib/resource/cifs_service.rb:131:in `destroyCourseDirectory'
app/models/resource/cifs.rb:30:in `teardown'
app/controllers/toolkits2/app_store_controller.rb:81:in `destroy'

**Comment by vincentliu98** [comment]
CIFS was deleted successfully in the UI in kits-test

**Comment by vincentliu98** [comment]
Deleted CIFS UI reappeared in the kit...

**Comment by ewendland23** [comment]
Hi @vincentliu98 - Can you provide a little more detail on this?
Which instance?  Which course?  When you deleted it, how did you do it?

Thanks!
Liz

**Comment by swwalker** [comment]
@joliet - Please verify that this item is still open

**Comment by joliet** [comment]
@noahhh I just tested this on kits-test with kit BRAINSOC 395 - 01 F19
Connections In Brain & Society.  I added CIFS then deleted it.  Did you see the error that was originally reported in this issue?  If not, can you close this issue?

**Comment by joliet** [comment]
I have re-tested this and when I add, then delete a CIFS app on a kit, it creates and deletes successfully.  Is that all that needs testing here @noahhh ?  I'm not sure.  The original issue description references an error that looks like it would not be showing up in the UI where I can see it.  Let me know.  Happy to keep testing if needed.

**Comment by noahhh** [comment]
I do not see this error in the logs anymore.
