### ISSUE TITLE
Clicking back after being taken to app brought the 'resource being setup' snackbar

### ISSUE THREAD

**Issue by profmikegreene** [DukeLearningInnovation/kits#339]
Clicking back after being taken to WW brought the 'resource being setup' snackbar and dimmed the Warpwire app in the kit as if it was being setup again both before and after I logged into WW. this just happened with sites@duke as well

**Comment by swwalker** [comment]
@joliet @profmikegreene 

Please confirm that this is still an issue

**Comment by noahhh** [comment]
This is because the browsers 'back' button takes you back to a cached page of the browser
