### ISSUE TITLE
Test accounts not showing in user lookup in manage membership

### ISSUE THREAD

**Issue by profmikegreene** [DukeLearningInnovation/kits#340]
**Describe the bug**
Our test users (citfac and citstud) are not showing up in the add user search results

**To Reproduce**
1. Go to manage membership for a kit
1. Type `citfac` in the name or email field

**Expected behavior**
The citfac user shows up and is selectable and added to the kit.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mojave
 - Browser: Chrome
 - Version: 71.0.3578.98

**Comment by profmikegreene** [comment]
I still can't add our test users citfac/citstud. Is there something I can ask IDM to do to those accounts to get them to show up in the endpoint we're using?

**Comment by swwalker** [comment]
@noahh - please review

**Comment by noahhh** [comment]
@swwalker yes this is probably a question for IDM.  It would have been good to have someone from LI in our last meeting with Kirk, as it may fall under the same circumstances.

**Comment by outten45** [comment]
Talked with Kirk and he said it should also include service/test accounts in the change for #302.

**Comment by swwalker** [comment]
@joliet @profmikegreene 

I believe this has been addressed, but please verify

**Comment by joliet** [comment]
Re-tested and working properly now.  Was able to find two different test accounts and add them to a kit with different roles.
