### ISSUE TITLE
Production downtime notices

### ISSUE THREAD

**Issue by profmikegreene** [DukeLearningInnovation/kits#342]
- [x] toolkits.oit notice
Toolkits will be unavailable on 12/19 from 8:30-10:30 AM EST for scheduled maintenance 

- [x] sakai.duke notice
Add Participants will be unavailable on 12/19 from 8:30-10:30 AM EST for scheduled maintenance

**Comment by ewendland23** [comment]
@profmikegreene - Do you want to link the notice to anything?  Like information on Kits etc?

**Comment by ewendland23** [comment]
I have this on toolkits production now.  Let me know if you need any changes.

**Comment by profmikegreene** [comment]
Sakai notice set to go live monday morning 8am. I think the toolkits message is fine and makes sense to leave up longer as it's the entire service compared to just one piece of sakai.
