### ISSUE TITLE
Role mapping error in Piazza

### ISSUE THREAD

**Issue by vincentliu98** [DukeLearningInnovation/kits#353]
After Instructor or assistant create piazza sites from Kits, they appear to only have rights of regular students. For example, currently for instructor, there are only three options for instructors on the nav bar: "Q&A", "Resources", and "Statistics". However, there is supposed to be a "Manage Class" tab on the nav bar.

**Comment by swwalker** [comment]
@joliet - please update with latest report of error

**Comment by swwalker** [comment]
per @joliet - seems to be resolved
