### ISSUE TITLE
Batch create Sakai sites

### ISSUE THREAD

**Issue by profmikegreene** [DukeLearningInnovation/kits#354]
I am *instructional support staff* trying to *create Sakai sites for every course in our department* but because *the feature is only available in Toolkits* which makes me feel *like i'm using an antiquated system*.

How might we (the Kits project team) allow instructional staff to batch create sakai sites on behalf of their faculty?

**Comment by ewendland23** [comment]
I hope that we can move all our 'Admin' pages, including the Batch create to the new Kits Look.

**Comment by joliet** [comment]
This is related to feature:
Create an Admin area for Kits where all admin features live - https://github.com/DukeLearningInnovation/kits/issues/440

**Comment by joliet** [comment]
Can we use our group manager groups for Kits to control access to creating sites only within a specific discipline, program or school, similar to what we plan to do for categories and school/program level admin access?

**Comment by joliet** [comment]
I have a Google Doc that shows the workflow and details for the current design of this feature in Toolkits.  I've also done a little user research on how people use this feature and provided some rough mockups on how we might use existing page designs in Kits to make this feature available in Kits.  Take a look @curiousmustard and let me know what you think.  Once we go through it and refine it tomorrow, I will share it with it with the whole team.
https://docs.google.com/document/d/1SljyOvnSNbso0TBK1rtPNCVO5niGqknv68_TepDamEU/edit?usp=sharing

**Comment by joliet** [comment]
@noahhh Links to feature doc with overview of existing and proposed workflows (batch add users to sites is a separate issue/feature in Kits):
https://docs.google.com/document/d/1SljyOvnSNbso0TBK1rtPNCVO5niGqknv68_TepDamEU/edit?usp=sharing

Link to interactive prototype - https://invis.io/4YY5HYB8BFT
Not everything works in the prototype.  Functional steps support:

1.    Click on Batch Create Sakai Sites on the first page (admin portal)
2.    Select term 2020 Summer 1, subject Nursing, and the Nursing template from the drop downs on the next page.
3.    Select the first three courses shown in the results table for your batch.  Click Add Courses.
4.    When you see the three courses at the top in the "chosen" area, click Confirm Courses.
5.    To add Tina as a member to the sites, click the name field on the Add New Member to Site(s) page (Tina will show up automatically).  Click the Add button to the right of the role drop down.
6.    When Tina shows below as added click the Confirm Members button.
7.    You should now see the courses you've chosen to create and the members to be added.  Click Confirm Batch.
8.    Back to Admin Console main page (need snack bar confirmation here that is not part of this design.  See requirements below.)

Prototype designs use existing UI designs for the combined kits feature and Add New Members feature.

Requirements for this feature:
Course support staff use this feature to create many Sakai sites at once for their program.  Steps that support this workflow include:

- Selecting academic term and subject(s) to display courses within a specific academic term and within the scope of a specific discipline(s).
- Selecting a Sakai template (a Sakai requirement when setting up sites).
- Viewing courses that match results from the term and subject(s) selections.
- Selecting courses from the results to add to batch.
- Removing courses from batch.
- Searching for members to add to all sites created through the batch.
- Adding members to sites created through the batch.
- Removing members from list to be added to sites through batch.
- Reviewing selections of courses and members to be included in the sites batch process.
- Confirming the batch selections.
- Cancelling the batch process to start over.
- A visible system message (snack bar) after confirmation that the batch process has started (not in mockup).  Message: "The batch process has started.  Updates on batch status will be sent via email."

**Comment by joliet** [comment]
Two more issues related to this feature:
Update email address and message confirmation for Batch Create Sakai Sites #584https://github.com/DukeLearningInnovation/kits/issues/584 (Parity)
Scope access to courses in Batch Create Sakai Sites using Group Manager support groupshttps://github.com/DukeLearningInnovation/kits/issues/585 (Non-parity/enhancement)
