### ISSUE TITLE
Allow instructors to view kit as student

### ISSUE THREAD

**Issue by profmikegreene** [DukeLearningInnovation/kits#358]
I am *instructor* trying to *understand what my kit looks like to my students* but *it's not intuitive* because *view visibility is my only option* which makes me feel *unsure about my choices and scared of using Kits*.

How might we (the Kits project team) increase instructor confidence that they have set up their kit the way they want it to appear for their students?"View as [role]"

### Questions
* What are the differences in building a 'view as student' vs 'view as any other role'? The latter is preferable if it is not significantly harder to achieve.
- this is the 3 way visibility toggle on an app, not the 4 way role selector in manage groups

**Comment by curiousmustard** [comment]
Wireframe sketches here: https://projects.invisionapp.com/freehand/document/2sINaXZDI

**Comment by curiousmustard** [comment]
Mockups added to Zeplin here: https://app.zeplin.io/project/5b214027c1eddc64606dc242/dashboard?seid=5cb8caaefae8ad09e84f43d2

**Comment by profmikegreene** [comment]
looks and works good to me.

**Comment by swwalker** [comment]
@noahhh - please push to production

**Comment by noahhh** [comment]
This has been moved to production
