### ISSUE TITLE
redesign help to not go straight to qualtrics form

### ISSUE THREAD

**Issue by profmikegreene** [DukeLearningInnovation/kits#365]
I am user trying to get help with something in Kits but can't help myself because the only help currently available is a link to a qualtrics form which makes me feel annoyed that I can't solve my problem and move on.

How might we (the Kits project team) redesign help to allow self-support and gather the information needed to more quickly support users?

**Questions**

**Assumptions**

**Hypotheses**

some relevant discussion on #17

**Comment by joliet** [comment]
MVP for this is closed issue #591.
