### ISSUE TITLE
Bulk remove members from kit

### ISSUE THREAD

**Issue by profmikegreene** [DukeLearningInnovation/kits#369]
- As an instructor, I need to bulk remove netids/DUIDs/emails from a kit because they are no long part of our learning community. 
- As an instructor, I need to remove an existing grouper/LDAP/Active Directory group from my kit because they are part of our learning community

How might we (the Kits project team) enable users to easily remove multiple users from their kit?

**Comment by joliet** [comment]
This is a duplicate issue and needs to be broken down more (e.g. groups need to be discoverable in Kits before we can design for adding/removing them).
