### ISSUE TITLE
Duke Alert not styled

### ISSUE THREAD

**Issue by profmikegreene** [DukeLearningInnovation/kits#370]
**Describe the bug**
The Duke Alert notice at the top of the screen is not properly styled.

**To Reproduce**
1. Go to Kits when a Duke Alert is active

**Expected behavior**
Duke Alert is styled as a material banner

**Screenshots**
![screen shot 2019-01-12 at 10 49 57 pm](https://user-images.githubusercontent.com/3632822/51081396-93274d80-16bc-11e9-83d3-0cd90ec32cfb.png)

**Desktop (please complete the following information):**
 - OS: Mojave
 - Browser Chrome
 - Version 71.0.3578.98

**Comment by noahhh** [comment]
I believe this is already complete
