### ISSUE TITLE
add favicon to manage membership

### ISSUE THREAD

**Issue by profmikegreene** [DukeLearningInnovation/kits#373]
**Describe the bug**
No favicon for manage membership screen on kits-test

**To Reproduce**
1. Go to manage membership for a kit

**Expected behavior**
The Duke logo to appear in the favicon spot

**Desktop (please complete the following information):**
 - OS: Mojave
 - Browser: Chrome
 - Version: 71.0.3578.98

**Comment by joliet** [comment]
Not seeing the Duke favicon on the View/Edit roster page.  Tested on kits-test with kit BRAINSOC 395 - 01: Connections In Brain & Society.

**Comment by joliet** [comment]
Tested with several kits on all pages to confirm favicon is showing, including manage membership.  All pages tested have the D (Duke) favicon in the browser tab.
