### ISSUE TITLE
MS Teams integration

### ISSUE THREAD

**Issue by profmikegreene** [DukeLearningInnovation/kits#382]
I am faculty trying to use Microsoft Teams with my course but can't because it's not in the app store which makes me feel annoyed that I have to use the custom link app for an enterprise tool.

How might we (the Kits project team) integration with MS Teams?

**Questions**

**Assumptions**

**Hypotheses**

**Comment by JustinJohnsen** [comment]
Is this an authentic issue, that is, a faculty member requested this?

**Comment by JustinJohnsen** [comment]
Also, are we getting to a point where we might want to tag or otherwise label user stories, problem statements, etc... that have authentic user sources as opposed to our own hypothesized user stories?

**Comment by curiousmustard** [comment]
Logo and app icon files are in Zeplin: https://zpl.io/aXNLLoK

**Comment by joliet** [comment]
**MS Teams Integration with Kits**

The MS Teams integration with Kits will allow users to quickly setup a Team for their course or group. The integration should allow users to create a team for their group with a name that of their choice, and adds kit members to the team automatically. Students/viewers in a kit will have the same level of access in Teams added to a kit as the role Member in the MS Teams app.  Instructors/assistants/owners in a kit will have the same level of access as Owner in the MS Team app.  Visitors in a kit will have the Guest role in MS Teams.

When setting up an MS Team, options are provided for team type.  These options should be part of the setup of the app through Kits through a drop-down menu: Course, Professional Learning Community, Staff, Other.

Workflow for setting up MS Teams as an app in Kits:
Kit - > Add App - > Select App in App Store (Add App to Kit) - >  setup page for app

Page 1
![Kits_Teams_Setup_Page_1_Final](https://user-images.githubusercontent.com/7387760/76790901-1c8d5080-6796-11ea-82ba-1027d3c58c83.png)
Page 2
![Kits_Teams_Setup_Page_2_Final](https://user-images.githubusercontent.com/7387760/76790918-257e2200-6796-11ea-9f8c-ab1a5e96fa72.png)

**Comment by joliet** [comment]
Default permissions for each team type:
Class
<img width="784" alt="Class_Team_Type_Default_Permissions" src="https://user-images.githubusercontent.com/7387760/76792908-6841f900-679a-11ea-9ed0-f342939c0272.png">
Professional Learning Community
<img width="794" alt="Personal_Learning_Community_Type_Permissions" src="https://user-images.githubusercontent.com/7387760/76792924-73952480-679a-11ea-94c5-9bbcd7280d66.png">
Staff
<img width="795" alt="Staff_Team_Permissions" src="https://user-images.githubusercontent.com/7387760/76792941-7a239c00-679a-11ea-8fcc-2b54ad661f7f.png">
Other
<img width="789" alt="Other_Team_Type_Permissions" src="https://user-images.githubusercontent.com/7387760/76792957-827bd700-679a-11ea-8e60-32bb3417581a.png">

**Comment by ewendland23** [comment]
Noting here - The 'Guest' option for MS Teams is actually for allowing people outside the enterprise to become part of a Team.  It is not enabled for our instance.

Jolie and I spoke and agreed to make 'Visitors' just normal members.
