### ISSUE TITLE
Bulk add members to kit using netID

### ISSUE THREAD

**Issue by swwalker** [DukeLearningInnovation/kits#383]
I am an instructor trying to add multiple people to my Kit but can only add them one at a time in Kits because the ability to add multiple members at once based on netID currently available in Toolkits has not been implemented which makes me feel frustrated and unwilling to use Kits to manage my course communities.

**Questions**

**Assumptions**
Providing the same functionality currently available in Kits to bulk add based on netID will be sufficient to meet the requirement.

**Hypotheses**

**Related issues**
This feature will begin to address the multiple ways users may wish to add multiple members to a Kit at the same time, as outlined in #92 Bulk add members to kit

This feature will help support #126 User-created kits, where members will not be pre-populated based on course registration rosters.

**Comment by curiousmustard** [comment]
Lauren included this in her Manage Members wireframes here: https://preview.uxpin.com/97f1536f1e1180fb99f4e5e05651cf146eef0747#/pages/84401760/simulate/no-panels

<img width="553" alt="Screen Shot 2019-04-22 at 11 36 42 AM" src="https://user-images.githubusercontent.com/18170417/56508730-0c6fe100-64f3-11e9-9b66-cc30d9569964.png">

1. Assume we don't need the radial selection if we're only allowing netID (is this correct?)
2. @noahhh Would the roster table be hidden until members are added, or visible but empty?

**Comment by curiousmustard** [comment]
I can't move forward on this one until I get feedback on comment above.

**Comment by joliet** [comment]
Hi Jen.  Michael and I just discussed this.  It sounds like we need all the options - NetID, Email, DUID, and OneLink when bulk adding users to a Kit.

**Comment by swwalker** [comment]
@joliet, @profmikegreene, @curiousmustard - the bulk add of community members was not included in the original scope for this effort.  It was identified as a bonus feature that could be provided to assist with the User-Defined group creation, provided that is was limited in scope to NetID only for this round of development.

**Comment by profmikegreene** [comment]
6/6/19 Testing results

* all three options working like a charm! 

**enhancements**
* if they successfully get added to the data table, remove them from the textbox

**Comment by swwalker** [comment]
@noahh - see comments above.  Is this enhancement something that can be added now, or would you prefer a separate issue for prioritization and tracking?

**Comment by noahhh** [comment]
@swwalker this enhancement has been completed and is in test

**Comment by swwalker** [comment]
@profmikegreene - Noah has included the enhancement to remove the individual from the text box when added to the table.  Please confirm this is working as envisioned.

**Comment by profmikegreene** [comment]
@noahhh if all users in the bulk add exist then they get added to the data table and removed from the textbox. 

If you try my netid mg287 and our test user citfac (or any other invalid netid), it does show appropriate error messages about the citfac user, and adds me to the data table, but doesn't remove me from the textbox.

**Comment by swwalker** [comment]
@naohh - close issue when code is pushed to production
