### ISSUE TITLE
Cannot impersonate user

### ISSUE THREAD

**Issue by joliet** [DukeLearningInnovation/kits#385]
**Describe the bug**
Impersonate user does not work for jgt10@duke.edu

**To Reproduce**
1. Click on user menu.
2. From drop down click on Impersonate User.
3. Search for user to impersonate.
4. Click on Impersonate next to user name.

**Expected behavior**
Should see what the selected user sees with onscreen notification and Impersonate in user account area.

**Screenshots**

**Desktop (please complete the following information):**
 - MacOS High Sierra 10.13.6 (17G7024)
 - Updating Google Chrome
Version 74.0.3729.131 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by noahhh** [comment]
Hi @joliet , could you try to impersonate in kits-test.oit.duke.edu now?

**Comment by joliet** [comment]
This looks to be resolved.
