### ISSUE TITLE
same vs new tab for app launches

### ISSUE THREAD

**Issue by profmikegreene** [DukeLearningInnovation/kits#389]
i'm not really a fan of new tabs over same tab but with the browser's back button really sucking due to having to back through all the shib session create redirects, is it a better UX to do new tabs when you open an app?

**Comment by profmikegreene** [comment]
O365 does this from Teams to Outlook but not Outlook to Teams
Gmail, GDrive, and Gcal all do this

**Comment by LASHirsh** [comment]
The UX community is somewhat divided on this point. The prevailing opinion amongst those who prioritize accessibility and end-user control is not to force a new tab but back button fatigue is an important consideration here and an argument could be made that since you are launching external sites/apps, it's okay to do new tabs. I'll think on it and maybe have Joel weigh in.

**Comment by joelhsmith** [comment]
Letter of the law vs practicality:

The letter of the law is not to open links in new tabs. https://www.w3.org/TR/WCAG20-TECHS/G200.html

- It can be disorienting for people with disabilities.

- It also removes a feature from everyones web browser. Anyone can opt-into opening a link in a new tab.  Shift+click. Or right-click open in a new window.  Forcing new window basically cripples a built-in feature.

Practicality:

- Being consistent is the best way to keep people from getting disoriented. If you can't make every single person do it right, at least be consistent.

The easiest way to ensure and sighted users know what will happen when they click the link is to add a module in Drupal or Wordpress that adds that little external link icon. Those modules also usually add hidden screen reader text like <span class="element-invisible">Link is external</span>

**Comment by LASHirsh** [comment]
@profmikegreene , I recommend continuing to have apps open in the same tab for now, and let users choose whether to launch in a new tab/window or not. Revisit if we discover over time that this is problematic for our population of end users.
