### ISSUE TITLE
Refresh Kits display without requiring user to logout and log in

### ISSUE THREAD

**Issue by swwalker** [DukeLearningInnovation/kits#391]
**Describe the bug**
From Michael Greene when testing #117 Impersonate a user.

impersonate, add user to kit, impersonate that user - did not show the kit. logout/in, impersonate did however. It would be worth exploring how we could get new kits to show up without logout/in next quarter, I can see that easing the rollout and support burden.

**To Reproduce**
1. Impersonate a user (User1) that can add others to a kit
2. Add User2 to a kit
3. Impersonate User2
4. Expect to see the new kit, but it requires logout and back in to show up

**Expected behavior**
[Noah outlines the time behavior here](https://github.com/DukeLearningInnovation/kits/issues/117#issuecomment-500432363)

**Comment by swwalker** [comment]
@profmikegreene can you revise the issue description to accurately reflect the steps you took.  I wasn't clear on when you were impersonating and when you weren't.

**Comment by profmikegreene** [comment]
May be affected by #406

**Comment by joliet** [comment]
Tested this on kits-test with two different kits and in both cases, the added user could see/access the kit right after being added.

**Comment by joliet** [comment]
Tested by adding Heather Hans to kit STDYAWAY 411C - 42 F19 Study Away At Unc, and adding Tara Kramling to kit ECE 110L9 - 02L F19 Fund Of Elec And Comp Eng (Lab).
