### ISSUE TITLE
service owners run domain level queries on all custom URLS to show what tools need to be integrated next and what integrations aren't working because users manually link instead.

### ISSUE THREAD

**Issue by profmikegreene** [DukeLearningInnovation/kits#40]

**Comment by JustinJohnsen** [comment]
Does this mean we would need some way of cataloging all custom URLs included on the site? Is there relevant metadata we would need to know in order to make use of this catalog (like associated course name, instructor/author, dept, etc...)?

**Comment by swwalker** [comment]
closed - incorporated in #211
