### ISSUE TITLE
Panopto integration not working

### ISSUE THREAD

**Issue by profmikegreene** [DukeLearningInnovation/kits#400]
Panopto was not setting up for me, even on existing courses.  Can you verify that @profmikegreene ?  If so, that will need to be a new ticket.

_Originally posted by @noahhh in https://github.com/DukeLearningInnovation/kits/issues/126#issuecomment-502803607_

Testing done on Kit 347 shows that the panopto integration never finishes setup.

**Comment by profmikegreene** [comment]
Perhaps we need a "temporarily disabled" flag for apps that we can apply to them and not allow folks to try and add them to kits in circumstances like this?

**Comment by ewendland23** [comment]
We collect information from the user on which sub-host to use for new Panopto instances. In the past the sub-host also had information on the groups. Something happened and now that Group information is only available on the master host - admin.capture.duke.edu.

The Panopto soap calls have been changed to now call this host. The Panopto 'create folder' calls will still call the particular sub-host.
