### ISSUE TITLE
Usability Enhancements on Create Custom Kit screen

### ISSUE THREAD

**Issue by swwalker** [DukeLearningInnovation/kits#401]
- [x] Add clear validation help text below the Kit ID input box, e.g., "valid characters are A-Z  a-z  0-9  _  -"
- [x] Remove the space after the dash in the sample kit image to the right of the form
- [x] Update error message text: "Please enter a Kit ID containing only letters, numbers, dashes, and underscores."

_Issue:_  
The Kit ID validation requirements should be made explicit to users prior to a user filling out the form, and these requirements should remain on the screen while the user is completing the form. In addition, the error message should be consistent with the language used in the form fields and elsewhere on the page/site.
- Here, some guidance is provided in the form of sample text in the Kit ID input box ("1000-01"), however that help text disappears from the screen as soon as the user begins typing and it isn't as clear if this is the required format/what characters are and are not permissible. 
- When the user attempts to create a kit with an invalid Kit ID, the error message text does not echo the language used on the Create Custom Kit screen. Current text says "Unique Name may only contain letters, numbers, dashes and underscores. Unable to create tool set". It's not immediately clear whether the Unique Name in question is the Kit ID or Kit Display Name. (Adding to the confusion, the example image on the right shows a Kit ID with a space after the dash.) And kit is referred to as "tool set."

(Also, the error message formatting looks a bit awkward to me...but I'll defer to @curiousmustard re: the line height). 

![Kits_CreateCustomKit_error](https://user-images.githubusercontent.com/2487713/60043887-22cf2000-968f-11e9-916c-3f434b8501b1.png)

**Comment by joliet** [comment]
Re-tested on kits-test with kit TRINITY 100-101 Physics research group and the requirements listed above are all there in terms of validation/feedback for naming requirements of user-created kits.
