### ISSUE TITLE
can't delete wiki

### ISSUE THREAD

**Issue by profmikegreene** [DukeLearningInnovation/kits#404]
Wiki pages have never been deleted by Toolkits.  How should Kits handle removal of wiki resources from a Kit?

**Comment by swwalker** [comment]
@profmikegreene @joliet 

Please confirm this is still an issue and provide further detail

**Comment by joliet** [comment]
I re-tested this on kits-test with kit CO-LAB 20-0619 Python Intro and was able to successfully remove the icon from the kit through Remove App under the kabob menu.  However, the wiki is still there.  Is there a delay for deleting wikis?

**Comment by swwalker** [comment]
@joliet to work with Wiki team to determine what the process should be when a user wants to remove a wiki page.

**Comment by swwalker** [comment]
@joliet - please fill in the information from the wiki team regarding how this should work

**Comment by joliet** [comment]
Jolie to Mark, Ryn, and Liz: It looks like to me, according to the documentation for Duke Wiki, that space owners are able to delete their spaces without any kind of admin intervention or approval. So, that means to me that if kits owners create a wiki, they should be able to take action in kits to delete that space. Copying Liz and Ryn to loop them into this conversation.

From Ryn:
It makes sense to me that users should be able to do this through Kits, as space creators on the Wiki can delete their spaces.

From Mark: Sounds good. I see no problem with that as long as they're aware the space can't be recovered once deleted.

**Comment by joliet** [comment]
At our last meeting, we discussed that any tool deleted from kit would remain in a "soft delete" state for six months(?).  This would avoid the need for an "are you sure prompt" and would make it easy to recover data when mistakes are made.  Can we proceed with that solution?

**Comment by ewendland23** [comment]
There is no option for a "soft delete" with our version of Confluence.  Later versions have the idea of 'Archiving'.  I have implemented the 'hard delete' option and its ready to test on Kits-test

**Comment by joliet** [comment]
The implementation of hard delete is working on kits-test.  Although, it looks as if Archiving is possible with our current version of Confluence. Maybe you didn't have a way to access that, Liz?  I'm closing this and creating a new issue for us to implement Archiving if/when possible.
<img width="1042" alt="Wiki_Archive_Option" src="https://user-images.githubusercontent.com/7387760/76013884-aca1df00-5ee6-11ea-8d1f-b6c8da35a449.png">
