### ISSUE TITLE
force a single Sakai node/cookie

### ISSUE THREAD

**Issue by profmikegreene** [DukeLearningInnovation/kits#407]

**Comment by ewendland23** [comment]
Putting comments from Longsight here for future reference:

> 1. In production, all SOAP calls are directed to a single front-end. I believe it is ‘duke01’. What is this for sakai-test?

duketest1

> 2. If I want to have all REST calls go to the same frontend, do I change the URL for my calls or do I have to modify the cookie? What should I use to make it the same as the front-end used by SOAP?

You can do either one but cookie takes precedence. For example, if you have a cookie set in your browser, you won't be able to use the URL GET param to arrive at a specific node. But if you are sending no cookies, the GET param should work fine.

So the two methods:

1) Set a cookie of SAKAIID to "xxx.duketest1"

2) Send no cookies and append this GET param: ?SAKAIID=xxx.duketest1

**Comment by ewendland23** [comment]
This change is available to test on Toolkits-test.  I am assigning to Chris and Jolie - not sure if I need to tag it?

**Comment by joliet** [comment]
I think this is working as batch create on toolkits-test consistently creates sites with all relevant properties.
