### ISSUE TITLE
Move all sakai calls from SOAP to REST

### ISSUE THREAD

**Issue by profmikegreene** [DukeLearningInnovation/kits#410]
Not sure if this is still on the agenda or not for @ewendland23. Is this part of your work on #407 ?

**Comment by ewendland23** [comment]
Here are the SOAP methods that I don't think we have in REST.
sakai.wsdl: (https://dukedev.longsight.com//sakai-ws/soap/sakai?wsdl)
  copySite
  copyResources
  getSiteProperty
  setSiteProperty
  (and maybe copySiteContent)

longsight.wsdl:
  getSitesWithProvider

**Comment by ewendland23** [comment]
@joliet @profmikegreene @chrislorch  - After talking to Sam, it turns out we could call the SOAP methods using REST-style calls, but its still a separate system and we'd need to use a separate login still.  Is there any advantage to using REST rather than SOAP in this case?

**Comment by joliet** [comment]
I don't see the value in using REST rather than SOAP in this case @ewendland23 .  @profmikegreene and @chrislorch what are your thoughts?
