### ISSUE TITLE
Bulk add members not recognizing legitimate netids

### ISSUE THREAD

**Issue by joliet** [DukeLearningInnovation/kits#411]
Tested  #399
Tested bulk add members to kit with the following steps:

1. Went to kits.duke.edu
2. In kit CROSSLISTED COURSE Sp19, went to View/Edit Roster
3. Clicked the Edit Mode button
4. Clicked on "or bulk add members"
5. In the Add New Members text book added the following netids - hrv, mg287, cl237
6. Received the error below that none of the netids were recognized

![Kits_Bulk_Add_Error](https://user-images.githubusercontent.com/7387760/61055779-3634f780-a3c0-11e9-9958-0629a1e32e0f.png)

The error window needs some improvement with spacing.  It would also be better to have a way to close the window instead of it disappearing automatically.  Users may need to capture the problematic netids to further investigate, especially Alumni who will be using the bulk add feature often.

**Comment by noahhh** [comment]
Danai has reverted the changes to our service account.  This means we do not have access to OneLink users currently, but old functionality should be restored.

Danai will create a test service account for us that he can work on getting the access set up correctly.
