### ISSUE TITLE
Bulk add members error window styling changes

### ISSUE THREAD

**Issue by swwalker** [DukeLearningInnovation/kits#412]
### Description ###

The error window needs some improvement with spacing. It would also be better to have a way to close the window instead of it disappearing automatically. Users may need to capture the problematic netids to further investigate, especially Alumni who will be using the bulk add feature often.

Current display:
![image](https://user-images.githubusercontent.com/38253046/61220345-1feeaa80-a6e4-11e9-929a-51647fb18c7b.png)

### Related Issues ###
Found during testing of #399

**Comment by joliet** [comment]
Tested on kits-test with user-created kit TRINITY 100-101: Physics research group.  The styling of the error message has been updated and is now easier to read with better spacing, and persists.
