### ISSUE TITLE
When creating a combined kit, return user to My Kits page after setup

### ISSUE THREAD

**Issue by swwalker** [DukeLearningInnovation/kits#418]
### Description ###
When a new combined kit is being created, the current flow brings the user to the View Roster page, which assumes all users will want to immediately add individuals to the roster. However, a user may wish to provision resources first, or create multiple combined kits. Changing the flow to return to the My Kits page will allow for these differences in desired workflow.

### Related Issues ###
#133 - Create merged kits
#406 - Grouper slowdown

**Comment by joliet** [comment]
Happy to test this when the combine kits options is available again.

**Comment by noahhh** [comment]
@joliet combined kits have been turned back on in test, so this is available to look at

**Comment by joliet** [comment]
Tested on kits-test. This looks good.  Tested by creating combined kit Foundations Elec & Comp Engineering with the following kits - ECE 110L - 01 F19, ECE 110L - 02 F19, ECE 110L9 - 01L F19, ECE 110L9 - 02L F19.  Took me back to the My Kits page after creating the combined kit.
