### ISSUE TITLE
Left align items in My Kits dropdown menu

### ISSUE THREAD

**Issue by profmikegreene** [DukeLearningInnovation/kits#419]
**Describe the bug**
Items currently

**To Reproduce**
1. Go to Kits
1. Click My Kits in the top nav

* MacOS - Chrome
<img width="1440" alt="Screen Shot 2019-07-25 at 9 10 38 AM" src="https://user-images.githubusercontent.com/3632822/61877043-3ce16580-aebc-11e9-89ed-ad118816f2fd.png">

* iOS - iPad - Chrome

**Comment by noahhh** [comment]
Hi @profmikegreene , could you attach a screenshot of the issue?

**Comment by profmikegreene** [comment]
Couldn't figure out how to get the screenshot from my iPad yesterday. Got one from the Mac Chrome version now.

**Comment by noahhh** [comment]
@profmikegreene Thanks.  Completed and in test now.
