### ISSUE TITLE
Shown kit setup in progress page when tried to add app to a combined kit I didn't create

### ISSUE THREAD

**Issue by LASHirsh** [DukeLearningInnovation/kits#424]
**Describe the bug**
I am on the roster of a combined kit I did not create (Jen Test 3) and I am unable to add an app. Clicking Add App links to "https://kits-test.oit.duke.edu/toolkits2/app_store/374" and displays the kit setup screen with message, "The course you are attempting to view this page for is still being set up. Please wait while we complete the setup. You will be redirected upon completion."  

**To Reproduce**
1. Go to My Kits on https://kits-test.oit.duke.edu/toolkits2
2. Click on "Add App" in the kebab menu or the Add App icon on the kit card for Combined Kit Jen Test 3.
3. See error

**Expected behavior**
To be taken to the add custom URL screen or the app store.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Mac OS Sierra
 - Browser: Chrome
 - Version 75.0.3770.142

**Additional context**
I am not sure when @curiousmustard added me or as what role, but my only two options in the kebab menu are "Add App" and "View/Edit Kit".

Related to: [Create merged kits #133](https://github.com/DukeLearningInnovation/kits/issues/133)

**Comment by LASHirsh** [comment]
Related to: [Create merged kits #133](https://github.com/DukeLearningInnovation/kits/issues/133)

**Comment by joliet** [comment]
Tested on kits-test with combined kit Elec and Comp Engr Foundations.  Tested instructor, assistant and student roles and could not replicate.
