### ISSUE TITLE
Footer changes to the About page on kits-test

### ISSUE THREAD

**Issue by joliet** [DukeLearningInnovation/kits#425]
Responding to feedback from others in LI about the footer content on the About page, the following are suggested changes to make the content and actions more clear to users.

Need Help?
Fill out this form and we'll be in touch
(form links to the Qualtrics form)

Learn More
The Kits Project on GitHub
(GitHub links to the Kits repo on GitHub)

Get Started
Use Kits now (Duke login required)
(Kits links to kits.duke.edu)

Add this to footer between the Kits and Duke logos?
Kits is a partnership between Duke Learning Innovation and the Office for Information Technology

**Comment by swwalker** [comment]
From DWS: update available on https://kits-dev.oit.duke.edu/toolkits2/about
@noahhh - what needs to be done to get this on kits-test?

**Comment by noahhh** [comment]
This is out on test

**Comment by joliet** [comment]
LGTM.
