### ISSUE TITLE
Spacing issue with colored lines below text on About page in kits-test

### ISSUE THREAD

**Issue by joliet** [DukeLearningInnovation/kits#426]
**Describe the bug**
On the new unauthenticated About page on kits-test, the colored lines below the text under Connect, Discover, Add, and Customize are not spaced properly in Firefox Quantum 60.8.0esr (64-bit).
**To Reproduce**
1. Go to https://kits-test.oit.duke.edu/toolkits2/about
2. Scroll down to Connect, Discover, Add, Customize on page.
4. See colored line colliding with text (screenshots below).

**Expected behavior**
To see the same page as designed in Zeplin which appears fine in Chrome.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS High Sierra
 - Browser: Firefox Quantum
 - Version: 60.8.0esr (64-bit).

**Smartphone (please complete the following information):**
 - Device: iPhone 6
 - OS: iOS 12.3.1
 - Browsers: Chrome, Safari, Firefox
 - Version: latest versions of all above

<img width="377" alt="Kits_About_Line_2" src="https://user-images.githubusercontent.com/7387760/62314050-345ed100-b460-11e9-85dc-71e8a5647ab7.png">
<img width="383" alt="Kits_About_Line_1" src="https://user-images.githubusercontent.com/7387760/62314032-29a43c00-b460-11e9-9095-7b2acbde7af6.png">

**Comment by swwalker** [comment]
From DWS: update available on https://kits-dev.oit.duke.edu/toolkits2/about
@noahhh - what needs to be done to get this on kits-test?

**Comment by noahhh** [comment]
Sorry, this should be in test already

**Comment by joliet** [comment]
Tested.  This looks good to me.
