### ISSUE TITLE
Impersonate a User access does not stick when modifying combined kit

### ISSUE THREAD

**Issue by joliet** [DukeLearningInnovation/kits#427]
**Describe the bug**
On kits-test, I created the combined kit Foundations Elec & Comp Engineering.  David Smith (drsmith) is an instructor for one of the kits in the combined kit.  When I impersonate drsmith with Impersonate a User, and click on View/Edit kit for the combined kit, I go back to being me and am no longer acting as drsmith.

**To Reproduce**
1. Go to 'https://kits-test.oit.duke.edu/toolkits2
2. Create a combined kit
3. View the roster for one of your combined kits to find an instructor to impersonate
4. Use Impersonate a User to become the instructor
5. Click the kebab and choose View/Edit kit.
6. Impersonation is dropped and you are acting as your user (see account icon in upper left).

**Expected behavior**
The expectation is that once you impersonate a user, you are able to see what they see, but also act on their behalf through modifying kits with the same level of access they have.  This is important for testing as the team has admin access and this is the only way we can test non-admin roles access and functionality. The same will be true for support when we have people using kits this fall.

**Screenshots**
![Impersonate_User_Fails_on_Edit](https://user-images.githubusercontent.com/7387760/62729088-3d651a80-b9eb-11e9-8feb-fa3383aacf17.gif)

**Desktop (please complete the following information):**
 - OS: macOD High Sierra, Version: 10.13.6 (17G8030)
 - Browser Chrome
 - Version 76.0.3809.100 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by noahhh** [comment]
@joliet does this happen every time?  I am unable to reproduce this using chrome Version 76.0.3809.100 and OS 10.14.2

**Comment by joliet** [comment]
@noahhh Yes, I just tested again impersonating Michael R Gustafson (mrg) in the combined kit Foundations Elec & Comp Engineering.  I lose impersonation when I click Add App or Edit/View Roster.  Michael Gustafson is an instructor in all of the sections combined in the kit.  Should I create a new combined kit to test with?

**Comment by noahhh** [comment]
Thanks @joliet .  You being able to replicate it on any user while I can't helped me track it down.   Could you try it again when you have the time?  I pushed a small fix to test.
