### ISSUE TITLE
Sakai does not link to Toolkit in course with no instructor of record

### ISSUE THREAD

**Issue by chrislorch** [DukeLearningInnovation/kits#431]
Example: If the LAW 573 - 01 Kit doesn't have an instructor of record, is it unable to link to the LAW.573.01.F19 Sakai site? In this case, sakaiws@duke.edu created the Sakai site in lieu of an actual instructor. This occasionally happens when the registrar is slow to set a faculty account up, or an instructor is hired late to teach a course.

What the problem looks like: Staff assistant created LAW 573 with Batch create today, and the roster was not added to the course. It also did not have the "school: Law" property associated, which Sakai delegated access needs:
https://sakai.duke.edu/portal/site/LAW.573.01.F19

Add Participants shows the Manage Access & Roles page for "LAW 573 - 01: Advocacy And The Aca" though users added there don't populate to the course site.
https://toolkits.oit.duke.edu/current/edit_course/35042
The link to the Sakai site in Toolkits goes to http://sakai.duke.edu

**Comment by joliet** [comment]
This is probably fixed.  Watch prod for new issues.
