### ISSUE TITLE
Create trigger for change to default semester filter 

### ISSUE THREAD

**Issue by joliet** [DukeLearningInnovation/kits#433]
I am an instructor trying to access my kits for this semester but when I log in, I see kits from last semester.  This makes me feel confused and frustrated.

How might we (the Kits project team) create a trigger in Kits that automatically changes the default display semester once the last semester is over?

**Questions**

**Assumptions**
The trigger should happen after grades are due.
Users expect to see the most recent semester displayed when they log in.

**Hypotheses**

**Comment by outten45** [comment]
We are able to get Term Begin Date and Term Ending Date from a QAS service from SISS team given the STRM. It will be for UGRD which the team thought was good enough for setting the default in kits.

**Comment by joliet** [comment]
The term changed!
