### ISSUE TITLE
Search returns more than one result for some users

### ISSUE THREAD

**Issue by joliet** [DukeLearningInnovation/kits#437]
**Describe the bug**
When searching for some users to add to a Kit or impersonate, more than one result appears.

**To Reproduce**
1. Go to Account
2. Click Impersonate a User
3. Search for user felde001
4. See two results for this user (see screenshot)

**Expected behavior**
One result for each user is the expected behavior.

**Screenshots**
<img width="888" alt="Impersonate_Multiple_Results" src="https://user-images.githubusercontent.com/7387760/65053032-542b5500-d939-11e9-9ae4-88d4bccb5f4b.png">

**Desktop (please complete the following information):**
 - OS:  MacOS High Sierra 10.13.6
 - Browser: Firefox Quantum
 - Version: 60.9.0esr (64-bit)

**Additional context**

**Comment by noahhh** [comment]
@joliet the second result is a different account.  It is Trinity-SA so I'm thinking it's a service account.  Those started coming in when LI asked for those accounts so they could add citfac.  This is the expected data to be returned, so I don't think it's a bug.

If you'd like an enhancement, there are things we could do to let you filter them out, but as it stands now the data being returned is correct.  Let me know if you'd like to talk!

**Comment by swwalker** [comment]
not a bug.
