### ISSUE TITLE
Existing Sakai site is not visible on kit

### ISSUE THREAD

**Issue by joliet** [DukeLearningInnovation/kits#439]
**Describe the bug**
When an instructor creates a site in Sakai and then navigates to Kits, the site does not show on the relevant kit.

I can't remember if this is supposed to happen but I don't see how with our current model.  Seems like Sakai sites would have to be created through Kits in order for them to show up?

**To Reproduce**
1. Go to Sakai and use "Become user" to masquerade as an instructor
2. Click on Worksite Setup, Create New Site, course, Duke Default Template, Continue
3. Select a course in the list of instructors courses
4. Finish
5. Go to Kits
6. Use "Impersonate User" under the account menu to masquerade as the same instructor above
7. Sakai app does not show up on kit for site created above

**Expected behavior**
Ideally, Kits would be able to see Sakai sites related to Kits

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS High Sierra, 10.13.6
 - Browser: Firefox Quantum
 - Version: 60.9.0esr (64-bit)

**Additional context**
Related to issues:
Replace Sakai Worksite Setup with Kits - https://github.com/DukeLearningInnovation/kits/issues/374

**Comment by swwalker** [comment]
Kits only checks for an existing Sakai site if no card has been created in Kits.  Would need to do a check every time until there is a point in time when Sakai sites can only be created in Kits.

Possible nightly cron job?  Need further investigation.  Jolie and LIz to review.
