### ISSUE TITLE
Instructor created Notifications

### ISSUE THREAD

**Issue by profmikegreene** [DukeLearningInnovation/kits#44]
I am kit member trying to receive meaningful notifications because I'd like to reduce ambiguity and cognitive load, and increase sense of place in the kit which makes me feel better about my status in the kit.

How might we (the Kits project team) send useful notifications or updates to users about what's going on in a kit?

Idea may be to show some indication on site that something has changed.  
Both desktop and mobile.  
Maybe an indicator that something has changed, but details would require opening the tool

Maybe as a first pass allow for manual notifications to be created by the instructor in kits to communicate to the members when they login.

May impact/be impacted by #384 Kit menu re-work

**Questions**
- is this the same as #43?

**Assumptions**
- only doing manually created notifications this release

**Hypotheses**
- what do users want from notifications?

**Comment by curiousmustard** [comment]
Trying to get wireframe sketches done by Monday afternoon so we can discuss before Sprint Retro/Planning meeting. @swwalker Can you schedule a review meeting for this one, I think it will need more discussion outside of Sprint meeting.

**Comment by curiousmustard** [comment]
Initial pass at designs for Notifications (wireframe sketches). Uploading now so folks can review prior to meeting to discuss designs next week. Included student view and instructor views.
![44_Notifications_01](https://user-images.githubusercontent.com/18170417/56918665-9cca9a80-6a8c-11e9-8adc-82d9e3374934.JPG)
![44_Notifications_02](https://user-images.githubusercontent.com/18170417/56918666-9cca9a80-6a8c-11e9-889e-30bb0cff0748.JPG)
![44_Notifications_03](https://user-images.githubusercontent.com/18170417/56918667-9cca9a80-6a8c-11e9-8ba5-165292c5ab41.JPG)

**Comment by profmikegreene** [comment]
https://github.com/adlnet/xAPI-Spec/blob/master/xAPI-About.md#partone

Learning analytic framework that may be useful for our notifications structure.

**Comment by curiousmustard** [comment]
Got design mockups in Zeplin: https://app.zeplin.io/project/5b214027c1eddc64606dc242/dashboard?seid=5cdf01b11f5a851e11326f22

**Comment by curiousmustard** [comment]
@noahhh Looks like marking notifications as "unread" (after they're read) is not working.

**Comment by LASHirsh** [comment]
@noahhh Can you please change the button text from "Save" to "Send" so it's more apparent to instructors that pressing the button will automatically send the notification and that there is no way to edit before it sends? Thanks!

**Comment by noahhh** [comment]
@curiousmustard should be fixed in test now.  I notice a small issue that only happens in test and not locally, where the icon is not being replaced by the 'Has notification' icon when you mark a read item as unread.

@LASHirsh this has been changed in test

**Comment by LASHirsh** [comment]
Thanks @noahhh ! One more change to that button...make "Send" all caps (SEND) so it's consistent with the button styling elsewhere in the app.

**Comment by noahhh** [comment]
@LASHirsh Oops, sorry!  Just pushed that change to test, should show up in 10-15 mins.

**Comment by LASHirsh** [comment]
@noahhh , cannot remember whether this was already on your radar: the links for deleting notifications (as instructor) and hiding (as student) appear not to be working. pretty sure delete was yesterday?

**Comment by LASHirsh** [comment]
Conducted a quick user test of this feature. Notes from the session are posted in Box: [https://duke.box.com/s/0y39hxymdrxhldnfjwmyrhx0qtd5xd9z](https://duke.box.com/s/0y39hxymdrxhldnfjwmyrhx0qtd5xd9z)

This is only one person, so more testing would be helpful, but there is some good feedback there to explore for usability enhancements to this feature, and an indication that the kit concept can be confusing.

**Comment by profmikegreene** [comment]
Testing results for #44. Most functionality working properly.

**bugs**
* hide not working in FF
* delete not working in chrome

** possible enhancements**
* move notification bell to the left of the user profile
* add an attribution to show who made the notification. use display name or "me" if the user created it
* maybe instead of hide/mark as read invoking the read action moves the notification to a read notifications page accessible via link at the bottom of the notifications modal. delete still shows for users with that right though.
* sub divide the right section of the notification into 2 action buttons one for delete the other for mark as read

**Comment by curiousmustard** [comment]
@noahhh for the Mark Read/Unread, I had some thoughts to make this more user-friendly. Not sure if anyone else uses Trello, but I like how it works in their notifications. I also updated my [mockup in Zeplin](https://zpl.io/b645XLW) to show the interactive state.

- Can tooltip appear on rollover/hover? Right now there's a delay and is not very useful
- Added a highlight that would also appear around the radial box on rollover/hover

Attaching a crappy recording of the feature in Trello notifications
![Trello_MarkUnread](https://user-images.githubusercontent.com/18170417/59103917-28421180-88fe-11e9-84b5-5664807b677f.gif)



-

**Comment by noahhh** [comment]
@profmikegreene Thanks.  Since there are quite a few items in test, some have had a little issue working with one another (which is good to figure out!).  I have fixed hide and delete not working. Let me know if you still experience them

@curiousmustard Is the highlighted area what sets off the mark as read/unread, or still the little circle (when clicked)?

**Comment by curiousmustard** [comment]
@noahhh still circle when clicked. Highlight is just another visual cue that this is an interactive element

**Comment by noahhh** [comment]
@curiousmustard thanks.  Tooltip appears when the highlight does, or when hovering the circle?

**Comment by curiousmustard** [comment]
@noahhh When highlight does. Although if it makes more sense for highlighted area to set off mark read/unread let's do that. I think that's actually what happens on Trello.

**Comment by swwalker** [comment]
@profmikegreene, @joliet - the bugs found during testing have been addressed and moved to test.  please verify.

**Comment by swwalker** [comment]
@profmikegreene, @joliet - the bugs found during testing have been addressed and moved to test.  please verify.

**Comment by joliet** [comment]
Re-testing results for #44 - Instructor created notifications

**passed**
- Notify Kit in ARABIC 102 - 04D Sp19 and SPANISH asdfasdf Sp19
- Deleted a notification from Leadership Laboratory
- Marked all as read - worked and new badge disappeared 
- Checked notifications on mobile (create, read, delete)

**bugs**
end and cancel buttons inconsistently styled on mobile (see image)

**possible enhancements**
Size notification for content, not consistently sized for all notifications.

**Comment by noahhh** [comment]
@joliet I made some changes to the buttons, I think.  I don't have an iOS device, would you mind checking them and letting me know?
