### ISSUE TITLE
Manage Kits admins

### ISSUE THREAD

**Issue by joliet** [DukeLearningInnovation/kits#442]
I am a Kits admin and would like to add new admins to Kits but can't because that feature doesn't exist yet.  This makes me feel frustrated and delays my colleagues in doing their work.

How might we (the Kits project team) allow Kits admins to add new admins?

**Questions**
Would we manage this with Group Manager?
_Per meeting with IDMS on 12/5/19, this is an ideal candidate for using Group Manager to manage permissions, and, in fact, is the recommended course of action for audit purposes and the ability to setup rules to automatically manage access for individuals who move out of the Kits support role due to job status changes._

Would this be a feature under the Kits Admin area?
_Per meeting on 12/5/19, management of the Kits Administrator Group will be done within Group Manager.  There is no need to replicate the functionality in Kits, nor is there a current need to provide access to manage the group in Group Manager from Kits itself._  

Who would own the group in Group Manager?

**Assumptions**

**Hypotheses**

**Requirements/Acceptance Criteria**
Kits Support group includes:

- all members of the Learning Innovation Support group (duke:group-manager:roles:learning-innovation-support)
- all members of the OIT Service Desk group (duke:group-manager:roles:oit-service-desk)
- Kits developer support team members

When an individual is added to the Kits Support group in Group Manager, they have administrative access within the Kit application.

When an individual is removed from the Kits Support group in Group Manager, they no longer have administrative access within the Kits application.

**Comment by swwalker** [comment]
meeting with IDMS 1/16/20:

IDMS is scoping Policy Spaces which will allow apps to retrieve ismemberof attributes for all groups that fall within a certain Policy Space.  IDMS will create a Kits Policy Space.

Kit Service Owners will be created as a group; Jolie will be the owner
Kits Admins will be created as a group; updaters will be Kit Service Owners

**Comment by swwalker** [comment]
Jolie is working with IDMS to define the policy groups in Group Manager

While that is being defined, Liz and Noah will implement the change from an internal table of admins to a group manager reference to determine who has admin rights.

**Comment by ewendland23** [comment]
This is on Test and ready for people to look at.  It is using membership in duke:policies:kits:admin to decide who can be a Kits System Admin.

**Comment by joliet** [comment]
Admin access for me and others in LI seems to be working as expected.

Bugs found while testing:

Missing name for user jgt10 when added to Toolkits-test
https://github.com/DukeLearningInnovation/kits/issues/526

Name missing next to account icon in kits-test for jgt10
https://github.com/DukeLearningInnovation/kits/issues/527

Custom Link tool not working on kits-test
https://github.com/DukeLearningInnovation/kits/issues/528

**Comment by ewendland23** [comment]
Should this issue be moved to the "Test" category @joliet ?
