### ISSUE TITLE
Scope access for Delegates to kits within their specific school

### ISSUE THREAD

**Issue by joliet** [DukeLearningInnovation/kits#443]
I am academic technology support person in a school at the university and want to be able to provide support to all the faculty who teach in my school.  I can't do this, because there is no way for me to access only the courses offered through my school.  This makes me frustrated because I can't support faculty without intervention on their part (they add me to their kit).

How might we (the Kits project team), scope access for delegates so that they have access to kits only within their school (such as Law or Nursing)?

**Questions**

**Assumptions**

- What is currently referred to as delegates in Toolkits are departmental administrators.  A one-to-one relationship (person A is only a delegate for person B and no others) is not a current requirement.

**Hypotheses**

**Tasks**

- [x] Complete an inventory of the current delegate access in Toolkits.

**Requirements/Acceptance Criteria**
A departmental administrator has instructor-level access for course-related kits within their department.

- Can access all course-related kits within their department
- Can access all cross-listed kits in which a course within their department is one of the cross-listed courses
- Can add any app available to their department to a kit within their department
- Can manage the roster for all kits within their department
- Can combine kits within their department

A departmental administrator has  administrator-level access across kits for their department

- Kit search includes search of all kits across their department and excludes kits not within their department or belonging to them personally
- Can impersonate a user within their department
- Cannot impersonate a user that is not in their department

Departmental administrators are not included in the roster display for course-related kits within their department, unless they are enrolled in the course or have been manually added to the roster in Kits.

Departmental administrators can create user-defined kits.  

- If creating a user-defined kit on behalf of someone within their department, the departmental administrator must impersonate that faculty member and then create the kit.  The departmental administrator will not appear on the roster of that user-defined kit.
- If creating a user-defined kit for themselves, the departmental administrator creates the kit under their own credentials.

**DKU Access will be scoped by Term.  All other groups will be given access based on course naming conventions (e.g. courses that begin with Nursing).**

**Comment by joliet** [comment]
I followed up with Angie Jones in IDM.  I'm expecting to have links to the groups any day now.

**Comment by joliet** [comment]
I've been testing this with the Nursing staff since that's the only group who has populated their kits policy group with members.  I have been able to search and view kits associated with Nursing and only those kits.  I was also able to create a user-created kit with the Nursing category.  The issue of not actually being able to access the official course kit applies here, too.  It shows for a millisecond then disappears.

**Comment by joliet** [comment]
I have a ticket open with IDM to update some of these support groups.  As of today, that work is still in progress.
The issue of the course kit disappearing quickly is now resolved.

**Comment by swwalker** [comment]
Covered by other issues.  Closing
