### ISSUE TITLE
Upper case not maintained in title of user-created kit

### ISSUE THREAD

**Issue by joliet** [DukeLearningInnovation/kits#444]
**Describe the bug**
Upper case not maintained for title of user-created kit.

**To Reproduce**
1. Go to kits-test.oit.duke.edu
2. Click on the Create Kit button.
3. Select Create new kit option.
4. On New Custom Kit page select category, enter Kit ID, and enter Kit display name as "My New Kit"
5. Click the Save Kit button.
6. New kit shows display name as "My new kit".

**Expected behavior**
Capitalization should be maintained in the title as typed.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS High Sierra
 - Browser: Chrome
 - Version: Version 76.0.3809.132 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by joliet** [comment]
This issue is related to:
User-created kits - https://github.com/DukeLearningInnovation/kits/issues/126

**Comment by joliet** [comment]
This is still not working for me on kits-test.  Here are the steps I took and screenshot of the results:

1. Login to kits-test.oit.duke.edu
2. Click Create Kit FAB, then Create new kit
3. For Category, choose Co-Lab
4. For Kit ID type 2019-09
5. For Kit Display Name type "Web Design 101"
6. Click Save button
7. Kit display name is Web design 101
8. When I edit Kit, I can retype Web Design 101 and the case sticks on edit

<img width="336" alt="Display_Name_Case" src="https://user-images.githubusercontent.com/7387760/66669460-93da1980-ec25-11e9-9f48-6500321ab3d3.png">

**Comment by noahhh** [comment]
Hi @joliet ,

Sorry, this got overwritten with some other code we have in test.  I just made the change and pushed to test, it should be deployed in a few minutes.

**Comment by joliet** [comment]
Re-testing this on kits-test with Trinity Physics Research Group user-created kit this eve (6:05 pm) and received an error.  Unfortunately, the capitalization of the title didn't stick.  I ended up with Physics research group.  When I went to Edit Kit, that's when I received the error.

**Comment by joliet** [comment]
<img width="691" alt="https___kits-test_oit_duke_edu_toolkits2_adhoc_course_653_edit" src="https://user-images.githubusercontent.com/7387760/67246921-de317680-f42d-11e9-86b4-1b5237e7616b.png">

**Comment by swwalker** [comment]
I’ve reassigned this to Noah and moved it to In Progress in the Sprint.

**Comment by joliet** [comment]
@noahh I just re-tested this on kits-test and was successful in creating the user-created kit SANFORD 2019-11 Sanford Test Kit.  The capitalization in the title remained after the kit was created, but when I clicked on Edit Kit in the kabob menu, I still received the "We're sorry, something went wrong message".  I will create a new issue for that and assign it to Shellene.

**Comment by noahhh** [comment]
@joliet You can assign it to me, I see the issue and will fix it shortly.

**Comment by joliet** [comment]
Thanks @noahh!
