### ISSUE TITLE
Prompt existing Toolkits users to use Kits

### ISSUE THREAD

**Issue by joliet** [DukeLearningInnovation/kits#446]
I am an instructor logging into Toolkits to setup my tools.  I would use a newer version of the tool if I knew it existed.

How might we (the Kits project team) prompt users of Toolkits to try Kits when they login?

**Questions**
Will users be able to do everything they need to do in Kits?
Can we fully support new users both with documentation/help or issues that come up that require troubleshooting (staff resources)?
How will we onboard new users to Kits?
What new categories do we need to add for user-created Kits?

**Assumptions**
Faculty will like Kits better.
Students will go to Kits because faculty will tell them to access their course resources there.
The current model for My Kits layout with semester and user-created kits is ok for now?

**Hypotheses**

**Comment by joliet** [comment]
If we implement this as a message in Toolkits - an onscreen prompt - we'll want to know who/how many clicked on 'try kits' and how many said 'no thanks'.

**Comment by LASHirsh** [comment]
We are going to start with email communication to faculty who are using Toolkits. We will establish what metrics we want to be able to see about existing Toolkits users so we can keep track of people who switch over to Kits. Assigning back to Jolie.
