### ISSUE TITLE
Non-admin users should have access to Create Combined Kit option drop-down menu under My Kits

### ISSUE THREAD

**Issue by joliet** [DukeLearningInnovation/kits#447]
**Describe the bug**
When testing, and masquerading as a faculty member or staff outside of the team, I noticed that the drop-down for the My Kits menu is not available.

**To Reproduce**
1. Go to kits-test.oit.duke.edu
2. Click on user account then Impersonate a User
3. Search for and impersonate a faculty member or staff (outside of Kits and LI teams)
4. Notice on My Kits page that the drop-down for that menu item does not exist.

**Expected behavior**

**Screenshots**
<img width="870" alt="No_Drop_Down_My_Kits" src="https://user-images.githubusercontent.com/7387760/65727778-bfd29800-e086-11e9-9c17-36d1383c73f6.png">

**Desktop (please complete the following information):**
 - OS: macOS High Sierra 10.13.6
 - Browser: Chrome
 - Version: Version 76.0.3809.132 (Official Build) (64-bit)

**Comment by noahhh** [comment]
Hi Jolie,

I believe in our discussions, it was decided that the 'My Kits' dropdown (comes with the ability to add custom/combined) is only available when a user is an 'admin'.  I know that wasn't definitive but it was our solution for the time being.  Should this option be available to everyone?

**Comment by swwalker** [comment]
Noah,

Because Combine Kit is an option under the My Kits dropdown, non-admin users should have access to the menu.  They should not see the Create Kit option, however, as that is only available to Admins.
![image](https://user-images.githubusercontent.com/38253046/65890873-a32dad00-e371-11e9-8f57-d681d4b31a50.png)

**Comment by noahhh** [comment]
Will combined kits be available for students as well, then?

**Comment by joliet** [comment]
That's correct @noahhh.  I reported this issue for the kits-test environment where we have Combined Kits.  In response to Shellene's comment above, we'll need to discuss the timing of this.  If we are intending to promote kits prod to all users, we'll need to open up Create Kits as well.  I will see if there is an issue for that and make comments there regarding the category changes that we might make as part of releasing user-created kits to everyone.

**Comment by joliet** [comment]
Tested this on kits-test masquerading as faculty Denise Comer.  Resolved.
