### ISSUE TITLE
Add General Category(ies) for User-created Kits

### ISSUE THREAD

**Issue by joliet** [DukeLearningInnovation/kits#452]
I am staff and trying to create a Kit for my project but none of the categories are a good fit for naming the kit.  This makes me feel frustrated and worried my collaborators will not be able to find our project kit.

How might we (the Kits project team), identify a few general categories for user-created kits that would be a good fit for more generalized use cases (Duke, Project, etc)?

**Questions**
What categories would make sense based on existing use cases in Toolkits?
Requires user testing.

**Assumptions**
The current Toolkits options for project would work for Kits?

Kits will need to restrict categories based on the user's membership.  For example, only individuals associated with Pratt (faculty, staff, students) will be able to create a Kit with the Pratt category.  This may be accomplished via Grouper.

**Hypotheses**

**Comment by swwalker** [comment]
Should the schools remain as categories?
Is there a concern about people not affiliated with the school creating a kit with that school's category?

For Fall 2019 release, list should only include Duke and Project.

**Comment by joliet** [comment]
I met with two faculty yesterday who used Kits this semester.  Both said that Project and Team would be good general categories for user-created kits.

**Comment by swwalker** [comment]
@noahhh - see Jolie's comment for the categories to be used for the Fall 2019 release.

**Comment by noahhh** [comment]
@joliet  @swwalker Are these in addition to what we currently have, or to replace them?

**Comment by swwalker** [comment]
@noahhh - replace please.  For this release, it should only be the two options.

**Comment by joliet** [comment]
@noahhh I tested as staff member Tammy Toler (NetID tt164) and don't see Create Kit as an option.  I think we want to make Create Kit available to everyone, but non-admins only see the categories Project and Team until we get the group manager piece working to show the categories relevant to their groups.

**Comment by swwalker** [comment]
@noahh - based on the team discussion, I misspoke above.  Keep all categories, but Project and Team are the only options for non-admins.

**Comment by joliet** [comment]
Tested with NetIDs for both Tammy Toler and Monica Kutan in LI - neither are Kits admins.  Successfully created a user-created kit, added apps and participants.  Both Tammy and Monica could only see the Project and Team categories.  Tammy confirmed Project and Team made sense for general categories and could think of no other category names that she would expect to see there.
