### ISSUE TITLE
Kits that are part of a combined kit do not always display the merged Sakai site on the Kit.

### ISSUE THREAD

**Issue by swwalker** [DukeLearningInnovation/kits#456]
I am a student in a course which has been merged with another course.  I don’t see the merged Sakai site on my Course Card.

Course cards for merged kits need to check if the parent kit has resources and render them as well.

**Questions**

**Assumptions**

**Hypotheses**

**Comment by noahhh** [comment]
@joliet This is out in test.  It included some larger internal changes dealing with permissions, so please test a lot of regular kits situations as well (make sure you can't edit an app on a combined kit that isn't yours, can't view apps that you shouldn't be able to see, etc).

**Comment by joliet** [comment]
@noahhh - My testing results:

I went to toolkits-test and added myself as an instructor to the following courses: Biology 212L - 001 F19, Biology 212L -01L F19, Biology 212L -02L F19, and Biology 212L -03L F19.  I logged into kits-test and saw each as a course kit.  Then:

1. Clicked on Combine kits in FAB.
2. Selected all the sections above to combine.
3. Name the new combined kit General Microbiology.
4. Added the following apps: Sakai, Box, Warpwire, and Custom Link.

Issues:
1. I see all apps on the individual kits except Sakai.  I assume @ewendland23 is still working on that piece (Sakai sites for combined kits)
2. I cannot view/edit roster at the combined kit level, only the individual kit level (ones included with the combined kit).  I get the "The page you were looking for doesn't exist."  error.

**Comment by noahhh** [comment]
@joliet can you try the view/edit issue (#2) again and see if it works for you?

**Comment by joliet** [comment]
The issue of instructors not seeing the View/Edit roster is resolved, but my testing this morning with student roles revealed another issue.

1. Testing the Combined Kit COMBINED KIT Test combined.
2. Added the student citstud to the single roster for the combined kit.
3. Impersonated student bitstud.
4. Student bistud saw the combined kit card.
5. bistud could see App App and View Roster for the combined kit.
6. bistud added a Custom App to the combined kit.
7. Re-tested with student citstud.
8. When impersonating student citstud, they could only see the roster BRAINSOC 395 - 01 F19 Connections In Brain & Society for which they are a participant.  They did not see the combined kit.
9. Impersonated assistant citfac who could Add/Edit/Delete apps, Add/Edit/Remove participants, and send notifications.

Issue - the student bistud should see the card for the roster for which they are a participant - in this case, BRAINSOC 395 - 01 F19 Connections In Brain & Society.
Question - should we be able to have combined kits with only one roster?  Maybe yes if adding rosters later to the combined kit will automatically share the combined kit apps with those kits?

Let me know if I missed anything with my testing @noahhh .

**Comment by swwalker** [comment]
Closing this issue since the original problem has been resolved.  New issue has been created for what was found during testing.  See #473
