### ISSUE TITLE
Disallow membership editing in Toolkits for Combined Kits

### ISSUE THREAD

**Issue by swwalker** [DukeLearningInnovation/kits#457]
**Describe the bug**
When accessing a tookit in the old Tookits interface that has been combined with another tookit in Kits, tookits throws an error. 

**To Reproduce**
Reported by Liz Wendland.

**Expected behavior**
Redirect all membership editing in Tookits to the Kits url.

**Comment by joliet** [comment]
This is working but we need better feedback for the user on what is happening.  Marking for crux and including a screenshot of the existing message.

<img width="579" alt="Error_Edit_in_Kits" src="https://user-images.githubusercontent.com/7387760/72638641-d9e3ff00-3931-11ea-9f6f-d7d747a88578.png">

It would be better not to use the word 'error'.  This is working as designed.  We'll need to think about how to communicate this to users before putting this into production.

**Comment by curiousmustard** [comment]
If we could style the message like this message on Roster Edit Mode in Kits, then it wouldn't need a heading. The text and background can be bigger than it is on Kits.

<img width="480" alt="Screen Shot 2020-02-03 at 9 08 25 AM" src="https://user-images.githubusercontent.com/18170417/73659860-0f445880-4665-11ea-95e3-3ef2beca1685.png">

**Comment by curiousmustard** [comment]
Text for updated message. I'm working on styling and will post link to that here when finished!

Membership for this course is now being managed using Kits.
Go to Kits to edit membership for this course. [link this sentence]

Find out more about Kits. [links to About]

**Comment by curiousmustard** [comment]
Updated styling and message text is in Zeplin here: https://zpl.io/brXZZRr
