### ISSUE TITLE
learn.duke service owners view usage metrics for all apps in /apps because they want to know how to prioritize work and what is successful

### ISSUE THREAD

**Issue by profmikegreene** [DukeLearningInnovation/kits#46]

**Comment by JustinJohnsen** [comment]
By successful, we may mean having a large enough volume of use that it justifies associated enterprise-level costs for the app, that related support tickets are near or below target numbers, that integrations are firing correctly, and that the app is operating correctly across the majority (preferably all) user devices. For starters.

And we would want to include meaningful usage metrics as early as MVP1, I think.

**Comment by swwalker** [comment]
closed - incoporated in #211
