### ISSUE TITLE
Instructors do not have full access to Kit features for newly created kits - timing issue

### ISSUE THREAD

**Issue by swwalker** [DukeLearningInnovation/kits#461]
**Describe the bug**
When I used Act As to masquerade as Thavolia Glymph, I had some unexpected results.  She had two kits for courses she is teaching in Fall 2019 - CROSSLISTED COURSE F19 Civil War And Reconstruction (Lecture) and HISTORY 393 - 14 F19
Research Independent Study.  For both of these courses, she is listed as an instructor in DukeHub.  Courses had not yet been setup in Kits, but exist in DukeHub.

For the CROSSLISTED COURSE F19 Civil War And Reconstruction (Lecture) kit, Thavolia could only see Add App and View Crosslistings.  For the HISTORY 393 - 14 F19 Research Independent Study kit, she could only see Add App and could only add the Custom Link app (as if she had only student access?).  See screenshots.

**Expected behavior**
As an instructor, Thavolia Glymph should have full access to Kit management for both of these Kits.

**Screenshots**
![History_Crosslist_Instructor_Access](https://user-images.githubusercontent.com/7387760/67590738-d0c80500-f729-11e9-9bdd-b5e6df47a03a.png)
![History_IndStudy_Instructor_View](https://user-images.githubusercontent.com/7387760/67590749-d4f42280-f729-11e9-8533-5e849f5ec16b.png)

**Additional context**
Found during testing of #352

**Comment by joliet** [comment]
@ewendland23 and @noahhh .  What is a reasonable expectation for seeing the menus in terms of time?  I tested this on kits-test and still didn't see the menu after about 1 minute.  At that point, I refreshed and saw the menus but users won't do that.  I tested with faculty Susan Rodger (rodger) and Lindsay Saunders (lrs9).

**Comment by joliet** [comment]
@joliet Send Noah faculty to use for testing.

**Comment by joliet** [comment]
@noahhh - here are some netids that should work for testing this: jmoe, jb465, drubin.  Let me know if you need more.

**Comment by joliet** [comment]
Tested with three different faculty that I never test with.  They could all see their kits and related data under the kabob menu immediately after logging in.
