### ISSUE TITLE
Edit Kit results in error after creating user-created kit

### ISSUE THREAD

**Issue by joliet** [DukeLearningInnovation/kits#462]
**Describe the bug**
Clicking on Edit Kit after creating a user-created kit results in the error "We're sorry, something went wrong.  Need some assistance?  Send us a help request."

**To Reproduce**
1. Click on the Create Kit fab
2. Click Create new kit.
3. Select a category for the new kit.
4. Enter a kit id.
5. Enter a kit display name.
6. Click the Save Kit button.
7. Navigate to the new kit.
8. Click the kabob menu, then Edit Kit.
9. Error displays "We're sorry, something went wrong.  Need some assistance?  Send us a help request."

**Expected behavior**
The user should be taken back to the page where they can edit the kit display name.

**Screenshots**
![kits-test_oit_duke_edu_toolkits2_adhoc_course_763_edit](https://user-images.githubusercontent.com/7387760/67770583-07a16200-fa2d-11e9-8498-4339597a5cae.png)

**Desktop (please complete the following information):**
 - OS: macOS High Sierra, version 10.13.6 (17G8037)
 - Browser: Chrome
 - Version: Version 77.0.3865.120 (Official Build) (64-bit)

**Additional context**
Discovered while testing issue #444 - Upper case not maintained in display name of user-created kit.

**Comment by noahhh** [comment]
Hi @joliet ,

Please try the 'Edit kit' button now and let me know if you still get an error

**Comment by joliet** [comment]
Hi @noahhh .  I can access Edit Kit for the Sanford kit I created earlier and for a new user-created kit I just created - FUQUA 2019-11 Executive MBA Resources.  However, Combine kits disappeared as an option under the Create Kit FAB and under My Kits.  Should I create a new issue?

**Comment by noahhh** [comment]
@joliet Sorry, I had removed combined kits in preparation for merging the code in to production.  Is it okay if combined kits is 'disabled' in test for a day or two - until we merge the code in to production?

**Comment by joliet** [comment]
Yes, no problem to disable combined kits while we sort out getting code to production.  Thanks @noahhh !
