### ISSUE TITLE
Update API version being used by Kits to manage Wiki resources

### ISSUE THREAD

**Issue by swwalker** [DukeLearningInnovation/kits#468]
Kits is using a deprecated version of the API for Wiki site management.  API needs to be updated to a more current version.

**Comment by ewendland23** [comment]
Unfortunately not all of the API calls we make are available through the REST API.  So some got moved to the new REST style and the others just got cleaned up.  Ready to test on kits-test

**Comment by joliet** [comment]
Tested by creating, updating, and deleting wiki for a course kit.  All worked.
