### ISSUE TITLE
Change term translation from file to database implementation

### ISSUE THREAD

**Issue by swwalker** [DukeLearningInnovation/kits#469]
**Description**
The translation of Registrar terms for display in Kits is currently file-based.  Changing to a database implementation for ease of maintenance.

**Comment by ewendland23** [comment]
Don't forget about DKU Terms.  I am not sure what the authoritative sources is for them.

**Comment by ewendland23** [comment]
The terms were moved into a database but we never stopped using the file-based values.  This caused a bug as people started adding Summer 2020 courses since we did not have Term information for Summer 2020.  We need to convert Kits to stop using file-based values and use the SISS data in the database.

**Comment by ewendland23** [comment]
The list of Terms that we are getting from SISS does not include Winter Semester.  Does that mean we do not need to support Winter Semester classes?  We get information on Winter Semester courses in our SISS feed.  If we need Winter Semester then we need to amend what we get from SISS.  Currently working under the understanding that we WILL NOT have Winter Semester courses.

**Comment by ewendland23** [comment]
Since we have not heard from DKU, the DKU Term information must remain File-based and will only go through Fall 2020.  After that DKU courses will break.

**Comment by ewendland23** [comment]
Ok, this is ready to test.  Jolie can you try creating some summer courses from Kits and also create a Summer Sakai site and see if interacts properly with Kits?  I think we should create a new issue for the DKU and Winter issues so this can move into production ASAP

**Comment by joliet** [comment]
I tested by using Batch Create Sakai sites on toolkits-test to batch create course sites for Summer courses.  I created sites from Kits-test then created Sakai sites in sakai-test then checked kits-test.  All worked fine.
