### ISSUE TITLE
Student should not be able to access all kits in a combined kit

### ISSUE THREAD

**Issue by swwalker** [DukeLearningInnovation/kits#473]
**Describe the bug**
A student who is added to the roster of a course in a combined kit should only see and act on the individual kit they are a member of.

**To Reproduce**
1. Testing the Combined Kit COMBINED KIT Test combined.
2. Added the student citstud to the single roster for the combined kit.
3. Impersonated student bitstud.
4. Student bistud saw the combined kit card.
5. bistud could see App App and View Roster for the combined kit.
6. bistud added a Custom App to the combined kit.
7. Re-tested with student citstud.
8. When impersonating student citstud, they could only see the roster BRAINSOC 395 - 01 F19 Connections In Brain & Society for which they are a participant.  They did not see the combined kit.
9. Impersonated assistant citfac who could Add/Edit/Delete apps, Add/Edit/Remove participants, and send notifications.

**Expected behavior**
The student bistud should see the card for the roster for which they are a participant - in this case, BRAINSOC 395 - 01 F19 Connections In Brain & Society.

**Question**
Should we be able to have combined kits with only one roster?  Maybe yes if adding rosters later to the combined kit will automatically share the combined kit apps with those kits?

**Comment by noahhh** [comment]
Hi @joliet ,

I believe this issue is fixed in test.  Could you try with a new kit/combined kit?

Thanks,
Noah

**Comment by joliet** [comment]
Hey @noahhh ,

I added myself as an instructor to several compsci courses (lecture plus three sections) in toolkits-test.  After I combined the kits for said courses in kit-test, I couldn't access View/Edit Roster for the combined kit (Intro to Computer Science) - https://kits-test.oit.duke.edu/toolkits2/shared_kits/1133

Jolie

**Comment by joliet** [comment]
@noahhh   I was able to view all kits in the combined kit and access the rosters in each kit.  I was able to confirm that official students for each section only saw the kits for the lecture section and the lab section for which they were a participant.
