### ISSUE TITLE
Admins don't see the Team and Project categories for user-created kits

### ISSUE THREAD

**Issue by joliet** [DukeLearningInnovation/kits#475]
**Describe the bug**
Admins don't see the Team and Project categories for user-created kits

**To Reproduce**
1. Logged in as a Kits admin, go to kits-test.oit.duke.edu
2. Click on the Create Kit FAB
3. Choose option Create new kit.
4. Click the Category drop-down list.
5. The categories Team and Project are not in the list.

**Expected behavior**
Kits admins should see the Team and Project categories in the Category list for user-created kits.

**Desktop (please complete the following information):**
 - OS: macOS High Sierra 10.13.6 (17G9016)
 - Browser Chrome
 - Version Version 78.0.3904.108 (Official Build) (64-bit)

**Comment by noahhh** [comment]
@joliet Pushed a fix for this to test, should be available shortly

**Comment by joliet** [comment]
Heather and I tested this as Kits admins and we both see the Team and Project categories under Category for Create new kit.
