### ISSUE TITLE
Rosters combined in Sakai don't immediately appear as combined Kits 

### ISSUE THREAD

**Issue by swwalker** [DukeLearningInnovation/kits#478]
An instructor has set up a Sakai site with multiple rosters.  They have never clicked ‘Add Participants’. (This means there may be no ‘kit’ for these rosters yet)
Instructor logs into Kits.

- Kits sets up all the missing rosters for this instructor including the one(s) that were merged.
- Kits does not know at this point that some of the kits should be part of a Combined Kit because it hasn’t tried to add in the Sakai site.

Instructor sees all their semester Kits as individual (not-combined)

- In the background, Kits kicks off jobs to search for Sakai sites for all of the new kits
- Kits finds that one (or more) of these new kits have multi-roster Sakai sites.  
- Kits then knows to create a Combined Kit to hold the sub-kits.  

If Instructor comes back to the Dashboard (or reloads) they will now see the sub-kits gathered into the new Combined Kit
 
**Question**
Is it OK that initially the instructor can’t see the Combined Kit?
 
Why it’s hard to fix:
As you know, that initial page is very slow to load the first time an Instructor logs in.  It is looking up all their new Kits and creating them.  That is why we look for Sakai sites in a background process.  If we look at Sakai for every new Kit before we create it, that page will be even slower to load the first time.

Reported by Liz Wendland

Per Jolie on 12/11/19: Yes, I think it's ok that the instructor doesn't see the combined kit in Kits at first.  This is just a communication/training issue for users.  Let' go with what you have outlined in your message for now.

Team meeting on 12/16/19: This user experience will likely not be resolved as long as the merge roster feature is available to users in Sakai.

**Comment by ewendland23** [comment]
This issue is informational only.  Closing
