### ISSUE TITLE
Set default term to Spring 2020 in kits.duke.edu

### ISSUE THREAD

**Issue by joliet** [DukeLearningInnovation/kits#484]
**Describe the bug**
The current term display in kits.duke.edu is Fall 2019.  It should now be Spring 2020.

**To Reproduce**
1. Go to kits.duke.edu
2. See the Fall 2019 category at the top.

**Expected behavior**
Now that Fall 2019 semester has passed, the expected category display for course kits is Spring 2020.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by noahhh** [comment]
@joliet This is in production, but I did not move the term table code yet - this was done manually like it has been.  I would like to wait until we move the rest of the code to move the term table code.

If you do not see the default term change, you may have to clear cookies.
