### ISSUE TITLE
Term property does not set for Sakai site when setup through Kits

### ISSUE THREAD

**Issue by joliet** [DukeLearningInnovation/kits#485]
**Describe the bug**
On January 5, a faculty member reported that when he setup his Sakai course site through Kits, the term property was not set in the Sakai site.  The site is https://sakai.duke.edu/portal/site/ECE.564.01.Sp20

**To Reproduce**
1. Go to kits-test.oit.duke.edu
2. Navigate to an official course.
3. Under the kabob, click Add App.
4. Navigate to the Sakai app and click Add App to Kit.
5. After 30 minutes, go to sakai-test and check site.  Term is not set.
NOTE: this list of steps is what you might use to reproduce this problem, however, the issue does not seem to be able to be consistently re-produced and happens only on production environments.

**Expected behavior**
The term property for the Sakai site is set every time a Sakai site is created through Kits.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS High Sierra, 10.13.6 (17G9016)
 - Browser: Fireforx
 - Version: 68.2.0esr (64-bit)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ewendland23** [comment]
I would want to see this problem duplicated after we move the huge number of Sakai updates into production.  Those changes are for multiple roster and combined Kits. There is little point in looking into it until we move that code.  At that point I would need to see someone duplicate the problem?  The example site does not exhibit the issue currently.

**Comment by ewendland23** [comment]
I think this happens when creating a Sakai site from Kits (and maybe TK?) we don't kick off the Verify job.  I need to move it from create_sakai_site.rb to sakai.rb:create.

**Comment by ewendland23** [comment]
All new Sakai sites should now be verified for Term, etc, regardless of whether they were Batch created or set up from Kits directly.
