### ISSUE TITLE
As a member, I want to quickly access the tools used by my community so that I can get things done quickly.

### ISSUE THREAD

**Issue by profmikegreene** [DukeLearningInnovation/kits#49]

**Comment by profmikegreene** [comment]
This speaks to the need for clarity on what the LMS and other tools provide vs what learn.duke is. I'd  hope to see either learn.duke or another project, perhaps https://github.com/lrnwebcomponents have a technical definition for an 'announcement' and learn.duke be a framework for displaying announcements regardless of where they come from. 

Learn.duke should not build an announcement tool. Learn.duke is a framework for aggregating announcements from the LMS or emails to the course list with Announcement in the subject or wherever else faculty decide they want to send announcements from.

Does that sound right to everyone else? @DukeLearningInnovation/lts

**Comment by JustinJohnsen** [comment]
I would agree. To me, learn.duke is about collecting these different tools together in a seamless (as possible) interface, but not about providing any of the functions themselves.

**Comment by joliet** [comment]
Yes, that sounds right to me.  learn.duke has very few tools of its own.  It is an aggregator of content from other services, and displays that content in a unified, simple interface.

**Comment by swwalker** [comment]
Closed - user story incorporated in Feature Issue Access Course Community Apps #234.
