### ISSUE TITLE
Update references to DukeCapture to be Panopto instead

### ISSUE THREAD

**Issue by joliet** [DukeLearningInnovation/kits#491]
As an instructor I am trying to find and add Panopto to my kit but I am confused because I see an app called DukeCapture instead. This makes me feel confused because I don't know what the DukeCapture app is and don't know if that's just another name for Panopto.

How might we (the Kits project team)

**Questions**

**Assumptions**

**Hypotheses**

**Comment by joliet** [comment]
I finally received access to Contenta CMS to update this but I can't find any references to DukeCapture.  I see that someone updated the page on 3/4/20.  There is an with accessing this page in the App Store.  Creating a separate issue for that.

**Comment by curiousmustard** [comment]
David White from DWS made the changes with this note:

> updated https://kitscontent.cloud.duke.edu/node/64 
> changed title from Duke Capture to Panopto
> changed all occurrences of 'DukeCapture' to 'Panopto' (original body text provided below for reference)
> left link to DukeCapture User Guide as-is since it still links to DukeCapture User guide (this can be edited as needed).
> 
> If we need to make any further revisions, let me know.
> 
> correct link to details page in kits - https://kits-test.oit.duke.edu/toolkits2/app_store/Panopto/details
