### ISSUE TITLE
Kits automatically creates combined kits from multi-roster, non-crosslisted Sakai sites

### ISSUE THREAD

**Issue by joliet** [DukeLearningInnovation/kits#493]
I am an instructor accessing Kits after I created a Sakai site that includes roster for multiple sections of the course.  When I access Kits to setup more apps for my course, I see the Sakai site on the kits for all my sections.  I would rather see the sites in a combined kit, since I will use the Sakai site and all other tools for all rosters/sections for the course.

How might we (the Kits project team), identify Sakai sites that have multiple rosters that are just additional sections of the course and automatically create a combined kit for those rosters/courses?

This is part of the work for the feature Combined Kits.

**Questions**

**Assumptions**

**Hypotheses**

**Comment by joliet** [comment]
I created the ECE.110L9.01L.Sp20 (provider ID 068f9392-10d3-458e-8c80-a885d829120f) Sakai site on sakai-test around 2:25 today.  I created it with the following rosters - ECE.110L9.02L.Sp20, ECE.110L9.03L.Sp20, ECE.110L9.04L.Sp20, ECE.110L9.05L.Sp20, ECE.110L9.06L.Sp20, ECE.110L9.07L.Sp20, ECE.110L9.08L.Sp20, ECE.110L9.09L.Sp20, ECE.110L9.10L.Sp20, ECE.110L9.11L.Sp20, ECE.110L9.12L.Sp20, ECE.110L9.13L.Sp20, and ECE.110L9.14L.Sp20.  When I logged into kits-test, the individual kits showed for each lab section, but did not show the Sakai site on the card.  A combined kit was also not created for these courses.

**Comment by ewendland23** [comment]
Jolie - I don't know what to say - 068f9392-10d3-458e-8c80-a885d829120f seems to have disappeared too!  Do you think Longsight did a restore of older data and didn't tell us?  Its like everything you worked on 1/28 is gone.  Do you mind doing this again please?
