### ISSUE TITLE
Course kits in Law getting 'null' as kit id and a Sakai site name for the display name

### ISSUE THREAD

**Issue by joliet** [DukeLearningInnovation/kits#501]
**Describe the bug**
Several of Stephen Sachs's law course kits show 'null' instead of the law course name and in the kits display name show what looks like a Sakai site title.  See screenshot below

**To Reproduce**
1. Go to kits.duke.edu
2. Click on Impersonate a User
3. Search for Stephen Sachs and choose impersonate
4. See error for course kits under Spring 2020

**Expected behavior**
The kit titles should look like this format LAW 758 - 01 Sp20 and not show the text null. and for the kits display name, the kit should show the the class title such as Originalism & Its Discontents. Because the display name looks like a Sakai course site title, could this problem have happened during the batch creation of Sakai sites?

**Screenshots**
<img width="1368" alt="null_kits_title" src="https://user-images.githubusercontent.com/7387760/72478411-f7915700-37bf-11ea-8bfb-ce731a80efba.png">

**Desktop (please complete the following information):**
 - OS: macOS High Sierra 10.13.6 (17G10021)
 - Browser Chrome
 - VersionVersion 79.0.3945.117 (Official Build) (64-bit)

**Comment by swwalker** [comment]
Have implemented a fix moving forward that previous semester data will no longer be unavailable to Kits.  Believe this is the cause of this issue.  Revisit after deployment of Fall 2019 code.
