### ISSUE TITLE
Do not allow adhoc (or user defined) kits to be combined with course kits

### ISSUE THREAD

**Issue by joliet** [DukeLearningInnovation/kits#506]
**Describe the bug**
When a user tries to create a combined kit that includes both adhoc and course kits (course or non-sis course), kits throws an error and does not create a group for the kit (Liz please confirm).

**To Reproduce**
1. Go to kits-test.oit.duke.edu
2. Click on My Kits, Create Combined Kit
3. When prompted with kits to combine, select an adhoc kit and a course kit to combine
4. Click the Add Kits button
5. Click the Confirm Kits button
6. Name the combined kits
7. When the kit has been created, click any menu item under the kabob
8. See error "The page you were looking for doesn't exist. You may have mistyped the address or the page may have moved. Need some assistance? Send us a help request."

**Expected behavior**
The combined kit should be created and all actions that can be taken on the kit available - add app, view/edit roster, etc.

**Recommended solution**
Do not allow adhoc and course kits to be combined.  The role mismatch causes an error.

**Screenshots**
![combined_kit_adhoc_course](https://user-images.githubusercontent.com/7387760/74962257-8dcb2500-53dd-11ea-8379-7be68740bf55.png)

**Desktop (please complete the following information):**
 - OS: macOS High Sierra version 10.13.6 (17G10021)
 - Browser Chrome
 - Version Version 80.0.3987.116 (Official Build) (64-bit)

**Additional context**

**Comment by swwalker** [comment]
@noahhh - this is dependent on #507, so no need to work on this until that work is complete

**Comment by noahhh** [comment]
@joliet How would you want to display this?  Since there is no parent course, the decision has to be made on this page whether to create course vs non course merged kit

**Comment by joliet** [comment]
I've investigated this issue on kits-test and I cannot find an example where a user has both collaboration and course kits in the Combined Kit feature.

Note: support staff with scoped access do not have access to Combined Kit.  The workaround for these folks is to use Impersonate to create combined kits on behalf of their faculty.
