### ISSUE TITLE
Add framework to distinguish between course-related Kits and collaboration Kits

### ISSUE THREAD

**Issue by swwalker** [DukeLearningInnovation/kits#507]
There is a need to distinguish between course-related Kits and Kits used for collaboration purposes.

- User testing has revealed that the role names displayed for Kits (instructor, assistant, student, visitor), are not easily understood in the context of Kits that would be used for projects or teams. (see #453)

- There is an issue of a role conflict between ad-hoc toolkits and course-related kits causing an error when these different types of Kits are combined (see #506)

All Kits created from SIS-courses should be designated as course-related Kits.
A determination will need to be made at the time that a user-defined Kit is created to classify the Kit as a non-SIS course Kit or a collaboration kit.

**Questions**
Because a user-defined Kit will need to be classified at the time of creation, research and/or UX is needed to define how to make this determination.

**Assumptions**

**Hypotheses**

**Comment by joliet** [comment]
Feature narrative doc that proposes kit type selection during the Create New Kit workflow - https://docs.google.com/document/d/1mYoS2WC7mpZ_PFTaSJSMIIx_hhr94U3-yJngTq5ztCY/edit
