### ISSUE TITLE
Change DKU term translation from file to database implementation

### ISSUE THREAD

**Issue by swwalker** [DukeLearningInnovation/kits#508]
**Describe the bug**
The translation of DKU terms for display in Kits is currently file-based. Changing to a database implementation for ease of maintenance.

**Comment by swwalker** [comment]
Get some data for the upcoming year at a minimum - terms and term id and start/end dates

**Comment by ewendland23** [comment]
Richard got the following from John Campbell.  There is no option to pull this from a web service yet but we can use this file data in the meantime.


```
Term | Descr | Short Desc
-- | -- | --
2138 | 2013 Fall Term | 2013 Fall
2188 | 2018 Fall Term | 2018 Fall
2181 | 2018 Spring Term | 2018 Sprg
2185 | 2018 Summer Term | 2018 Sum
2198 | 2019 Fall Term | 2019 Fall
2191 | 2019 Spring Term | 2019 Sprg
2195 | 2019 Summer Term | 2019 Sum
2208 | 2020 Fall Term | 2020 Fall
2201 | 2020 Spring Term | 2020 Sprg
2205 | 2020 Summer Term | 2020 Sum
2218 | 2021 Fall Term | 2021 Fall
2211 | 2021 Spring Term | 2021 Sprg
2215 | 2021 Summer Term | 2021 Summe
2228 | 2022 Fall Term | 2022 Fall
2221 | 2022 Spring Term | 2022 Sprg
2225 | 2022 Summer Term | 2022 Sum
2238 | 2023 Fall Term | 2023 Fall
2231 | 2023 Spring Term | 2023 Sprg
2235 | 2023 Summer Term | 2023 Sum
0000 | Begin Term - Srvc Indicatr Use | Begin Term
9999 | End Term - Srvc Indicator Use | End Term

```

**Comment by ewendland23** [comment]
Added Terms for 2021, 2022 and 2023.  Still hard-coded since DKU does not provide a web service

**Comment by joliet** [comment]
Accessed the DKU SIS files and tested with several faculty.  The DKU terms showed up for them and I saw relevant course kits for each account.
