### ISSUE TITLE
Integrate Zoom with Kits

### ISSUE THREAD

**Issue by joliet** [DukeLearningInnovation/kits#510]
I am faculty member trying to teach my course online but Kits does not have a way for me web conference with my students.  This makes me feel frustrated and limited by my choices in how I will connect with my students remotely.

How might we (the Kits project team) integrate Zoom with Kits so that faculty can hold online discussions with their students when they teach online?

**Questions**
What are users expectations about how this functionality will work?

**Assumptions**
We can use LTI to add Zoom to Kits.

**Hypotheses**

**Comment by curiousmustard** [comment]
Logo and app icon files are in Zeplin: https://zpl.io/aXNLLoK
