### ISSUE TITLE
Provision MS Teams for all Spring 20 course kits

### ISSUE THREAD

**Issue by joliet** [DukeLearningInnovation/kits#512]
I am instructor trying to find an alternative to Zoom but I don't know what tool I can use instead.  This makes me feel frustrated as I can't interact with my course remotely with web conferencing software while teaching remotely.

How might we (the Kits project team), provision Teams for all spring 20 courses through Kits making it easy to switch faculty over to Teams for videoconferencing if Zoom is not an option?

**Questions**

**Assumptions**
MS Teams would be a viable option instead of Zoom.
We can provision Teams for all spring 20 kits with the appropriate rosters/access.

**Hypotheses**
Faculty will be able to quickly learn MS Teams and use it for teaching remotely with their students through synchronous online interactions.

**Acceptance Criteria**
- Faculty see a teams icon on every course kit in Kits for which they are an instructor.
- By clicking the Teams icon on their course kit, all expected students have access (from the faculty perspective)
- The name of the team matches the name of the course for which the team was created.  In this case, the team name is the same as the kit name (Kit ID + Kit Display Name).

**From conversation with Mary, Shawn, Liz and others in teams channel:**
With cross-listed courses, we have solved the multiple naming issue with a title for those of "Crosslisted Course" then "class title" (from DukeHub).  That would also be the name of the MS Team when it is created.  For the Teams that need multiple sections (lecture+01+02, etc) if the kit is created automatically without faculty login, the process should check to see if a Sakai site exists and create a combined kit.  That combined kit should contain all the rosters included in the Sakai site. If the Team is setup for the combined kit after that, all rosters should be added to the Team.  In the scenario where faculty are not using Sakai for the lecture+lab sections, I would recommend we setup a Team for the lecture section only (001 Sp20: Lecture).  That includes all students for all sections for which that faculty member is an instructor in DukeHub.  If they have been manually added to other sections, they can then add those sections in Kits so they show up in the Team.

**Comment by swwalker** [comment]
@joliet - is this still open, and, if so, how critical?

**Comment by joliet** [comment]
No longer relevant.
