### ISSUE TITLE
Broken link and DukeCapture reference in Panopto Details from App Store

### ISSUE THREAD

**Issue by swwalker** [DukeLearningInnovation/kits#515]
**Describe the bug**
Receive error message when accessing more details on Panopto from the App Store

**To Reproduce**
1. Go to 'https://kits.duke.edu/toolkits2/app_store'
2. Click on 'Panopto details'
3. See error

**Expected behavior**
Expect to see app details page for Panopto

**Screenshots**
![image](https://user-images.githubusercontent.com/38253046/77932109-13fb4680-727b-11ea-8583-699b0eb26ac6.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome

**Additional context**

**Comment by noahhh** [comment]
@swwalker  fixed

**Comment by swwalker** [comment]
@noahhh -

Still seeing a reference to DukeCapture.  Do you want me to open a separate ticket?

![image](https://user-images.githubusercontent.com/38253046/77935203-24152500-727f-11ea-8fcf-8768a298846f.png)

**Comment by noahhh** [comment]
@swwalker that reference is in the code we pull from what Will created.  It is a fix for Jolie/Jolies team

**Comment by joliet** [comment]
Updated.
