### ISSUE TITLE
Access to Admin Portal

### ISSUE THREAD

**Issue by swwalker** [DukeLearningInnovation/kits#517]
I am an administrator trying to access administrative features available to me in Kits but do not know how to access them which makes me feel frustrated.

How might we provide administrators with access to administrative tools?

Administrative tools will be accessible via the Admin  Portal #440.  To access the admin portal, authorized users can select the "Admin Console" option from either the site menu or their personal menu.  Option will be listed after the "Impersonate a User" option in both locations.

**Comment by joliet** [comment]
Tested a variety of accounts accessing this portal including those who have admin access and our test accounts that do not.  All navigation seems to work.
