### ISSUE TITLE
Administrator access to act on Kits

### ISSUE THREAD

**Issue by swwalker** [DukeLearningInnovation/kits#518]
I am an administrator trying to update a Kit but I can't because I am not a member of the Kit which makes me feel restricted in my ability to support Kits users.

Administrators have full rights to all Kits.  This access is resolved through work on group Admin access.  Steps to act on Kits by Admins are:

1. Go to the Kits Admin console - kits.duke.edu/admin
2. Click the icon Search all Kits (see #440)
3. Search for the kit you need to view or update
4. Search results are shown as kits cards (just like search in the Kits application UI)
5. When the Admin finds the kit they are looking they should be able to make any update to the kit as if they are the owner/instructor.

Related GitHub issues to this work: 
Access to Admin Portal - https://github.com/DukeLearningInnovation/kits/issues/517
Manage Kits Admins - https://github.com/DukeLearningInnovation/kits/issues/442

**Questions**

**Assumptions**

**Hypotheses**

**Comment by joliet** [comment]
Posted this on issue #101 but is probably more relevant here as it is related to the ability to act on a kit once accessed:
Tested https://kits-test.oit.duke.edu/toolkits2/admin/search by searching for 'compsci' (showed results), 'ece' (showed results) and known add ahoc titles such as 'kit' (showed results). Searching and showing results seems to be working fine but I can only access and update adhoc kits, including combined kits. Official course kits show for a millisecond then disappear.

When testing the access I have to user-created kits (adhoc), I'm able to update membership for one of Noah's kits (I am not a member of the kit) and able to edit the kit details, but I am not able to add apps.  I tested with kit TEAM 01 - Test Updated by Jolie.

**Comment by joliet** [comment]
@noahhh I re-tested this and found a few things.  Testing with kit COMPSCI 201 12D Sp20 I was unable to add new members.  Every member I tried I received the prompt that the user was already a member even though they were not (e.g. Michael Hudson, mvh13).  All the people I tried were LI folks who are admins.  I also tried a faculty member and grad student and had no problems.  There will be situations that a support person will need to add themselves to a kit, even if they have admin/scoped access.  I tried using impersonate a user to do this thinking that might be a workaround but got the same message.  I was able to remove members and change their roles.

I was able to add/edit/remove apps.  The only issue I found with that is that if I added or edited an app, it took me out of the Admin console view of the kit and back to my main kits page.  If someone were setting up a kit on a faculty's behalf this would be a little frustrating - having to navigate back to the Admin Console and search for the kit again.

I was unable to exit from the View as Student feature when accessing a kit in the Admin Console - at least not by clicking the exit option on the student view snack bar.  Refreshing the page worked.  I was able to successfully exit student view while impersonating as user.

**Comment by joliet** [comment]
@noahhh I re-tested and was able to add/remove/edit members that were admins (mostly LI folks).  I was also able to exit Student View while viewing a kit accessed through the Admin Console.

**Comment by joliet** [comment]
@noahhh  I re-tested with a few kits adding and editing apps.  Both Teams and Sakai did not take me back to the kit view in the admin console but to my kits page instead.  Everything seemed to work fine with adding/removing/editing normally in kits through impersonation or as myself.
