### ISSUE TITLE
Refresh Kits in Test Environment

### ISSUE THREAD

**Issue by swwalker** [DukeLearningInnovation/kits#522]
There are lots of old Kits used for testing that no longer reflect current Kits features/functionality.  It would be helpful to refresh the data in Test and remove the Test Grouper Groups.

**Comment by ewendland23** [comment]
There currently are 1637 Kits on Kits Test.  Are we OK with me deleting ALL OF THEM? :) I just want to check before I start getting crazy.

**Comment by swwalker** [comment]
@ewendland23 - received confirmation from @joliet to go ahead and delete all
