### ISSUE TITLE
Update confirmation message when adding new member to a kit

### ISSUE THREAD

**Issue by swwalker** [DukeLearningInnovation/kits#524]
**Describe the bug**
The confirmation message when adding a new user to a kit references "course" instead of "kit".  This is misleading for user-defined kits that are not associated with a course.

**Expected behavior**
Change confirmation message text to "The user has been added to this kit" (currently states "The user has been added to this course".

This change can be applied to any kit, regardless of whether course-related or not.  No need to display different messages based on the type of kit.

**Comment by joliet** [comment]
Tested with multiple kits.  Look good.
