### ISSUE TITLE
Bulk add users to a kit: User experience improvements

### ISSUE THREAD

**Issue by swwalker** [DukeLearningInnovation/kits#525]
**Describe the bug**
When bulk adding users to a kit by netID, submitting the list does not result in any confirmation message.  The user only sees a refresh of the bulk add screen with the information erased.  They must return to the view mode of the roster in order to see whether the users were added to the roster.

**To Reproduce**
1. Go to 'View/Edit Roster' for a Kit
2. Click on 'Edit Mode'
3. Click on 'or bulk add members'
4. Enter netIDs in text box, one netID per line and select a role
5. Click on 'Add'

**Expected behavior**
A confirmation message is displayed to the user indicating the roster has been updated.

**Desktop (please complete the following information):**
 - OS: Windows
 - Chrome

**Comment by swwalker** [comment]
@joliet, @curiousmustard - @noahhh will need information about wording for the confirmation message and whether or not to stay on the bulk edit page or return to the view roster page.

**Comment by joliet** [comment]
This looks good, Noah.  I like what you've done with the combo message of success/some failures and leaving the failed accounts in the text box.  I'm struggling a little with the "successful users" part of the message but I can't think of anything better.  Thanks for your work on this!
