### ISSUE TITLE
Missing name for user jgt10 when added to Toolkits-test

### ISSUE THREAD

**Issue by joliet** [DukeLearningInnovation/kits#526]
**Describe the bug**
When I add myself as an instructor to a course group in Toolkits, my name shows as missing and I do not have instructor access Kits.

**To Reproduce**
1. Search for a course toolkit in Toolkits-test (such as STA 210 001 Sp20
2. Click on Manage Access and Roles
3. Add jgt10 as an instructor to the toolkits
4. User shows name as Missing

**Expected behavior**
I expected to see my name in Toolkits under Manage Access & Roles, I expected to have instructor access in Kits.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS High Sierra (10.13.6)
 - Browser: Chrome
 - Version: 80.0.3987.163 (Official Build) (64-bit)

**Additional context**

**Comment by joliet** [comment]
Admin access for me and others in LI seems to be working as expected.

Bugs found while testing:

Missing name for user jgt10 when added to Toolkits-test https://github.com/DukeLearningInnovation/kits/issues/526

Name missing next to account icon in kits-test for jgt10
https://github.com/DukeLearningInnovation/kits/projects/74

Custom Link tool not working on kits-test
https://github.com/DukeLearningInnovation/kits/issues/528

**Comment by ewendland23** [comment]
This bug should be fixed.

**Comment by joliet** [comment]
Tested with several users including ones where we were seeing this issue with previously.  All worked as expected with names appearing in the Toolkit list of members.  Closing this one.
