### ISSUE TITLE
Name missing next to account icon in kits-test for jgt10

### ISSUE THREAD

**Issue by joliet** [DukeLearningInnovation/kits#527]
**Describe the bug**
When I am logged into Kits-test, I do not see my name next to the account icon as expected.

**To Reproduce**
1. Go to kits-test
2. Name next to account icon is missing

**Expected behavior**
I expected to see my name next to the account icon as I do in kits-prod.

**Screenshots**
My account on kits-test
<img width="170" alt="account_test" src="https://user-images.githubusercontent.com/7387760/80830145-7915c500-8bb6-11ea-8849-b0cec46ebdec.png">
My account on kits-prod
<img width="263" alt="account_prod" src="https://user-images.githubusercontent.com/7387760/80830173-8337c380-8bb6-11ea-88a0-ad9dd95631c6.png">

**Desktop (please complete the following information):**
 - OS: macOS High Sierra 10.13.6
 - Browser Chrome
 - Version 80.0.3987.163 (Official Build) (64-bit)

**Additional context**

**Comment by joliet** [comment]
Could this be related to https://github.com/DukeLearningInnovation/kits/issues/526?

**Comment by joliet** [comment]
When testing #442, and following up on an issue reported by Heather Valli, I discovered the name of the user is also not showing in the impersonating user snack bar:

<img width="873" alt="impersonating_snackbar_issue" src="https://user-images.githubusercontent.com/7387760/80971950-7a7c0300-8deb-11ea-9e73-c6fbcae1f6b0.png">

Adding here because I think these two are related.

**Comment by ewendland23** [comment]
This was related to the issue where the display name was missing.  Should be fixed now.

**Comment by joliet** [comment]
Tested with several users including the ones Liz identified as missing names in Toolkits/Kits before this fix.  Seems to be working now.  Closing this one.
