### ISSUE TITLE
Custom Link tool not working on kits-test

### ISSUE THREAD

**Issue by joliet** [DukeLearningInnovation/kits#528]
**Describe the bug**
I cannot add a custom link to any kit on kits-test.  I receive the error "The page you were looking for doesn't exist. You may have mistyped the address or the page may have moved.
Need some assistance? Send us a help request."

**To Reproduce**
1. Go to kit where you are the owner/instructor.
2. Click on Add App.
3. In the App Store navigate to the Custom Link app and click "Add App to Kit".
4. See error "The page you were looking for doesn't exist. You may have mistyped the address or the page may have moved. Need some assistance? Send us a help request."

**Expected behavior**
I expected to see the setup page for this app that shows the display name, link field and icon selection.

**Screenshots**
<img width="879" alt="custom_link_error" src="https://user-images.githubusercontent.com/7387760/80830933-e0804480-8bb7-11ea-8e51-e3ffe208b890.png">

**Desktop (please complete the following information):**
 - OS: macOS High Sierra 10.13.6
 - Browser: Chrome
 - Version: Version 80.0.3987.163 (Official Build) (64-bit)

**Additional context**

**Comment by ewendland23** [comment]
Jolie - i think i figured this one out if you want to test.

**Comment by joliet** [comment]
Add custom links to several kits.  This seems to be working now.
