### ISSUE TITLE
Batch Add Members to Sakai sites feature in Kits Admin Console

### ISSUE THREAD

**Issue by joliet** [DukeLearningInnovation/kits#531]
I am staff trying to batch add members to Sakai sites in Kits but that feature is not in Kits yet.  This makes me feel confused about which system to use and frustrated to use two different systems.

How might we (the Kits project team) the Kits project team move the Batch Add MemBers to Sakai Sites feature to Kits?

**Questions**

**Assumptions**

**Hypotheses**
We have already scoped out this feature and how it might work in Kits using a variation existing page designs for combined kits and bulk add users to kits.  Details are here:

https://docs.google.com/document/d/1SljyOvnSNbso0TBK1rtPNCVO5niGqknv68_TepDamEU/edit?usp=sharing

**Comment by joliet** [comment]
Updated feature narrative that includes just the 'Batch Add Members to Sakai Sites' feature as a standalone feature in the Admin Console - https://docs.google.com/document/d/1mW5LB-PhTOlfbq7i3DkmORyTIMFZFXuABsjTDLap-UU/edit#heading=h.40bfws86w621

 Some questions:
In the sites list, what should be displayed?  The current feature design in Toolkits only shows the values entered into the text box with site id/titles.
Do we need to keep the ‘Do not add users to Toolkits’ checkbox?

We need another lovely icon for this feature in the Admin Console.  Is that something you could work on soon @curiousmustard ?

**Comment by joliet** [comment]
For this issue, we need a new icon for the Kits Admin Console that represents this feature.  The work is scoped out in the feature narrative - https://docs.google.com/document/d/18uQHBn0p_TG8ittKnPZRtXwQNNz2nvORB66CPkkzfg0/edit (last page of doc).  Jen and I have discussed this one.

**Comment by curiousmustard** [comment]
@joliet I've got an icon for Batch Add Members to Sakai, attaching a mockup. I'll also add this to the Zeplin project.
![#440 - Admin Area](https://user-images.githubusercontent.com/18170417/109859427-f40e9880-7c2a-11eb-9004-8bd6ce279cf2.png)

**Comment by joliet** [comment]
@noahhh - Results of testing for this feature in the Admin Console so far:

Testing for adding members to Sakai course sites worked.  I tested with several existing Sakai sites.
Testing with project sites was inconsistent.  In some sites it worked and others it did not.  I need to do more testing on this part to figure out what might be happening there.  Here are the sites I tested with:

Noah Test d0a80d24-f4ba-4776-931d-f70dbded69fb - Heather Valli was not added with the role of Maintainer (Owner)
Kits Category Test - f0e00732-8e51-4599-9a41-65d71c64d53a - Heather Valli was not added with the role of Maintainer (Owner)
Noah Role Test - 9d114f21-1b4d-4973-b6dd-15b388fcf1ee - Heather Valli was not added with the role of Maintainer (Owner)
Kits Site Info Add Test - 579f3836-0e7f-4736-9cbf-5cf4b3e63842 - Heather Valli was not added with the role of Maintainer (Owner)
Kits Test - 5dfaccec-5d1e-4ffd-862a-accf58b56fa8 - Heather Valli was not added with the role of Maintainer (Owner)

Kits Role Test for PS - 789c0be2-4e85-4688-bb1d-62cbcd55dc7f - - Heather Valli was added with the role of Access (Viewer)

Jolie's New Project Site - cc86ec1d-35dd-43df-b9d3-de232f661dc6

In this specific scenario (adding to Kits Role Test for PS), I saw the roles of Instructor, Assistant, and Student on the Add Member page, even though the site is a project site.

I logged into Sakai-test to check the site type and it did not have an associated kit.  The activity logs showed that it created the kit when I clicked on Add Participants in Sakai.

Related to this, what if instead of the text on the first page "Be sure all sites are the same TYPE. You will be picking a single role that needs to be available on all of these sites" we required the user to select Project or Course site type instead?  That way, even if there isn't a kit created yet, the correct roles will display on the add member page.

I found a few other small things with the UI and defaults:

<img width="1348" alt="Batch_Add_Members_Edit" src="https://user-images.githubusercontent.com/7387760/116914609-ef5d6500-ac18-11eb-9ba7-c010faa091dc.png">

For the defaults change, when adding a new member to a Sakai course site the default role should be Instructor or Assistant instead of Visitor.  I've asked for feedback on this from someone who uses this feature regularly and will let you know as soon as I hear from her.

I will follow up once I've done a little more testing on project sites.

**Comment by joliet** [comment]
Follow up - the default role when adding members to Sakai course sites should be 'Assistant'.  That is the role most commonly selected.
<img width="912" alt="Batch_Add_Default_Role" src="https://user-images.githubusercontent.com/7387760/116917474-b6bf8a80-ac1c-11eb-95b0-aef58ae65ed5.png">

**Comment by joliet** [comment]
One more thing I noticed in testing - the email I receive has the subject of Batch Create Sites.  We'll need to update that to be more specific.  I will find an old one and post it here.

**Comment by joliet** [comment]
The confirmation email from Toolkits for batch adding users to Sakai sites was formatted like this:

<img width="742" alt="Batch_Add_Members_Confirmation_Email" src="https://user-images.githubusercontent.com/7387760/117350044-1797ce80-ae7a-11eb-8d7d-ecbf8d6755f2.png">

**Comment by noahhh** [comment]
What if we put the subject as something that could fit both?  "Toolkits Batch Sakai Process Status" or something?

**Comment by joliet** [comment]
Yes, that sounds great!   I like that wording "Kits Batch Sakai Process Status" for the subject.

**Comment by joliet** [comment]
Hi @noahhh .  I just re-tested this and only found one small thing: on the confirmation page (Step 3) the Remove options are not aligned.  Not a blocker by any means but if we could fix that small thing, this is ready for production.  Everything else looks good!

<img width="988" alt="Remove_Column_Align_Step_3_Batch_Add_Users" src="https://user-images.githubusercontent.com/7387760/119023265-9eb36f00-b96f-11eb-9405-153af50254a2.png">

**Comment by noahhh** [comment]
@joliet pushed a change for this, let me know what you think when you have time to take a look.

**Comment by joliet** [comment]
This looks good @noahhh .  Quick question: what happens in Step 2 when adding the member if the process can't find the site from the ID entered in Step 1?  Maybe we need a check in Step 1 after Continue is clicked and an error shown if there's an issue with one the site ids?  This could be similar to the message on Batch Add Users where we should what fails.  Something like - "site id" not found.  Does this make sense?

**Comment by noahhh** [comment]
@joliet from what I remember, we do not check when they are entered because we also create new kits if a site ID is entered that we do not have.  Since it works this way, I'm not sure if we could check the legitimacy of a site ID as it may be one that doesn't exist in Kits yet.

**Comment by joliet** [comment]
Thanks @noahhh  I'm not seeing this feature on test.  Let's stick with the strategy of moving this to prod, even without checking in step one.  Are you still ok with that?

**Comment by noahhh** [comment]
@joliet this has been moved to production (And I put it back on test, sorry about that)

**Comment by joliet** [comment]
T
