### ISSUE TITLE
/about page not secure

### ISSUE THREAD

**Issue by swwalker** [DukeLearningInnovation/kits#533]
**Screenshots**
![Screen Shot 2020-05-08 at 5 02 30 PM](https://user-images.githubusercontent.com/38253046/81592004-4c6a6600-938b-11ea-9024-e1ab17849068.png)

Appears to be related to the images on the page

**Comment by swwalker** [comment]
Jillian indicated that DWS has corrected this in dev.  @noahhh - what does @joliet need to do to confirm?

**Comment by noahhh** [comment]
@swwalker @joliet This is out in test now.  You should be able to visit /about and verify it no longer says 'not secure'

**Comment by joliet** [comment]
Tested and not showing at Not Secure on kits-test.  Can be moved to prod.

**Comment by noahhh** [comment]
@joliet  This has been moved to prod
