### ISSUE TITLE
Create a better empty state message for new users of Kits

### ISSUE THREAD

**Issue by joliet** [DukeLearningInnovation/kits#544]
I am staff member new to Duke and trying to use Kits for the first time.  The message I see when I go to Kits "The page you were looking for doesn't exist. You may have mistyped the address or the page may have moved. Need some assistance? Send us a help request" is confusing and makes me think there is a problem with Kits.

How might we (the Kits project team) create a better empty state message for first-time users of Kits (those who are in no existing grouper groups).

**Questions**

**Assumptions**

**Hypotheses**
New users will think there is a problem with Kits if they see this message.  A better message would give them feedback on the state and what to do next.
Existing message:
<img width="865" alt="Kits_New_User_Message_Error" src="https://user-images.githubusercontent.com/7387760/82687609-822e0b00-9c25-11ea-84d2-1ff46af91d5b.png">

**Comment by joliet** [comment]
Resolving this before May 1 or August 1 (just prior to a new semester), would be good timelines to target getting this into production.

**Comment by joliet** [comment]
Here's a design @curiousmustard  and I talked about today - https://emptystat.es/s/nothing-in-your-adobe-creative-cloud-library/. 

We discussed the goals of giving better feedback to users who are new Kits, giving some guidance on how/why to use Kits, and a call to action for creating a new kit.  We discussed whether or not the call to action would need to be a functional button for creating a new kit or if the design could point users to the existing Create kit FAB Create kit.  I offered to do some usability testing before we finalize the design to determine how function the CTA button/design should be.

**Comment by curiousmustard** [comment]
@joliet I wrote up some copy options and have a sketch in [this Google doc](https://docs.google.com/document/d/1TkHzvqzuVWAmHnOaCEPs0AbynCH81glZY1pG-dLZMSQ/edit?usp=sharing) to give you an idea of layout for the page. I've also mocked up in [Figma](https://www.figma.com/file/LdIhgBac2syUvmmbMaNQkH/Empty-States), but don't have imagery. I'd like to nail down the copy first then I'll look for imagery (probably iconography).

**Comment by joliet** [comment]
@curiousmustard I commented on the doc regarding the copy.  This looks good!  I'm happy to chat about this anytime if that helps.

**Comment by curiousmustard** [comment]
@joliet I've got a mockup for this issue, with imagery, ready for review. 
https://www.figma.com/file/LdIhgBac2syUvmmbMaNQkH/Empty-States?node-id=0%3A2265
![#544 - Empty State for New Users](https://user-images.githubusercontent.com/18170417/115061337-1268e480-9eb7-11eb-8e01-817e80485266.png)

**Comment by joliet** [comment]
This looks great, Jen!  Confirming with @noahhh that we can make the CTA buttons go to the relevant actions.

**Comment by joliet** [comment]
Just found a few small text changes @curiousmustard .  When we refer to individual kits, we use a lower-case k and when we refer to the application as a whole, we use an upper-case K.  I wonder if the first-time user who doesn't really know anything about Kits will get that, though.  Thoughts?

**Comment by joliet** [comment]
@noahhh For this, only the items that look like buttons need to be clickable.  User testing confirmed this.

Something that came up for a new user of Kits - the current semester heading displays and this could be a little confusing.  Is this something you were already thinking about with this change or did you consider that out of scope?  Out of scope is totally fine but it could make sense to address that with this change.

**Comment by joliet** [comment]
Looks good!  All buttons worked as expected.
