### ISSUE TITLE
Extend app integration for Box to include private folder set up and co-owner selection

### ISSUE THREAD

**Issue by joliet** [DukeLearningInnovation/kits#547]
I am a staff member OIT Collaborative Services who needs a better way to support Duke Health staff when using Box.  The current process makes it too easy for data to be lost.  This makes me feel unable to effectively support people at Duke who use Box.

How might we (the Kits project team), make it easier for OIT to support Box users?  Current challenges include orphaned Box folders/data, difficulty tracking down Box data ownership, and accidental data loss.

**Questions**
What are the use cases for Box?
What are the most common support issues with Box?

**Assumptions**
Using Kits to set up Box folders for Duke Health, and possible changes to how Kits current sets up Box will reduce the number of problems the Duke community has using Box (see current challenges above).

**Hypotheses**
Current issue title is the hypothesis.  Dorothy Coletta is working with Jolie on discovery to refine the problem(s) to be solved.

**Comment by joliet** [comment]
I have a mockup for this.  I would like to discuss this in our team meeting on 2/8 before moving forward.

**Comment by joliet** [comment]
I shared the draft mockup with Matt R.  Waiting on his feedback.

**Comment by joliet** [comment]
@ewendland23 I have an update on this.  I met with Matt R last week and we finalized the app workflow, selections and language for sensitive data and the role drop down order for custom role mapping.

When the sensitive data option is selected, two things must be set on the folder: 

Invitation restrictions: Only folder owners and co-owners can send collaborative invites
Shared Link Access: Only collaborated can access this folder via shared links, For: Files and Folders

Options for remapping Student role in course kits is as follows:

Viewer (default)
Uploader
Viewer Uploader
Editor
Previewer Uploader
Previewer

Options for remapping the Assistant role in course kits is as follows:

Editor (default)
Viewer Uploader
Viewer
Uploader
Preview Uploader
Previewer

Options for remapping the Viewer role in collaboration kits:

Viewer (default)
Uploader
Viewer Uploader
Previewer
Previewer Uploader
Editor

Options for remapping the Editor role in collaboration kits:

Editor (default)
Viewer Uploader
Viewer
Uploader
Previewer Uploader
Previewer

Let me know if you have questions.  I'm reposting a link to the Figma file in Teams.

**Comment by ewendland23** [comment]
![Screen Shot 2022-03-30 at 11 01 27 AM](https://user-images.githubusercontent.com/4522248/160866844-7a6117b5-e3a6-4946-97b7-be9fe95ff384.png)
![Screen Shot 2022-03-30 at 11 01 47 AM](https://user-images.githubusercontent.com/4522248/160866872-0d66a4dd-0ebe-490a-9102-51cab943cec1.png)

**Comment by ewendland23** [comment]
For Sensitive folders we will be setting:
folder_attrs[:can_non_owners_invite] = false
folder_attrs[:shared_link] = { access: 'collaborators' }

**Comment by joliet** [comment]
Hi @ewendland23 .  I set up a Sensitive Data Box folder in one of my kits and it did not get the setting folder_attrs[:shared_link] = { access: 'collaborators' }

Details:
Kits-test
kit: TEAM 2021-10-30: Kits Role Test again
kit id: 2639

The 'folder_attrs[:can_non_owners_invite] = false' setting and the role mappings worked great.

**Comment by ewendland23** [comment]
After doing some investigating, I think it is impossible to check that box from the API?  See this issue:
 
https://support.box.com/hc/en-us/community/posts/360049153234-Restrict-Shared-Link-Access-for-Folder-Programmatically-
 
I then tested if I could invite someone who wasn’t a Collaborator and I found I could NOT.  So, I think the behavior is correct, but that box isn’t checked.

**Comment by mattroyal** [comment]
I've raised this shortcoming with Box, but in the meantime, if we can't control folder settings via the API, I wonder how useful the Kits sensitive data folder feature would really be.  (If the folder is no different from any other folder in its functionality, I think it could wind up being misleading to the user.)

**Comment by ewendland23** [comment]
Matt,

Did you find that the behavior wasn’t there either?  I tried inviting a non-collaborator and they could not join… at least as far as I understand this.  I am thinking Box might have overloaded the concept of ‘shared links’?

Liz

From: mattroyal ***@***.***>
Date: Wednesday, April 6, 2022 at 12:36 PM
To: DukeLearningInnovation/kits ***@***.***>
Cc: Liz Wendland ***@***.***>, Mention ***@***.***>
Subject: Re: [DukeLearningInnovation/kits] Extend app integration for Box to include private folder set up and co-owner selection (#547)

I've raised this shortcoming with Box, but in the meantime, if we can't control folder settings via the API, I wonder how useful the Kits sensitive data folder feature would really be. (If the folder is no different from any other folder in its functionality, I think it could wind up being misleading to the user.)

**Comment by mattroyal** [comment]
My colleagues at other universities confirm that they have tried this and
ran into the same thing: the function we're trying to use was not supported
by the API.

**Comment by ewendland23** [comment]
@mattroyal  and @joliet ,

What do we do about this issue?  Do you want to move ahead with what we can do?  Do you want me to back out my changes and abandon this idea?

Liz

**Comment by joliet** [comment]
@mattroyal and @ewendland23 

I defer to Matt here on the final decision.  I have tested sharing a link to the folder with non-collaborators and that doesn't work even though the check box for "Only collaborators can access this folder via shared links." is not selected.  If shared links are not accessible to non-collaborators without this check box, what does checking the box change?  Hoping Matt can shed some light on that.

Even if we can't check that box with the integration, there's still benefit in encouraging folks to use Kits to set up folders for sensitive data: persistent Kits folder ownership; tracking sensitive data folders setup through Kits (not comprehensive but better than nothing); guidance in the UI on what constitutes sensitive data; and setting the first option for "only owners can....".    

Maybe rather than scrapping the integration, we add text in the UI for recommending owners apply the second setting on their own with a link to Box documentation on how?  @mattroyal what do you think?

**Comment by joliet** [comment]
Waiting on response from Matt when he returns from vacation on 4/19.
