### ISSUE TITLE
DKU users cannot create or update kits

### ISSUE THREAD

**Issue by joliet** [DukeLearningInnovation/kits#548]
**Describe the bug**
When DKU users try to update Sakai sites via Add Participants, they are unable to do this.  Toolkits never finishes creating a group for them to access and add a new participant.

**To Reproduce**
This is difficult to reproduce.  I have confirmed this issue with Liz with specific reported cases from DKU and with her accessing the logs to confirm the access problem.

**Expected behavior**
DKU users should be able to create a new kit for a new site in Sakai through clicking Add Participants to add users to the site.  They should also be able to access existing groups for updating Sakai sites and clicking Add Participants in Sakai.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ewendland23** [comment]
The underlying cause of this issue is we only allow people with the affiliations student/staff/faculty to create Kits.  If LI wants to change this we can.  They just need to tell us how to decide who can create a Kit.

**Comment by profmikegreene** [comment]
We have grouper groups setup that allow us to consume DKU faculty and manually add anyone else in order let them create Sakai sites. Would that mechanism work here? Home >Root >Duke University> Learning Innovation has the groups Sakai is using.

Thanks!

Michael Greene, Associate Director
Learning Technology Services and Strategy
Duke Learning Innovation<https://learninginnovation.duke.edu/>  - Subscribe to our newsletter<https://duke.us11.list-manage.com/subscribe?u=8e4fc10aff65b7e7963513f17&id=c768abf8fe>
@profmikegreene<https://twitter.com/profmikegreene>


________________________________

**Comment by joliet** [comment]
Thanks for posting that, Michael.  So, yes, we have the same issue with Sakai and this group in Grouper helps us define the DKU folks and allows them to create Sakai sites.  There is a tradeoff in that case, though.  Support staff are unable to "become user" to troubleshoot issues.  We have a different design here so I don't think this would be an issue for us.

**Comment by ewendland23** [comment]
Kirk created a Policy group that includes the LI group.

duke:policies:kits:learning-technology-faculty

Our service account (toolkitsgrouper) has access to this group now.

**Comment by ewendland23** [comment]
@profmikegreene  and @joliet  - can you give me an example of a DKU faculty member that is in that LI group?  All of the ones I see are also Duke Faculty.  I randomly selected a DKU course instructor mk390 - Moon Joon Kim and can't find him in your group.

**Comment by joliet** [comment]
Here's one @ewendland23 - bx23

**Comment by profmikegreene** [comment]
I thought the DKU faculty were in a separate group consumed by this group. I don't know if that affects how you're searching for them. I see 2 groups with direct membership but I says that I cannot view them, so I don't know if they are it or not.

Thanks!

Michael Greene, Associate Director
Learning Technology Services and Strategy
Duke Learning Innovation<https://learninginnovation.duke.edu/>  - Subscribe to our newsletter<https://duke.us11.list-manage.com/subscribe?u=8e4fc10aff65b7e7963513f17&id=c768abf8fe>
@profmikegreene<https://twitter.com/profmikegreene>


________________________________

**Comment by ewendland23** [comment]
People who are members of the new policy group kits:learning-technology-faculty are automatically give permission to create Kits, no matter what affiliation they have.

**Comment by joliet** [comment]
Ok, I have tested with a few DKU faculty and DKU staff.  I was able to successfully create a user-created kit in Kits and able to create a toolkit for a Sakai site (coming from Sakai) with DKU faculty.  I added/updated/removed. However, the two DKU staff I tested with jw644 (Jiaxin Wu) and fl109 (Fan (Luisa) Li) were not able to create a user-created kit in Kits.  Thoughts on that @ewendland23 ?

**Comment by ewendland23** [comment]
Hi Jolie,

The users with DKU access are defined by **you all** in Learning Innovations.  The policy group is defined to look at your group:
isMemberOf: urn:mace:duke.edu:groups:dli:learning-technology-staff

I can’t see members of that nor how it is set up.  I think @Milesofmikegreene should know?

If you need other groups included in this policy group, please let Kirk Rouser know.  Adding them to the policy group kits:learning-technology-faculty will automatically give them the ability to create Kits.

**Comment by joliet** [comment]
Thanks, Liz!  Will investigate.  It may be that only DKU faculty are in my group.  I will work with LI and Kirk to get that resolved.

**Comment by joliet** [comment]
I have a ticket in to IDM about DKU access.  I can't seem to add the staff DKU group to the policy group.

**Comment by swwalker** [comment]
@ewendland23 - give dku staff group access to create and manage kits
