### ISSUE TITLE
Remove Admin page in Toolkits

### ISSUE THREAD

**Issue by joliet** [DukeLearningInnovation/kits#560]
I am a member of the OIT Service Desk trying to update who should have admin access to OIT Services and notice that there is a page in Toolkits that shows outdated membership for admin access.  This is confusing to me because we are now using Group Manager to gain admin access to Kits.

How might we (the Kits project team) make it clear to Duke IT support staff who support Toolkits/Kits where/how admin access in Toolkits/Kits is managed and viewable?

**Questions**
Should we change the admin page to show a message that communicates the new process we are using through Group Manager for access and who to contact (Jolie or kits@duke.edu) for more information?

**Assumptions**
Everyone who needs admin access to Toolkits/Kits is now is the right Group Manager group and has access.

**Hypotheses**

**Comment by joliet** [comment]
I'm still seeing the Admin page on toolkits-test, @ewendland23 .  Would it help if I wrote a message to display on the page that points people to our new admin process with Group Manager that you could put on the page?  Something like:

"Toolkits/Kits administrative access for support groups is now being handled through Group Manager.  Contact the Kits Team at kits@duke.edu to learn more about gaining administrative access to Kits."

**Comment by ewendland23** [comment]
Hey Jolie,  I haven't done this yet.  Not sure how it got marked for 'Test'.  I will work on it next.

**Comment by joliet** [comment]
This has been tested and is ready to move to Toolkits prod.
