### ISSUE TITLE
Combined kit setup from Sakai should check for crosslists to avoid duplicate kits in the combined kit

### ISSUE THREAD

**Issue by joliet** [DukeLearningInnovation/kits#562]
**Describe the bug**
When an instructor with a Sakai course site that includes cross-listed rosters tried to Add Participants in Sakai, Kits is adding the cross-listed course kits twice.

**To Reproduce**
1. Set up a Sakai site for a course that has cross-listed rosters
2. All all cross-listed rosters to the site
3. Click Add Participants in the Sakai
4. Kits adds the cross-listed rosters twice to the combined kit that is created

**Expected behavior**
Only one kit for each cross-listed course should be shown.

**Screenshots**
Liz and Jolie discovered this bug when supporting an instructor who couldn't add their TA to Sakai through Kits.  We discovered duplicate kits for the Combined Kit AMES.490S.01.F20.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by joliet** [comment]
Related to issue - Combined kits should not be created for cross listed courses https://github.com/DukeLearningInnovation/kits/issues/566

**Comment by joliet** [comment]
To test this I tried setting up the crosslisted course CULANTH 106S 01 F20 in Sakai.  This course has five crosslists - HISTORY:125S:01:13921:1740; PUBPOL:170S:01:13925:1740; VMS:106S:01:13927:1740; DOCST:105S:01:13979:1740 and POLSCI:105S:01:13923:1740.  I followed these steps:

1. Became instructor in Sakai, Gary Hawkins (hawkins)
2. Use Worksite setup to create the Sakai course site for CULANTH 106S 01 F20
3. In the course site, navigated to Site Info, Edit Class Rosters(s) and added the roster for CULANTH 106S 02 F20 to the site
3. In the course site navigated to Site Info and clicked Add Participants
4. On the Add Member page for this kit saw just two rosters - POLSCI:105S:01:13923:1740 and HISTORY:125S:01:13921:1740
5. The combined kit was created correctly on the Kits site with both crosslisted courses showing in the combined kit.
6. The member pages for each crosslisted kit shows correctly within Kits.  It is only displaying incorrectly when viewed from Sakai.

I should have seen the rosters for CULANTH 106S 01 F20 and CULANTH 106S 02 F20 and within each of these rosters should have seen the crosslists at the top (as displayed within each crosslist).  The crosslisted courses for 02 are: CULANTH:106S:02:13920:1740; POLSCI:105S:02:13924:1740; PUBPOL:170S:02:13926:1740; VMS:106S:02:13928:1740; DOCST:105S:02:13980:1740; HISTORY:125S:02:13922:1740.

@noahhh and @ewendland23 .  This was probably one of the most complicated crosslisted rosters I could test and had some unexpected results (see 4 in the list).  Let me know if you need more information or further testing.

**Comment by ewendland23** [comment]
Hi Jolie,

Kits did sort-of the right thing here.  It took each Provider ID and found the list of Siss Classes which include that.  It then created the first one.  It just didn't happen to be the same name as the Sakai site.

This would also happen if an instructor logged into Kits before setting up the Sakai site.  Kits would pick one of the 'names' of the cross-listed course and create that course.

You made this palatable in Kits by having the Cross listed courses "name" appear as:
CROSSLISTED COURSE Doc Exper F20
Doc Exper: A Video Appr

Maybe you need to change the "name" of the course in the combined kit roster view too?

We could do some monkey business to make Sakai-created crosslisted sites "match" what Sakai called them... but that would not work if the Kit was already created.

**Comment by joliet** [comment]
Thanks @ewendland23 .  I get it.  The two rosters for the cross-listed kits show, but just with a different course name than the Sakai course site.  I think in the case of cross-lists, which are really the same course and not different sections, showing the list of all students would probably make the most sense.  What if we displayed the associated roster for each student in a the participant table rather than at a list of rosters as the top?  We can address this later in a different sprint. It might make sense to include this with work to use Kits to set up all Sakai sites.
