### ISSUE TITLE
Don't create child kits before parent is ready in Combined Kits

### ISSUE THREAD

**Issue by joliet** [DukeLearningInnovation/kits#578]
**Describe the bug**
Liz found a bug with Combined Kits where children kits are being created before the parent is ready.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ewendland23** [comment]
I added a check after I create a parent to make sure the Grouper groups are synced before continuing.

**Comment by joliet** [comment]
I've tested this with several Sakai sites with multiple rosters and as far as I can tell, everything is working fine.  I can't seem to find the ticket I was working on when we found this issue so I'm not 100% sure I've replicated the scenario when we found this problem.  @ewendland23 any suggestions for how I might test to confirm your fix is working?
