### ISSUE TITLE
Re-label roles in non_course kits

### ISSUE THREAD

**Issue by joliet** [DukeLearningInnovation/kits#581]
I am a staff member trying to create a kit to collaborate with my department I don't know which roles to choose for members of the kit since the existing roles are used in courses. This makes me feel confused and worried that my teammates will not have the access they need to. collaborate..

How might we (the Kits project team) re-label the roles in non_course kits to make them more appropriate for teams and collaboration?

**Questions**
Label mapping:
Owner = instructor
Editor = assistant
Viewer  = student
Visitor = visitor

**Assumptions**
These are role label changes only.  The role names and permissions on the backend are the same a course kits.

**Hypotheses**
We discovered through testing that the roles used for courses are confusing to users who are using Kits for collaboration.

**Comment by noahhh** [comment]
@joliet new kits didn't have non_course kits.  I've added that with these roles, but this ticket ended up being pretty much #581

**Comment by joliet** [comment]
I see these roles for collaboration kit types.  Closing.
