### ISSUE TITLE
Add options for non_sis_course and non_course kit type in New Kit set up workflow

### ISSUE THREAD

**Issue by joliet** [DukeLearningInnovation/kits#582]
I am student trying to create a new kit for my study group but can only seem to create a kit that has student and instructor roles. This is confusing because my kit is not a course or for teaching and learning, just to share files and resources.

How might we (the Kits project team) add an option for users during set up that allows them create the type of kit they need with roles that reflect the type of work/context they are trying to accomplish?

**Questions**

**Assumptions**

**Hypotheses**
We know from usability testing that people using kits to collaborate find the student and instructor roles confusing.  Building this collaboration kit will allow users to choose their context and see appropriate roles.

**Comment by joliet** [comment]
Feature narrative doc that proposes kit type selection during the Create New Kit workflow - https://docs.google.com/document/d/1mYoS2WC7mpZ_PFTaSJSMIIx_hhr94U3-yJngTq5ztCY/edit

This issue is replaced #507 Add framework to distinguish between course-related kits and collaboration kits
Related issues: 
#581 Re-label roles in non_course kits
#470 Show existing ad-hoc toolkits to Kits platform (Closed)

**Comment by joliet** [comment]
Testing this.  It looks good from the Kits perspective.  When I set up a user-created on kit-test I am able to select the type of collaboration or course, and each have the correct roles.  However, when I set up a project site on Sakai-test and click Add participants, I am shown a kit with me added with the owner role.  After adding several colleagues with different roles and clicking Finish in Sakai, I do not see the the members I added to the kit in my site.  When I go to kits-test, I see the kit with the correct Sakai project site associated with it.  But it displays under the semester category heading instead of Project.  Here are details:

Sakai project site created: 
title: Kits Site Info Add Test
site id: 579f3836-0e7f-4736-9cbf-5cf4b3e63842

Kit associated with site:
Display name: Kits Site Info Add Test
kit id: 2080

Assigning back to both Liz and Noah to take a look.

**Comment by ewendland23** [comment]
Hi,  there are two separate issues so i will make two comments.

First. the Kit was created and it is of type CommunityVarietyID 7.  I am not sure where these should sort?  Which heading do they go under @joliet?  Since that isn't defined, Kits is just putting it in the first group (courses).

**Comment by ewendland23** [comment]
Second, the Kit has roles:
Owner
Editor
Viewer
Visitor

and the Sakai Site has:
maintain
access
Visitor.

That doesn't map so it failed to add people.  What is the correct mapping @joliet ?

**Comment by joliet** [comment]
Thanks for clarifying @ewendland23.

First issue - all kits that do not have their own category that are of the type collaboration should be categorized under the Project heading.

Second issue - I updated the doc I created a couple of weeks ago for app/Kits role mappings to include project site mappings and Kits roles.  Here is relevant part of that table:

Kits Collaboration Role | Sakai Project Site Role
-- | --
Owner | Maintain
Editor | Maintain
Viewer | Access
Visitor | Visitor

**Comment by joliet** [comment]
Tested creating a project site and adding members through Kits.  Members were added to Sakai with the correct roles.  Project site tested Kits Role Test for PS (siteid 789c0be2-4e85-4688-bb1d-62cbcd55dc7f).  Associated kit has same display name and has kit id of 2097.

All issues found in testing this feature have been resolved.
