### ISSUE TITLE
Update email address and message confirmation for Batch Create Sakai Sites

### ISSUE THREAD

**Issue by joliet** [DukeLearningInnovation/kits#584]
I am staff member who just created several Sakai sites for my school using the Batch Create Sakai Sites feature in Kits but the email confirmation I received is from 'toolkits@duke.edu' which makes me feel confused and unsure about the status of my sites.

How might we (the Kits project team) update the toolkits@duke.edu email address and subject of the confirmation message  'Toolkits Batch Sakai Site Creation' to use the word kits instead of toolkits?

**Questions**

**Assumptions**

**Hypotheses**
Message should be from kits@duke.edu and subject of message should be 'Kits Batch Sakai Site Creation'.

Example of current message:
<img width="750" alt="Toolkits_email_batch_create" src="https://user-images.githubusercontent.com/7387760/95476064-db88a380-0954-11eb-993a-35aa68b43523.png">

**Comment by ewendland23** [comment]
@joliet I can't figure out how to move this into the Test for our sprint but its ready to test.

**Comment by joliet** [comment]
This is working on test.  It can be moved to production when we are ready to move the Batch feature in kits-test to prod.
