### ISSUE TITLE
Add Help menu link in Kits top main menu

### ISSUE THREAD

**Issue by joliet** [DukeLearningInnovation/kits#591]
I am kits user trying to find documentation on Kits but I don't see an option for help in the application.  This makes me feel like I cannot successfully use Kits because I can't find help when I need it.

How might we (the Kits project team) make it easy for Kits users to find help docs when they need to learn how to use a feature in Kits?

**Questions**

**Assumptions**
Replacing About with Help menu, and moving About to the Account drop down is a good MVP to providing Kits help documentation.  Future goal is to provide contextual help.

**Hypotheses**
Making Help visible in the top main menu of Kits (replace About, move About to Account drop down) is good first step in making it easy for users to find help documentation for Kits.  This menu is persistent and therefore always available to users no matter which feature they are using in Kits.

Feature narrative here - https://docs.google.com/document/d/1f9hCATkd-k7iMuSYs_a2SVesEDWeTt642jAJv_LZJEQ/edit#heading=h.ykwu0qs5jr8r

Link to new Kits help - https://dukelearninginnovation.github.io/kits/

Related issues:
Redesign help to not go straight to qualtrics form #365

**Comment by joliet** [comment]
Coming back to this as we'll need help as part of Kits until we can get the docs server stuff ready.  We talked about opening Help in a new window and Joel CS said this is ok.  From 10/2/20 "I had a great conversation with Joel Crawford-Smith earlier about accessibility and end-user help documentation for Kits.  He said that we can do a new window/modal for help but we need to use this as a guide for how to do it for accessibility - https://www.w3.org/TR/wai-aria-practices-1.1/examples/dialog-modal/dialog.html "  More information here https://www.w3.org/TR/WCAG20-TECHS/G200.html

**Comment by joliet** [comment]
Tested and LGTM.

**Comment by noahhh** [comment]
@joliet this has been moved to production
