### ISSUE TITLE
Update or replace Toolkits landing page for decommission

### ISSUE THREAD

**Issue by joliet** [DukeLearningInnovation/kits#594]
I am staff member trying to set up a shared Box folder but I cannot use Toolkits to do this as I have in the past. This makes me confused as I don't understand the new process for creating shared Box folder.

How might we (the Kits project team) re-direct existing Toolkits users to Kits?

**Questions**
Do we disable all functionality on the Toolkits page?
Just disable create/edit but view is still possible until late spring?

**Assumptions**

**Hypotheses**

**Comment by ewendland23** [comment]
Jolie, this is on https://toolkits-test.oit.duke.edu for you to test.  We also rearranged the project so a good testing of Kits is warranted.  Thanks!
