### ISSUE TITLE
No Duke terms show in Batch Create Sakai Sites tool, only DKU

### ISSUE THREAD

**Issue by joliet** [DukeLearningInnovation/kits#595]
**Describe the bug**
When you access the Batch Create Sakai Sites tool in the Kits Admin Console, the only terms displayed are DKU.  No terms from DukeHub display in the drop-down.

**To Reproduce**
1. Go to kits.duke.edu as an admin or someone with scoped access
2. Click on the hamburger menu in the upper-left corner
3. Select Admin Console
4. Click on the icon for Batch Create Sakai Sites
5. Click the Term drop-down menu.
6. Only DKU terms are displayed

**Expected behavior**
Terms from both DukeHub and DKU's SIS should be shown in the drop-down menu

**Screenshots**
<img width="756" alt="Duke_Kits_Term_Issue_Batch_Create" src="https://user-images.githubusercontent.com/7387760/102095704-d5e68880-3df1-11eb-82c2-69ec1dad32ce.png">
.

**Comment by ewendland23** [comment]
I think this might be a Noah issue?  He just did something to get the latest DKU terms.  Adding him.

**Comment by joliet** [comment]
Thanks @ewendland23 and @noahhh .  I'm pretty sure the DukeHub upgrade broke the Sakai feed.  That may not be the issue here but mentioning it just in case.

**Comment by noahhh** [comment]
@joliet Liz and I found the issue.  It was due to how I was looking for the data vs the timezone in the DB causing them to duplicate. It is back to normal in prod now.

**Comment by joliet** [comment]
Resolved.
