### ISSUE TITLE
Synchronize resources periodically to make memberships consistent across tools

### ISSUE THREAD

**Issue by joliet** [DukeLearningInnovation/kits#596]
I am an instructor trying to add someone to my Sakai site and even though I see the person I added under Add Participants, I do not see them under Manage Participants or under groups in Sakai. This makes me feel confused and frustrated.

How might we (the Kits project team) periodically run syncs to make sure memberships are up to date across all tools including Sakai?

**Questions**
Can this periodic sync replace Synchronize Resources in Toolkits?
How often should we run the sync?

**Assumptions**

**Hypotheses**

**Comment by joliet** [comment]
Synch 30 minutes after kit is created, then synch again after 24 hrs, then 1 week later.

**Comment by joliet** [comment]
Liz and Richard discussed the best timing for the sync and decided that the sync with Sakai sites would happen for memberships that changed 15-75 minutes ago.

**Comment by ewendland23** [comment]
Every hour (at 26 minutes after) Kits checks for groups that were altered in the last hour.  If it finds any and they have a sakai site, it will run a Membership sync with Sakai.
