### ISSUE TITLE
Sympa List name too long

### ISSUE THREAD

**Issue by ewendland23** [DukeLearningInnovation/kits#601]
A Sympa list name has a Max Length of 50 characters.  Kits currently does not prevent longer names.  This causes the list creation to blow up.

**To Reproduce**
1. Create a course with a really long name. Better if it is a combined course... that adds more characters.
2. Add a Sympa list
3. See error

**Expected behavior**
Kits should truncate the default Sympa list name (but still including the Kit ID for uniqueness) to fit.  Or maybe even make the name something pretty - not using the 'link_to' field, but just the Kit name?  It already is doing a uniqueness check.

**Comment by joliet** [comment]
Resolved through the work done in #605.
