### ISSUE TITLE
Improve combined kit naming convention

### ISSUE THREAD

**Issue by joliet** [DukeLearningInnovation/kits#605]
I am faculty who set up a Sakai site through my combined kit.  The name for the Sakai site is really long and different than how my other Sakai sites are named. This makes me feel confused and like something is not working correct, or I did something wrong.

How might we (the Kits project team) devise a better naming convention for resources set up through combined kits.  The current naming convention is: kits_shared:SUBJCOURSESECTERM:SHARED:kitID.  Example: kits_shared:MATH216001Sp21:SHARED:48475

**Questions**
Can we use the word combined instead of shared?
Can we shorten the name?
What the technical requirements for the name?

**Assumptions**
We need to think beyond course naming as we may allow collaboration kits to be combined in the future.

**Hypotheses**

**Comment by joliet** [comment]
@ewendland23 and @noahhh - I did some testing on kits-test for this issue.  I set up several apps in the the combined kit 'Intro to Computer Science Sp21' (kit id 2220) - Sakai, Sympa, and Box.  The Sakai site title was the same as display name for the combined kit.  This is an improvement, but ultimately, we want the site title name to follow the Sakai convention of COMPSCI.101L.001.Sp21.  I know this is a little complicated in this scenario (and with crosslisted courses) as there is more than one possible name. A drop-down list for the name would be ideal with the possible options.  A good MVP for combined kits would be to just use the first lecture section (001) or when no lecture section is there, the first lab/discussion section (01L/01D).  I don't have a good MVP option for the cross-listed scenario.  We'll need to let folks add a name until we can get the drop-down list or something similar available.

The Box folder was named the long combined kit name - kits_shared_introtocomputersciencesp21_shared_2220.  Using the display name for the combined kit to name the Box folder would be ideal.

I have no idea what happened with the Sympa list.  I can't seem to access that.  The icon is not grayed out but nothing happens when I click on it, and I've searched every likely name in Sympa to find it with no luck.  Can you see anything on your end @ewendland23 ?

**Comment by joliet** [comment]
Provide Sakai title examples for combined, crosslists, single roster, adhoc - all naming scenarios for Sakai.

**Comment by ewendland23** [comment]
@joliet - There is no requirement that Combined Kits be composed of different sections of the same course so I am not sure what to do in those cases... 

Here is a proposal.  I don't care if this is what we do, but I need the decision  in this type of format...

Proposed Naming:

Courses with a current SISS record

* Normal (not-cross listed) course:
  * All Resources
	  * id: Sakai-style for course- **PSY.106.001.1Su21**
	  * title: Kit Title (normally course title) -  **PSY 106 - 001: Bio Bases Of Behavior (Lecture)**

* Cross-listed and Combo courses:
  * All Resources
      * id: Let them choose the id from a list of all the Sakai-style ids for all crosslists and/or combined kits. For example:
		    * PSY.106.001.1Su21
		    * PSY.106.002.1Su21	
		  	
      * title: They have to enter title - defaults to Kit Title

	
Kits **without** a current SISS record

* Singleton and Combo:
  * All Resources
	  * id: uuid i.e. a65cad00-b4ee-11eb-8529-0242ac130003 
	  * title: user-entered.  Default to Combo Kit title

**Comment by joliet** [comment]
The doc is here - https://docs.google.com/document/d/13A5Qp0yW_V-611NlaFcStX5buZv8T1Nrz41hd36Vtig/edit# . I think this is what you were looking for?  I think this is the format you need, correct?

**Comment by joliet** [comment]
Ok @ewendland23 .  Take a look at this doc one more time and let me know if you have any other questions I should get answers to.  If not, I think this is ready - https://docs.google.com/document/d/13A5Qp0yW_V-611NlaFcStX5buZv8T1Nrz41hd36Vtig/edit#

**Comment by ewendland23** [comment]
Hi Jolie,

This is looking really good now!

The only thing that might be missing –
Combo course where:

  *   One or more of the combined kits are cross-listed
  *   The combined kits do not have the same Class Title

Do you want the Class Title/Semester option for all possible options?  For all crosslists?

Thanks!
Liz

From: Jolie Tingen ***@***.***>
Reply-To: DukeLearningInnovation/kits ***@***.***>
Date: Tuesday, June 1, 2021 at 5:00 PM
To: DukeLearningInnovation/kits ***@***.***>
Cc: Liz Wendland ***@***.***>, Mention ***@***.***>
Subject: Re: [DukeLearningInnovation/kits] Improve combined kit naming convention (#605)


Ok @ewendland23<https://urldefense.com/v3/__https:/github.com/ewendland23__;!!OToaGQ!6IVHTO8rOMll2B8bTAFYP2PpKxKuH4AgcoE2A0mlumtlAYiJ5BJ8vew65ckD$> . Take a look at this doc one more time and let me know if you have any other questions I should get answers to. If not, I think this is ready - https://docs.google.com/document/d/13A5Qp0yW_V-611NlaFcStX5buZv8T1Nrz41hd36Vtig/edit#<https://urldefense.com/v3/__https:/docs.google.com/document/d/13A5Qp0yW_V-611NlaFcStX5buZv8T1Nrz41hd36Vtig/edit*__;Iw!!OToaGQ!6IVHTO8rOMll2B8bTAFYP2PpKxKuH4AgcoE2A0mlumtlAYiJ5BJ8vfDRNJo7$>

**Comment by joliet** [comment]
Hi @ewendland23 .  I added the specific example of a combined kit with cross-listed courses.  In general, the format is: if there is a roster, it is a naming option in the drop-down menu with the specified formatting for each app.  I tried to be as consistent as possible while balancing readability.

In every case, drop the course format (lecture, lab, etc).  Every naming option will include a selection that is just the class title with the semester (Sp21, F21, etc) at the end to allow a more generalized title for these complex roster scenarios.  Does that make sense?

**Comment by ewendland23** [comment]
Jolie,  Here is my first cut at this.  There are a few things missing:
1) I haven't added the extra apps - Zoom, Wiki, etc.  Let's see how this goes?  Maybe we should make a separate issue for them?
2) I also haven't made it possible for users to change the names of anything.  Can we leave that out for this first effort?  Just to get this rather large effort into production?

Thanks!
Liz

**Comment by joliet** [comment]
Sure @ewendland23  let's do all of your recommendations:

- Create issues for Zoom, Wiki, Warpwire, and Panopto
- Create an issue that allows users to modify names for user-created kits

Thanks for your work on this!  I will start testing and get the issues created early next week.

**Comment by joliet** [comment]
Hi @ewendland23 .  Names in the drop-down menus for course kits looks great!  The only issue I found with that is in combined/cross-listed kits the names were repeating (see below).

Here are my testing results:

Single Roster course kit:
COMPSCI 334 - 01 Sp21
Mathematical Foundations (Lecture)
Kit id 2208
- Setting up MS Teams for a single roster SIS course kit, the second setup page with Team Type dropdown never displayed only the Kit name + permissions page (1st one)
- Box folder for single roster course did not include semester at the end of the folder name.  Example: Box folder https://duke.app.box.com/folder/140864724374. Name is COMPSCI 334 - 01: Mathematical Foundations Lecture and should be COMPSCI 334 - 01: Mathematical Foundations Lecture Sp21

Combined kit:
Programming/Problem Solving F21 (https://kits-test.oit.duke.edu/shared_kits/2419)
COMPSCI 94 - 01: Programming/Problem Solving (Lecture)
COMPSCI 94FS - 01: Programming/Problem Solving (Lecture)
- Teams never set up properly for this kit.  Maybe related to the / in the class title?
- All roster participants except the instructor are adding manually to the Sakai site.  Example: Combined kit Programming/Problem Solving F21 (https://kits-test.oit.duke.edu/shared_kits/2419) and Sakai site https://sakai-test.duke.edu/portal/site/programmingproblem-solving-f21.  This issue only seemed to affect combined kits.  The single roster course kit added all roster members non-editable as expected.
- Note: I set up Panopto for this kit and it worked as expected.

CROSSLISTED COURSE 01 Sp21
Motown And American Soul Music (Lecture)
Kit id 2149
- Sympa never properly set up for this kit.  The icon is still grayed.

Crosslisted and Combined kit:
Interactive Graphics Sp21
Kit id 2435
ISS 294L - 001: Interactive Graphics (Lecture)
ARTSVIS 794L - 01L: Interactive Graphics (Lab)
VMS 794L - 001: Interactive Graphics (Lecture)
ARTSVIS 242L - 01L: Interactive Graphics (Lab)
- All possible names for Sakai site are duplicated (see image)

https://user-images.githubusercontent.com/7387760/125645398-ff73b9ce-55b4-47a3-bcac-c1425b4c7153.mp4

- Sympa setup for this one went straight to "We're sorry something went wrong." Right after I typed In the Kit Display name, selected sharing/visibility and clicked

**A note about app naming for user-created kits (both types): including the kit id will likely be an issue for users.  They don't have a lot of control over the names and the kit ids don't really mean much to them.  I know we said that we need make sure names are unique and this is one way we can do it.  We'll likely need to come back to this to improve naming.  Something else to consider - display names can be edited.  This can create a disconnect between app names. I will add this to the Kits documentation to help manage expectations for this.**

User-created course kit:
NURSING 2021-07
2021 Student Orientation
kit id 2436

User-created collaboration kit:
TEAM 2021-07: DLI DEIA Committee
kit id 2437
- kit members did not get added to the Sakai site.  I think we need two things - 1) adding Sakai to a collaboration kit should create a project site, not course and 2) we need to map our collaboration kit role names to the new role names in Sakai projects sites (they are the same role names).

**Comment by ewendland23** [comment]
@joliet 

For Single Roster Box, I can't duplicate your issue.
Here is what I got adding Box to https://kits-test.oit.duke.edu/admin/view_kit/2439
![Screen Shot 2021-07-28 at 9 16 37 AM](https://user-images.githubusercontent.com/4522248/127328867-14a9b55f-6660-416e-98e9-749b7fc14500.png)

**Comment by ewendland23** [comment]
- Course w/single roster
  x Panopto wasn't asking for Support Dept.
  x Teams wasn't asking for Team type.
  x Box folder missing semester at the end of the name. (This was true for wordpress and sympa too)

- Combined
  _ Sakai sites don't have rosters, just added members.
      **Not related to naming convention.  We should move this to another ticket.**
  x Sympa failed for Test kit 2149 (fixed bug)
- Combined/Crosslisted
  x Test kit 2435 sakai setup lists all name options twice.
    - actually, the names of the combined kits are almost exactly the same (Lab and lecture)
      so it did the right thing.  The Generic name is the same though so i can remove the
      duplicates of that.
  x Sympa exception for 2435 (probably same as for Combined.)
- Can Teams titles handle a / ?  (Yes)
- Adhoc/Collaboration 
  **(the following issues aren't related to naming - we should make another ticket)** 
  _ Adding Sakai should create a project, not a course site. 
  _ Remap role names.

**Comment by joliet** [comment]
Need to confirm these issues can also be closed when this work is done - #541 and #503.

**Comment by joliet** [comment]
Small issues found while testing.  Creating separate issues for those.
