### ISSUE TITLE
Collaboration kit does not show Edit Kit in menu for kit owner

### ISSUE THREAD

**Issue by joliet** [DukeLearningInnovation/kits#608]
**Describe the bug**
There is no option for Edit kit in the kabob menu for the kit owner.

**To Reproduce**
1. Go to kits.duke.edu
2. Click on Admin Console
3. Search for kit "Digital Learning Strategy Group"
4. Click kabob menu, no Edit kit

**Expected behavior**
I expected to see Edit kit in the kabob menu so that I could delete the kit (two were created by accident).

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by joliet** [comment]
I tested this several faculty on kits-test and combined kit creations seems to be working fine.

**Comment by joliet** [comment]
Commented and closed the wrong issue.  This one needs another look still.

**Comment by ewendland23** [comment]
I found and fixed the issue.  Can you please test again @joliet ?

**Comment by joliet** [comment]
Tested with several existing collaboration kits and a new one with apps.  I was able to access Edit Kit for all and Delete.
