### ISSUE TITLE
Cannot browse all available kits in Combine Kits, Add Kits

### ISSUE THREAD

**Issue by joliet** [DukeLearningInnovation/kits#613]
**Describe the bug**
In list of kits for Add Kits in step one of Combine Kits, not all results are showing, and pagination (1 of 2) does not allow access to page 2.

**To Reproduce**
1. Go to kits-test
2. Impersonate faculty cdr42
3. Click on Create Combined kit
4. Pagination of results shows 1 of 3
5. Only page 1 results are accessible

**Expected behavior**
In some cases (like this one) a faculty may have more than 10 courses that they are combining.  There is no way to select all results if there are more than 10 kits you would like to combine.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ewendland23** [comment]
This also happens on the paging for Search All Kits.  It is something in React.  It looks like next_page was never implemented in Javascript?

**Comment by joliet** [comment]
Tested in combined kits, batch create, search all kits, and view activity.  Looks good @noahhh  Thanks!  We can push this to prod.  I'll let you and @ewendland23 decide when is best to do that.
