### ISSUE TITLE
Remove 'View as Student' from Collaboration kit menu

### ISSUE THREAD

**Issue by joliet** [DukeLearningInnovation/kits#619]
I am a staff member trying to use a collaboration kit but I see a menu item labeled 'View as Student'.  I don't have any students in my kit so the menu item is confusing.  This makes concerned that something might be wrong with my kit.

How might we (the Kits project team) hide the 'View as Student' menu item in the kabob menu for collaboration kits?

**Questions**
Should this menu item be relabeled to be more generic?
Would collaboration kit owners use this feature?

**Assumptions**

**Hypotheses**

**Comment by joliet** [comment]
Tested this and it looks good.  Closing.

**Comment by noahhh** [comment]
This has been moved to production
