### ISSUE TITLE
Make OKD Kits kits-test

### ISSUE THREAD

**Issue by joliet** [DukeLearningInnovation/kits#629]
I am developer trying to manage code for Kits but there are too many environments.  This makes it hard for me to keep track of code changes which is frustrating.

How might we (the Kits project team) make the new Kits OKD environment kit-test?

**Questions**

**Assumptions**

**Hypotheses**

Tasks for this issue:

- [x] Resolve React issues (need Jim Wood's assistance)
- [ ] Jolie tests to find bugs with moving kits-test to OKD

**Comment by joliet** [comment]
The following issues were found during testing:

- [ ] Spacing/padding too wide between app icons in kit (tested on Chrome and Firefox)
- [ ] Impersonate a User feature doesn't work.  Yellow snackbar message at bottom of screen shows you are impersonating you.
- [ ] Confirmation message (green snackbar at top of screen) confirms you logged in successfully - not needed.
- [ ] Add back Help menu item instead of About (see https://github.com/DukeLearningInnovation/kits/issues/591)
- [ ] Collaboration kit I used for testing had the semester of Sp22 appended to the Kit ID in the name.  Kit is TEAM 2021-03 Sp22 Test Collab Kit for OKD (kit id 2221)
- [ ] Warpwire library added to kit did not set up correctly.  Keeps prompting for Duke NetID but never shows library - https://warpwire-frontend-test.oit.duke.edu/w/LW4CAA/
- [ ] I was not added to the Sakai site I set up through my kit.  This could be because of role mapping issues between collaboration kits and Sakai sites.  We'll need to fix this soon, not urgent.  I will create two issues for follow up - 1) Collaboration kits should set up Sakai project sites and 2) Roles in Sakai project sites should match Collaboration Kit roles (change on Sakai side but need an issue for reminder)
- [ ] Edit/remove icons on app skewed to pill shape.  Should be circles.
- [ ] Clicking Remove App from kebob menu and clicking on App to remove doesn't stop at first app removal.  After clicking remove in pop-up confirmation, prompts to delete next app in kit.  Click remove should delete app, close popup, and refresh.
- [ ] Wrong role displayed in drop-down menu for members table.  Collaboration kit shows correct roles in drop-down when adding, but drop-down for role change shows Instructor, Student, Assisstant.
- [ ] Sakai site templates missing on kits-test during site set up through kit and during batch create sites - Advanced Course Template (site id eedaab1d-ed06-4953-9e3c-9093aececd47), Minimal Course Template (site id 099f8e3f-1da3-4d1b-854f-03c754fc58a7),  DKU Graduate Template (site/535eb91d-323b-41fa-a857-f129013482cf).

I will test more tomorrow @ewendland23  with all types of course kits.

**Comment by joliet** [comment]
Testing today with courses:

- [ ] Set up a Sakai site for Jocelyn Olcott in History (olcott) - HISTORY.790S-02.01.Sp21  (site id c3385a77-9f17-4cf2-b9de-9b8ea457cf0e).  When I click Add Participants in her Sakai site I see "We're sorry, but something went wrong.
If you are the application owner check the logs for more information."  I think @ewendland23 said testing with sakai-test would not work?
- [ ] Same issue as above when adding Warpwire library to combined kit.  Doesn't ever show library, just prompts for Duke NetID login. (used the following kits for testing GREEK 312S - 01 Sp21 Oratory And Rhetoric (kit id 2194) and GREEK 764S - 01 Sp21 Seminar Greek Lit I (Top) (kit id 2196).  Combined kit is COMBINED KIT Greek Courses Test (kit id 2228)

These are all the issues I found today testing with sis-course kits and non-sis course kits.  Happy to retest when issues are resolved and need re-testing.

**Comment by ewendland23** [comment]
I checked the first 5 issues.  Does that stick?  Thanks to @noahhh  and Jim Wood for doing number 1.

**Comment by ewendland23** [comment]
@joliet  - I can't find the templates you list on sakai-test.  535eb91d-323b-41fa-a857-f129013482cf is not found for example.  Or maybe i don't understand what you meant?

**Comment by ewendland23** [comment]
@joliet  - I can't replicate the Remove App issue.  Which type of resource were you removing?  I have been testing with the Custom Link apps because they are so simple.  I wonder if it only happens for a specific app?

**Comment by ewendland23** [comment]
Hi @joliet, I think we are ready for you to retest.  Thank you!

**Comment by joliet** [comment]
I've retested sis-course kits, non-sis course kits, collaboration kits (with new & existing), adding/editing/removing apps and members in all.  I tested all features in the admin console including confirming non-admins can't access that.  It looks good.  Closing this issue.
