### ISSUE TITLE
Cannot sort by Type, Creator, Category, Date headers in Search All Kits results

### ISSUE THREAD

**Issue by joliet** [DukeLearningInnovation/kits#636]
**Describe the bug**
When viewing results in Search All Kits, result can only be sorted by Kit ID Number and Kit Display name.

**To Reproduce**
1. Go to the Admin Console
2. Click on Search All Kits
3. In the search box type ECE
4. In the results table, click the headings Type, Creator, Category, and Date

**Expected behavior**
I expected to be able to sort the results by these column headings.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by noahhh** [comment]
@joliet is this fixed since we switched view all kits (and other pages) to use the same table/pagination styling?

**Comment by joliet** [comment]
Thanks for following up on this one @noahhh .  Just checked this and it looks likes this is working to me.  Closing.
