### ISSUE TITLE
Not enough space between app icons in a kit

### ISSUE THREAD

**Issue by joliet** [DukeLearningInnovation/kits#645]
**Describe the bug**
There seems to be no spacing between app icons in kits.

**To Reproduce**
1. Go to kits.duke.edu
2. Look at any kit with multiple apps.
3. App icons have no spacing between.

**Expected behavior**
I expected there to be a little space between each icon.

**Screenshots**

<img width="288" alt="App_Icon_Spacing_Issue" src="https://user-images.githubusercontent.com/7387760/115877833-e0570580-a415-11eb-93e6-247b2e8b2828.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by noahhh** [comment]
@joliet I put something out in test for this.  Can you look there when you have time and make sure they no longer overlap/touch?

**Comment by joliet** [comment]
Looks good to me @noahhh .  Thanks!  We can push this to prod whenever you and Liz are ok with that.
