### ISSUE TITLE
Access Denied error when using Impersonate a User

### ISSUE THREAD

**Issue by joliet** [DukeLearningInnovation/kits#647]
**Describe the bug**
Staff in Nursing (tlmoore and bd47) who have scoped access to Nursing kits are receiving an 'Access Denied' error when using the 'Impersonate a User' feature.

**To Reproduce**
1. Go to kits.duke.edu
2. Click on Account, Impersonate a User
3. Receive error Access Denied

**Expected behavior**
After clicking 'Impersonate a User' the expectation is that you will see a page to search for a user to impersonate, click impersonate next to their name in the results, and then view/act on Kits as that user.

**Screenshots**
<img width="509" alt="kits_duke_edu_admin_impersonate_access_denied" src="https://user-images.githubusercontent.com/7387760/116576916-02e99280-a8de-11eb-9508-1d74386551c5.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ewendland23** [comment]
Hey Jolie, I mistakenly was assuming you had to be a Sys Admin to Impersonate users.  I switched it to also allow Program admins.  If you test this on Kits-test i can move it to production.

**Comment by joliet** [comment]
Thanks, Liz.  I tested this and had the Nursing folks test as well.  Seems to be working now.
