### ISSUE TITLE
Is a learning community = to a slack workspace or discourse space?

### ISSUE THREAD

**Issue by profmikegreene** [DukeLearningInnovation/kits#65]
At the future of online at duke panel, there was talk about networked communities of learners. Does that have a place here or is this the thing that connects you to your communities quicker/easier?
Maybe part of the UI is linking to the community that gets created for every course? Every course gets a slack channel?

**Comment by profmikegreene** [comment]
Saying every learning community gets a slack or discourse is different than adding those into /apps for users to enable. It bakes that concept into what we're defining as a learning community, which may or may not be what we want. I lean towards not, as I imagine that leading to a bunch of unused slack/discourses, similar to why we don't auto-create Sakai sites for every learning community.

**Comment by JustinJohnsen** [comment]
I would say more generally every learning community might have a chat space. It might be default on or default off, but I wouldn't make it mandatory.

**Comment by profmikegreene** [comment]
This also seems directly related to /templates where we are effectively stating to users that we know what toolsets effective learning communities use and how to configure them.
