### ISSUE TITLE
Manage Panopto Departments

### ISSUE THREAD

**Issue by joliet** [DukeLearningInnovation/kits#655]
I am a Panopto administrator trying to add a new department to the list of options in Kits but can't find that option the Admin Console of Kits.

How might we (the Kits project team) create a new icon that represents the Manage Panopto area in Kits?

**Questions**

**Assumptions**

**Hypotheses**

**Comment by joliet** [comment]
Once Jen designs the icon for the Admin Console, the next steps are:

1. Style configuration page to be inline with Kits pattern library.
2. Add icon to Admin Console and link to Panopto configuration page.

**Comment by curiousmustard** [comment]
Created icon: https://www.figma.com/file/vbjsQkApG7rNknJUwv73xG/Admin-Console?node-id=0%3A16292

Kept it simple by using the Panopto logo icon, I figure that's best for scanability  in the admin console.
