### ISSUE TITLE
Update Search design throughout Kits

### ISSUE THREAD

**Issue by joliet** [DukeLearningInnovation/kits#656]
I am staff member trying to use the search feature in Kits but it looks different than the search box I've used on other pages.  This makes me think that the designs behave differently and I might not get the results I expect.

How might we (the Kits project team) make all search options in Kits use the same design?

Specifically, Search on these pages need to be updated:
https://kits.duke.edu/shared_kits
https://kits.duke.edu/admin/impersonate
https://kits.duke.edu/admin/batch_create
https://kits.duke.edu/admin/search
Exception: https://kits.duke.edu/admin/activity_log (but maybe use X instead of CLEAR?) That would be a clear per individual filter, though and might not work.  This one can be skipped if that doesn't work.

**Questions**

**Assumptions**

**Hypotheses**

**Comment by joliet** [comment]
Thanks, @noahhh , this looks good.  Unfortunately, I missed a page - View/Edit Members for a combined kit.

**Comment by noahhh** [comment]
@joliet I've made this change to the view/edit members for combined kit

**Comment by joliet** [comment]
Looks good!
