### ISSUE TITLE
Provide user feedback when apps don't set up correctly

### ISSUE THREAD

**Issue by joliet** [DukeLearningInnovation/kits#659]
I am an instructor trying to set up an app for my kit but the app has been greyed out for several hours.  I don't know what this means.

How might we (the Kits project team) provide better feedback to users when and app doesn't set up correctly?

Issue that is part of this work - https://github.com/DukeLearningInnovation/kits/issues/721 (Define time frame for app pending state)

**Questions**

**Assumptions**

**Hypotheses**

**Comment by joliet** [comment]
Give options like retry, delete, or contact OIT.

**Comment by joliet** [comment]
Link to Figma mockup for this design - https://www.figma.com/file/dB483dx21JgjFYbJD059Dr/Pattern-Library---Kits?node-id=0%3A2265

**Comment by noahhh** [comment]
@joliet I put some changes for this out in test, let me know what you think.

**Comment by joliet** [comment]
This looks great @noahhh .  I like the way you improved the modal design with the Remove and Cancel options.  That will save the user a step which is always good.  There's a slight wording issue on the modal.  It says "There was a problem adding Listserv to kit Test Collab OKD Edit. Click 'remove' below try and re-adding the app, or contact OIT."  I think you just need to change the order of the words 'try' and 'and' to read "Click 'remove' below and try re-adding the app". 

I noticed that after I click remove the app disappears from the kit, but in the app store the app still shows as added to the kit, so it can't be re-added.  Is that work in another issue?

**Comment by noahhh** [comment]
I fixed the text error, thanks for catching that.

For the second issue, I'll tag in @ewendland23 .  Liz, I'm using the same method to remove these apps as you would remove a normal app.  It calls app_store_controller#destroy which uses @resource.teardown.  It looks like some (or all?) of the 'pending/error' apps removed this way aren't deleting the resource.  If they have an issue setting up causing this pending/error status, could they be running in to an issue tearing down successfully too?  Thus preventing the resource from being removed. (App model #available_for_course still returns :exists which is what displays the flag in the app store saying you already have an app for this kit)

**Comment by ewendland23** [comment]
One last thing to do is to make sure all the resource.teardown methods can work no matter what state the resource is in.  For example if the resource was never created, the delete should not fail because it can't destroy it.
