### ISSUE TITLE
Divinity Scoped Access users can't access courses that begin with PREACHNG

### ISSUE THREAD

**Issue by joliet** [DukeLearningInnovation/kits#670]
**Describe the bug**
When Divinity Scoped Access users search for courses that begin with PREACHNG, they get no results - can't see those courses.

**To Reproduce**
1. Become Karin Reese
2. Click on Search All Kits in the Admin Console
3. Search for a kit that begins with PREACHNG
4. None found

**Expected behavior**
There are many course kits for this subject.  I suspect there is a typo in the subject per the Scoped Access master doc that shows all Scoped Access configurations.  The subject mapping is likely spelled PREACHING.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ewendland23** [comment]
@joliet - I fixed this and pushed to Production.  I am not sure how to adjust this ticket to show that.

**Comment by joliet** [comment]
Confirmed with the Divinity folks this is fixed.
