### ISSUE TITLE
Make creator of SIS course kits the instructor by default

### ISSUE THREAD

**Issue by joliet** [DukeLearningInnovation/kits#671]
I am Kits administrator trying to understand who is using Kits but the data for official course kits is misleading.  When a student logs into Kits and official course kits for that student are set up, they are shown as the creator of this kit.

How might we (the Kits project team) more accurately reflect the 'creators' of official course kits?

**Questions**
Should the default automatically be the instructor?
Should the default be the 'system'?
Should the default be 'roster participant'? If so, would it be more useful to show something like 'roster: 'netid' or roster: 'student'?

**Assumptions**

**Hypotheses**

**Comment by ewendland23** [comment]
@joliet you can test this by creating any kits_course kit.  It should always show the creator as the **first instructor of record**.  Batch add or courses created as a result of a student logging in will verify this.  All other types of kits should still show the requestor as the creator.

**Comment by joliet** [comment]
This looks good to me, Liz.  Tested masquerading as several students.  Looking up official course kits under Search All Kits showed the instructor as the creator of the kit.
