### ISSUE TITLE
Heading, checkbox, and radio button styles wrong on Kits-test

### ISSUE THREAD

**Issue by joliet** [DukeLearningInnovation/kits#678]
**Describe the bug**
I'm seeing the wrong styling for Header text, checkboxes, and radio buttons on Kits-test.  See screenshots below.

<img width="1249" alt="Batch_Create_Heading_Style_Issue" src="https://user-images.githubusercontent.com/7387760/139480237-de5699c8-c320-45da-9aee-ff9744c97acb.png">

<img width="1173" alt="App_Setup_Radio_Button_Issue" src="https://user-images.githubusercontent.com/7387760/139480263-4ce59fa8-8ea6-493c-9732-ae2a1d158bfc.png">

<img width="637" alt="My_Kits_Heading_Issue" src="https://user-images.githubusercontent.com/7387760/139480281-5c473647-6d8b-4477-8fa8-966b06a85c53.png">

<img width="1402" alt="Combined_Kits_Heading_Checkbox_Styling_Issues" src="https://user-images.githubusercontent.com/7387760/139480302-b023d646-e4b3-4936-96a7-320715f0fc56.png">

**Comment by noahhh** [comment]
Hey @joliet sorry, just remembered this ticket.  Are you still seeing this?  I have no issues in kits-test.  If you are, what browser/version are you using?

**Comment by joliet** [comment]
Hi Noah.  I'm not seeing this now.  I'm going to close this one.
