### ISSUE TITLE
Role drop-down menu for Visitor option shows wrong roles in collaboration kit

### ISSUE THREAD

**Issue by joliet** [DukeLearningInnovation/kits#681]
**Describe the bug**
When trying to change the role of a Visitor in a collaboration kit, the role drop-down menu shows Instructor, Student, Assistant instead of Owner, Editor, Viewer

**To Reproduce**
1. Go to kits-test
2. Click on collaboration kit New PS Roles Testing Site (kit id 2642)
3. Click on View/Edit members, then Edit Mode
4. Click drop-down menu to change role for Tammy Toler
5. See Instructor, Student, Assistant instead of Owner, Editor, Viewer

**Expected behavior**
For collaboration kits, all roles listed for adding/editing should be Owner, Editor, Viewer, Visitor.

**Screenshots**
<img width="1308" alt="Project_Site_Roles_Visitor_Switch_Issue" src="https://user-images.githubusercontent.com/7387760/140192088-24c9416c-34c1-467f-9934-ad817e2d2537.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ewendland23** [comment]
As we have discussed in various meetings, this issue uncovered other issues with changing roles.  Please test this as well as modifying the Roster roles for kits_course sites.

**Comment by joliet** [comment]
I tested several sites/kits of all types (collaboration, sis course and non-sis course), both old and new.  I couldn't find any scenario where the drop-down menu for roles were not consistent with the kit type, or showed roles it shouldn't (e.g., showing Assistant when the member had the role Assistant).

I have asked Marty to do some testing as well.  Will follow up soon on that.
