### ISSUE TITLE
Add Back to Admin Console navigation for all features there

### ISSUE THREAD

**Issue by joliet** [DukeLearningInnovation/kits#682]
I am academic support staff trying to go back to the main page of the Admin Console in Kits from the Batch Add Members feature but there is no clear way for me to do that.

How might we (the Kits project team) make it easy to go back to the Admin Console main page when using a feature there?

**Questions**

**Assumptions**

**Hypotheses**

Adding a new navigation element to all features modeled on the 'Back to My Kits' navigation will make sense to users and follows our current navigation patterns.  This can be seen in two new Admin features in Figma (link to be shared in team meeting).

(above heading for the Manage Panopto Departments feature and the Managed Scoped Access feature)

**Comment by noahhh** [comment]
@joliet should this be available on all steps of a feature?  Or just the first?

**Comment by joliet** [comment]
Hi @noahhh .  I think adding to just the first step will be fine.

**Comment by joliet** [comment]
Looks good, Noah.
