### ISSUE TITLE
Display kit members as lastname, firstname in member table

### ISSUE THREAD

**Issue by joliet** [DukeLearningInnovation/kits#699]
I am instructor trying to search for one of my students in my course kit but I can't easily scan the member table as it is organized by first and last name.

How might we (the Kits project team) make it easier for kit owners to scan the kit member table in a predictable order such as lastname, firstname alphabetically.

**Questions**

**Assumptions**

**Hypotheses**

**Comment by joliet** [comment]
Add attributes to member table and how to display.  SN for last name, eduperson nickname for first name.

**Comment by joliet** [comment]
This looks good @noahhh and @ewendland23 .  Two things I found while testing this:

1 - the default sort order for the name column is by first name.  If we are starting with lastname, we should sort by the alphabetically ascending by default.
2 - there is an issue with displaying the last name when the person has a suffix.  The last name is skipped and only the suffix shows.  This is going to be a really common scenario with many faculty having Ph.D. as a suffix.  I found this in the kit ECE 458 - 02: Eng Software Maintainability (Lecture) with faculty Tyler Bletsch, Ph.D.  The display for him in the member list is Ph.D., Tyler.

**Comment by joliet** [comment]
@ewendland23  will - See if the names can be split more intelligently.  Verify we have the right data for everyone in LDAP.

**Comment by noahhh** [comment]
@joliet your first issue should be fixed on test

**Comment by ewendland23** [comment]
@joliet  - i noticed that the Kit you mentioned had Tyler with Ph. D. already was showing him with the correct name.  I think people will get refreshed as people are looking at kits, etc.  

I can't figure out a way to easily split the name more intelligently, But I was able to run a very easy command to fix everyone with Last Name Ph.D. so I can do some cleanup like that when we move this to production.

**Comment by joliet** [comment]
Sounds good @ewendland23 .  Your fix looks good too @noahhh .  I think this is ready for prod?  Let me know if we are waiting on something I'm not remembering here.  If not, I will close this issue so we know it's ready.

**Comment by joliet** [comment]
Combined kits looks good @noahhh .  I spent a little time re-checking all the kit types and didn't find any issues.  The combined kits fix is ready for prod.
