### ISSUE TITLE
Add a 'num per page' option for all tables in kits

### ISSUE THREAD

**Issue by joliet** [DukeLearningInnovation/kits#701]
I am instructor with a very large course trying to quickly scan the student data in the member table. I can only see 20 students per page and it would be really helpful to see 50 students per page.

How might we (the Kits project team) add a 'num per page' option to all table data in Kits.

**Questions**

**Assumptions**

**Hypotheses**

**Comment by joliet** [comment]
Hi @noahhh .  That was fast!  I didn't realize you had moved this to test.  Looks good!

**Comment by noahhh** [comment]
@joliet this is in production now
