### ISSUE TITLE
Winter Term missing from in Kits

### ISSUE THREAD

**Issue by joliet** [DukeLearningInnovation/kits#708]
**Describe the bug**
Winter Term 2022 (an previous Winter terms) is missing from the semester drop-down menu under My Kits and from the Batch Create Sakai Sites feature.

**To Reproduce**
1. Go to My Kits.
2. Click on Impersonate a User selecting a Law faculty member.
3. Notice no Winter terms under semester drop-down.

**Expected behavior**

**Screenshots**
Winter Term should be an option under the semester drop-down menu and in the term selection for Batch Create Sakai Sites.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by joliet** [comment]
I think we decided it would be hard for me to test this.  I was thinking about batch creating some Sakai sites for Winter Term 2022 so that I would be able to see those in kits-test, but I'm not seeing that term in the Batch Create Sakai Sites feature.  @noahhh  and/or @ewendland23 , can we get Winter to show there so I have some kits to test with?  Thanks!

**Comment by noahhh** [comment]
Hi @joliet.  We take the current term and the 5 closest upcoming terms and the current term, so winter doesn't show up in the dropdown list yet.  Should we increase the number of terms we display?  Winter would show up at that point.

**Comment by joliet** [comment]
Hey @noahhh .  If we are taking the next 5 upcoming terms, wouldn't we get Winter 2023?  The current term is Spring 2022 and the next 5 terms would be Summer 1 2022, Summer 2 2022, Fall 2022, Winter 2023, and Spring 2023.

Unfortunately, Winter Term 2023 won't have any classes yet so I wouldn't really be able to get some test data for that term, just confirm it is showing up.  Would it be better just to push this to prod?  I assume faculty with Winter 2022 courses would see kits in that term, correct?

**Comment by noahhh** [comment]
@joliet the batch create sakai page includes DKU terms as well

**Comment by noahhh** [comment]
@joliet Sure, I can go ahead and move this to prod
