### ISSUE TITLE
Sakai site type for a non-sis course kits should be course instead of project

### ISSUE THREAD

**Issue by joliet** [DukeLearningInnovation/kits#710]
**Describe the bug**
When a user sets up a Sakai site for a non-sis course kit, the Sakai site type is project but it should be course.

**To Reproduce**
1. Go to kits-test
2. Click on Create Kit
3. Select type of course
4. Add kit id and kit display name
5. Save and create kit
6. Add Sakai to kit
4. When Sakai site is ready, click the icon
5. See that the site type for the site is project

**Expected behavior**
The Sakai site type should be course instead of project when added to a non-sis course kit.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ewendland23** [comment]
Hi @joliet  - this issue should be fixed.  Thanks for the excellent description of the problem.

**Comment by joliet** [comment]
Looks good to me, Liz!
