### ISSUE TITLE
Combined Kits have no context

### ISSUE THREAD

**Issue by joliet** [DukeLearningInnovation/kits#715]
I am instructor trying to find my kit from Spring 2020 but it is difficult to find because there is no organizational structure for combined kits.  Since all of my courses are multi-section, all of my kits are combined kits and hard to navigate.

How might we (the Kits project team) better organize combined kits?

**Questions**

**Assumptions**

**Hypotheses**

**Comment by joliet** [comment]
How we might solve this:

- Add constraint of not allowing non-sis course kits in combined kit.
- Check to see if any combined kits contain semester courses and other categories.
- Combined kit will show under semester or category.  Combined kits with official course kits in more than one semester will show in every semester represented in the kit.

**Comment by noahhh** [comment]
Hi @joliet , I've put this ticket on to test.  I was working with very limited data locally so let me know how it looks to you.

**Comment by noahhh** [comment]
@joliet I don't think so.  Since we already weren't allowing non-sis courses to be combined, I don't think there's more to test?  I am only checking for term and placing them in the term if there is a child in the term, not dealing with categories.

**Comment by joliet** [comment]
That makes sense @noahhh .  I think this is working as expected.  Not sure what Liz has that might need to go to prod as well.  Let's talk about moving work ready for prod at the start of our meeting next Tuesday.
