### ISSUE TITLE
Broken image links on app details page in App Store

### ISSUE THREAD

**Issue by joliet** [DukeLearningInnovation/kits#716]
**Describe the bug**
Links to images in app detail pages are broken.

**To Reproduce**
1. Go to Kits
2. Click on App Store
3. Click on app details for any app
4. See broken images

**Expected behavior**

**Screenshots**

<img width="932" alt="Screen Shot 2022-02-22 at 10 00 56 AM" src="https://user-images.githubusercontent.com/7387760/155159934-92b4a4a3-c2b5-4d71-82c8-a74a1f8fc8de.png">
**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by joliet** [comment]
Created this ticket in ServiceNow - https://duke.service-now.com/nav_to.do?uri=incident.do?sys_id=e9cfdc561b75419028c90f66624bcb62%26sysparm_view=itil

**Comment by noahhh** [comment]
Hi @joliet .  I spoke with Dave White about this issue.  It was easier for me to work on it than help him get set up with Kits again, as it was a fix that could be done within the Kits app.  Let me know if you have issues with it, Dave walked me through what was wrong/what we needed to do.

**Comment by joliet** [comment]
Thanks, @noahhh .  I'm still seeing the broken images even with a refresh.  Are you still working on this?

**Comment by noahhh** [comment]
Interesting, I do not see broken links.  Which apps do you see them for?  Can you try a different browser/clear cache?

**Comment by joliet** [comment]
Ok @noahhh, I cleared cache and tested in all of these browsers - Chrome, Firefox, and Safari.  The images on the app detail pages for all the apps were not showed - they showed as broken links.  Let me know if you'd like me to do more testing.

**Comment by joliet** [comment]
That's it, @noahhh !  I connected via VPN and the images are there.

**Comment by joliet** [comment]
This looks fixed @noahhh .  Thanks!  Closing.
