### ISSUE TITLE
403 Error Message

### ISSUE THREAD

**Issue by msoupcoff** [DukeLearningInnovation/kits#725]
I am course/dept/school coordinator trying to add participants to a Sakai site I created for an instructor but get a 'Kits can't connect' message when going to **Add participants** because while Sakai added me to the site as its creator, Kits does not know about me and thus I'm not in Kit. 

A more informative message to users would be helpful when they first hit error. 

Workaround/fix: DLI, OIT SD or instructor of record adds coordinator to Kit

**Comment by ewendland23** [comment]
@msoupcoff  - Can you provide the text you would like to see if they don't have access?

**Comment by msoupcoff** [comment]
@ewendland23 Can we put the following html?

```
<h2 style="text-align:center">🛑 Whoops.. Looks like you don&#39;t have access to this feature.&nbsp;🛑</h2>

<p style="text-align:center">If you are seeing this error and believe you should have access to this feature, please report the below error code & site title to the OIT Service Desk (<a href="https://oit.duke.edu/help">https://oit.duke.edu/help</a>) or Learning Innovation (<a href="mailto:learninginnovation@duke.edu">learninginnovation@duke.edu</a>) for troubleshooting and assistance.</p>

<p style="text-align:center">Error code: 403</p>
```

**Comment by msoupcoff** [comment]
Pushed into production. LI & OIT SD members have been alerted to change in UI
![403](https://user-images.githubusercontent.com/1220785/189719655-04eeabf9-c1e3-4dbe-ad38-a7e882409003.png)
