### ISSUE TITLE
What happens with cross-listed courses? Is there a master group that's created?

### ISSUE THREAD

**Issue by LASHirsh** [DukeLearningInnovation/kits#74]

**Comment by profmikegreene** [comment]
I believe users choose which course will serve as master and just add rosters to that @joliet is that correct? Is there more to it technically @ewendland23?

**Comment by joliet** [comment]
Sakai doesn't handle this well but Toolkits does.  When a Toolkit is created for one of the cross-listed offerings, the remaining cross-listed courses are automatically added to the group. The main course will likely depend on the faculty member's department, and they will want that to be the course title. I can give some specific examples if this is unclear.  Just let me know.

**Comment by swwalker** [comment]
Closed - Duplicate of #205
