### ISSUE TITLE
Dynamic designation of Featured apps in the App Store

### ISSUE THREAD

**Issue by LASHirsh** [DukeLearningInnovation/kits#75]
(copied from [Questions](https://github.com/DukeLearningInnovation/learn.duke/blob/master/apps/readme.md#questions-on-apps) on /apps)

**Comment by JustinJohnsen** [comment]
Are we trying to push apps? Are we talking here about how we want to increase use of new apps in the ecosystem?

I guess if we are 'advertising' by saying "Here is this new capability you have to do a thing and how you can initiate it." I would not like to see the app be the star, but rather what it allows a student to do.

**Comment by profmikegreene** [comment]
So the featured section is more like ‘apps for giving students better feedback’ or ‘have better online discussions’ ? That feels more learning innovation to me, we could probably do that regardless of whether we advertise specific apps or not.

I have mixed feelings about advertising apps. 
+highlight whatever we want, boosting usage and awareness, we get more ROI
-open a can of worms when other parties want to advertise things. What are our policies around the advertising space?

We could do a sprint (this whole idea not mvp1 in my mind, someone else chime in here and i’ll remove it from the milestone) to UX test advertising apps and build it in a way where it’s easy to remove at a later date if it proves problematic. Perhaps the con I mentioned above wouldn’t ever be realized and that shouldn’t stop us from trying something that would help put the right tool into users hands.
