### ISSUE TITLE
How do we incorporate OER?

### ISSUE THREAD

**Issue by LASHirsh** [DukeLearningInnovation/kits#78]
(copied from [Questions](https://github.com/DukeLearningInnovation/learn.duke/blob/master/apps/readme.md#questions-on-apps) on /apps)

**Comment by JustinJohnsen** [comment]
To me this depends some on how much the OER content is tied to a particular application. If we can separate the content itself and offer it through our own curated apps, then incorporating should be relatively easy. For example, downloading an OER video from YouTube and offering it through WarpWire, or downloading an OER textbook from OpenStax and offering it through Box.

**Comment by profmikegreene** [comment]
@joliet what are your thoughts here?

@JustinJohnsen we can’t enable users to break other services’ user agreements (downloading YouTube videos), but if we find a use case that makes sense to port content into one of our systems vs using a public OER system, we should at least discuss the idea. I’m not familiar enough with the popular OER systems to know what’s possible and what’s best for users.
