### ISSUE TITLE
Market beta to Duke community

### ISSUE THREAD

**Issue by LASHirsh** [DukeLearningInnovation/kits#80]
[Beta users list in Box](https://duke.app.box.com/notes/357015492748)

- [x] create interest form https://duke.qualtrics.com/jfe/form/SV_2lWKZ2qh2kSIGj3
- [ ] post to Sakai MOTD
- [x] meet with instructors to discuss beta
- [ ] UX test with instructors and students in beta

### The incredibly easy platform for managing the people and tools in your courses.
*Save time getting your semester setup*
[Join the Kits Beta today](https://duke.qualtrics.com/jfe/form/SV_2lWKZ2qh2kSIGj3)
<img width="1894" alt="sakai___home___overview-2" src="https://user-images.githubusercontent.com/3632822/50032642-3b190080-ffc3-11e8-9625-fefdb6214f99.png">

![kitsscreenshot](https://user-images.githubusercontent.com/3632822/50028452-becfee80-ffbd-11e8-913f-9ffe46309e5a.png)

**Comment by profmikegreene** [comment]
I worry that focusing on an academic program might skew results in some way. What do others think?

What about DSG? What about a blurb on the sakai gateway offering a prize to the first 50 students who signup or something?

**Comment by profmikegreene** [comment]
Aria C - faculty
Melody J - student
Chentian J - student

have volunteered to give feedback this spring and summer.

**Comment by swwalker** [comment]
@joliet - please confirm that you would like this to remain an issue and, if so, whether it should be done during Fall 2019 or Spring 2020
