### ISSUE TITLE
Add Delegate

### ISSUE THREAD

**Issue by profmikegreene** [DukeLearningInnovation/kits#85]
* As in _instructor_ I want to _designate a delegate to setup my course on my behalf_ because _I'm too busy or don't feel comfortable with the technology_
* As an _instructional support staff_ I need to _set up courses, manage users, and apps on behalf of instructors_ because _they are too busy or uncomfortable with technology_. 
* As a _Kits admin_, I can _add delegates for instructors on their behalf_ because _they don't have local support staff or are too busy or uncomfortable with technology_. 

How might we (the Kits project team) enable users to add other users that can perform tasks on their behalf?

**Comment by joliet** [comment]
This is related to feature:
Create an Admin area for Kits where all admin features live - https://github.com/DukeLearningInnovation/kits/issues/440

**Comment by joliet** [comment]
**Research update:** In looking at the list of delegates for faculty, and the same list of admins for Toolkits, I suspect the more useful feature is to find a way to define a sub-admin role scoped to a school.  This is the primary use case for this feature.  Most people don't support just one or a handful of faculty/users.  Their support spans an entire school and trying to manage access at the delegate level would probably be frustrating and time-consuming for everyone.  Let's focus on a sub-admin feature as a priority, and then see re-evaluate this feature as issues come up.

**Comment by swwalker** [comment]
Addressed by other issues.  Closing
