### ISSUE TITLE
Bulk add members to kit

### ISSUE THREAD

**Issue by LASHirsh** [DukeLearningInnovation/kits#92]
- As an instructor, I need to batch add netids/DUIDs/emails to a kit and select their role because they are part of our learning community.
- As an instructor, I need to add an existing grouper/LDAP/Active Directory group and select their role to my kit because they are part of our learning community
- As an instructor, I need to import a CSV of netids/DUIDS/emails that contains roles to a kit because they are part of our learning community

### Assumptions
- This functionality will be more useful for user-created kits than course kits because membership of those kits is more flexible without a roster

**Comment by joliet** [comment]
Since this epic contains more that one feature (with one already in production), I have created issues for the remaining pieces to be built.

#414 Bulk add existing grouper/LDAP/AD groups to kit
#415 Bulk add users to kit via CSV import of netids/DUIDs/emails
