### ISSUE TITLE
Define and label all our nouns

### ISSUE THREAD

**Issue by profmikegreene** [DukeLearningInnovation/kits#93]
what is a 
course
tool
faculty/instructor/delegates

**Comment by profmikegreene** [comment]
![concept_wireframes_-_v1_-_uxpin_preview](https://user-images.githubusercontent.com/3632822/38891010-11290be2-4251-11e8-8fea-89f6fae36d69.png)

Did some guerilla UX with Aria's class
Q1 - what to call the pink boxes
* workspace
* workstation
* wall
* card
* bag
* community
* backpack


Q2 - what to call the orange boxes
* widget
* box
* tiles
* tools
* apps
* applets
* elements
* components
* cards
* packet
* bit
* nugget
* pocket
* pieces of a whole thing that make sense metaphorically

Q3 - what to call this website
* backpack
* gateway
* dukenexus
* roadmap
* turnpike
* environment
* things come together
* learning environment
* ecosystem
* learning experiences
* learning board
* canvas
* don't put learning in the name because it should be a single place for more than courses

**Comment by profmikegreene** [comment]
Service names from Justin
* affinity/concord
* enclave/sodality
* conduit/estuary
* hub/fulcrum/convergence/locus
* HQ/ops

Riffing off those - kin

**Comment by profmikegreene** [comment]
What about cafe https://www.wikiwand.com/en/English_coffeehouses_in_the_17th_and_18th_centuries or salon https://www.wikiwand.com/en/Salon_(gathering) for the name of the service?

**Comment by JustinJohnsen** [comment]
More random service name ideas:  nova, zenith, kaishi, gurupu, axis

More tool name ideas:  blocks, cogs, layers, links, gadgets, gizmos, 
(I also favor tiles, apps, components, or widgets from above)

More learning community name ideas:  array, collection, mosaic
(affinity, concord, enclave, sodality, locus, and hub could also work here, and I like card or backpack from above, too)

Combo name suggestions:
- _kaishi.duke.edu_ has many _affinities_ containing _apps_
- _nexus.duke.edu_ has many _enclaves_ containing _cogs_
- _concord.duke.edu_ has many _mosaics_ containing _tiles_
- _ops.duke.edu_ has many _collections_ containing _components_
- _locus.duke.edu_ has many _hubs_ containing _links_
- _conduit.duke.edu_ has many _arrays_ containing _widgets_

**Comment by hrvalli** [comment]
I like "gizmos"!

**Comment by profmikegreene** [comment]
Member vs participant 
Participant is a role in the system
Member is a person in a community
Membership is all the members of the community regardless of roles, participant being one of them

- [ ] rename member to participant everywhere to avoid confusion between member and membership.

**Comment by profmikegreene** [comment]
How about slate for the service name?

**Comment by mzrascoff** [comment]
What do you think about Intaglio?

It's a form of printing "in which the image is incised into a surface and the incised line or sunken area holds the ink". 

https://en.wikipedia.org/wiki/Intaglio_(printmaking)

The idea is that the tech should be a direct image formed from the learning. The mirror image that makes the learning "print".

**Comment by profmikegreene** [comment]
We hosted a service-naming brainstorm yesterday with Matthew, Shawn, Courtney, Justin, and I. We separated the discussion into 3 areas.

### Themes/Feelings the service should evoke
* learner experience home page
* reddit like
* aggregator, tiler
* hub, plat to find what you need
* intuitive
* uncluttered
* clean and simple, essential
* app store
* curated, quality control. Good options
* accessible to those unfamiliar with edtech and teaching
* open
* unbounded
* just in time
* cathedral and the bazaar
* remixing
* expose the guts
* non-aol version of online
* allow the designed learning experience
* expose learners and faculty to the real web. Critical thinking
* transparancy through tools
* decision making
* socket
* switch in switch out
* modularity
* pluralism for faculty and students
* convergence
* colearning cocreation
* groups and community

### The brand of the service
* contemporary
* Techie
* the edge
* the colab
* sans serif
* fun
* provost-friendly
* matrix
* next gen
* cutting edge
* clean
* works well
* integrated
* **curated**
* history and future
* Marketplace - market
* behind the scenes
* like the wirecutter blog. Make decisions transparent. Reveal our criteria. Link to research evidence
* consumer choice/power
* best ed
* trustworthy
* center
* hq
* coworking

### Possible names of the service
* port city
* board
* Blue board
* roundtable
* learning blocks
* groove
* **port**
* harbor
* wharf
* edtech
* **rialto**
* **grand bazaar**
* portico
* **lx**
* hq
* switchboard
* LA :: learning agency (like freedom, not organization)
* L
* lip :: learning independence portal
* LP :: learning port

**Comment by clockemer** [comment]
A couple other name ideas:

- assemble
- build
- remix
- emporium

Also, I wanted to point out that the name of the service and the URL don't have to be precisely the same. For example,

- Duke Learning Port/port.duke.edu
- Education Builder/build.duke.edu

**Comment by joliet** [comment]
If we are putting nouns out there:

- lift
- grow
- edify
- teach

Non-noun ideas:

- scholar

**Comment by profmikegreene** [comment]
@LASHirsh is baking some of the nouns into the current mockups @bap13 @thegreenbot . If there are still unknowns, would you message me?

**Comment by bap13** [comment]
@profmikegreene will do, but I think I am getting confused between what we are referencing as "Nouns" vs. "component names". Jen and I really only need to know **component names**, which will hopefully reflect or reference the nouns you are coming up with...

**Comment by swwalker** [comment]
Regarding product name, an informal survey of 6 rising Duke sophomores currently interning in OIT, they proposed “Class Manager” or “Course Central”.  When prompted that the vision of the tool would be for any learning community, including those beyond courses, they did not respond with any additional feedback, they continued returning to those two names.  

Could be the name doesn't have to encompass all functions in order for people to understand the breadth of the tool.

**Comment by swwalker** [comment]
As the naming question has been turning over in the back of my mind and I have reached the point in my day when I am more apt to free-associate, the phrase "port in the storm" keeps coming to the fore.  Consistent with other feedback in the thread, and seems particularly applicable to feelings some of the target community may have of being in a storm, particularly at the beginning and end of a semester where information and task overload is at peak.
