### ISSUE TITLE
[MANAGE MEMBERSHIP] As a leader, I want to view and edit my community membership and their roles so that I can determine if the group list and permissions need to be changed and update them as necessary, because the official course enrollment  data from SIS does not include ad-hoc additions such as auditors, visitors, and TAs that  I need to teach my course.

### ISSUE THREAD

**Issue by LASHirsh** [DukeLearningInnovation/kits#95]

**Comment by profmikegreene** [comment]
We haven't discussed official role names yet, but it will be more robust than only instructor of record gets admin access. Current toolkits roles below.


Toolkits Role | Sakai Course Site Equivalent
--- | ---
Instructor | Instructor
Manager | Instructor
TA | Teaching Assistant
Developer | Course Builder
Mentor | Teaching Assistant
Student | Student
Auditor | Student
Visitor | Visitor

Toolkits Role | Sakai Project Site Equivalent
---|---
Admin | maintain
Contributor | access
Visitor | Visitor


Toolkits Role | WordPress Equivalent
--- | ---
Instructor | Administrator
Manager | Administrator
TA | Administrator
Admin | Administrator
Developer | Editor
Mentor | Editor
Contributor | Editor
Student | Author
Visitor/Auditor | Subscriber

**Comment by profmikegreene** [comment]
![0](https://user-images.githubusercontent.com/3632822/38898558-50f87ad4-4263-11e8-8e15-47a95e160818.JPG)

**Comment by swwalker** [comment]
closed - referenced in #199
